// Code generated by mockery v2.53.5. DO NOT EDIT.

package testing

import (
	context "context"

	api "github.com/Uncensored-Developer/datalk/apps/backend/services/connections/api"
	connections "github.com/Uncensored-Developer/datalk/apps/backend/services/connections/pkg/connections"
	mock "github.com/stretchr/testify/mock"
)

// API is an autogenerated mock type for the Client type
type API struct {
	mock.Mock
}

// CreateAccess provides a mock function with given fields: ctx, params
func (_m *API) CreateAccess(ctx context.Context, params api.NewAccessParams) (*connections.Access, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccess")
	}

	var r0 *connections.Access
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, api.NewAccessParams) (*connections.Access, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, api.NewAccessParams) *connections.Access); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*connections.Access)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, api.NewAccessParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateConnection provides a mock function with given fields: ctx, params
func (_m *API) CreateConnection(ctx context.Context, params api.NewConnectionParams) (*connections.Connection, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateConnection")
	}

	var r0 *connections.Connection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, api.NewConnectionParams) (*connections.Connection, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, api.NewConnectionParams) *connections.Connection); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*connections.Connection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, api.NewConnectionParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteConnection provides a mock function with given fields: ctx, connectionID
func (_m *API) DeleteConnection(ctx context.Context, connectionID int32) error {
	ret := _m.Called(ctx, connectionID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteConnection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, connectionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAccess provides a mock function with given fields: ctx, userID, connectionID
func (_m *API) GetAccess(ctx context.Context, userID int32, connectionID int32) (*connections.Access, error) {
	ret := _m.Called(ctx, userID, connectionID)

	if len(ret) == 0 {
		panic("no return value specified for GetAccess")
	}

	var r0 *connections.Access
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) (*connections.Access, error)); ok {
		return rf(ctx, userID, connectionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) *connections.Access); ok {
		r0 = rf(ctx, userID, connectionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*connections.Access)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, int32) error); ok {
		r1 = rf(ctx, userID, connectionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetConnection provides a mock function with given fields: ctx, ID
func (_m *API) GetConnection(ctx context.Context, ID int32) (*connections.Connection, error) {
	ret := _m.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for GetConnection")
	}

	var r0 *connections.Connection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (*connections.Connection, error)); ok {
		return rf(ctx, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) *connections.Connection); ok {
		r0 = rf(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*connections.Connection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAccess provides a mock function with given fields: ctx, params
func (_m *API) ListAccess(ctx context.Context, params api.ListAccessParams) ([]*connections.Access, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListAccess")
	}

	var r0 []*connections.Access
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, api.ListAccessParams) ([]*connections.Access, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, api.ListAccessParams) []*connections.Access); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*connections.Access)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, api.ListAccessParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListConnections provides a mock function with given fields: ctx, params
func (_m *API) ListConnections(ctx context.Context, params api.ListConnectionsParams) ([]*connections.Connection, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListConnections")
	}

	var r0 []*connections.Connection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, api.ListConnectionsParams) ([]*connections.Connection, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, api.ListConnectionsParams) []*connections.Connection); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*connections.Connection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, api.ListConnectionsParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TestConnection provides a mock function with given fields: ctx, params
func (_m *API) TestConnection(ctx context.Context, params api.TestConnectionParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for TestConnection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, api.TestConnectionParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateConnection provides a mock function with given fields: ctx, params
func (_m *API) UpdateConnection(ctx context.Context, params api.UpdateConnectionParams) (*connections.Connection, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for UpdateConnection")
	}

	var r0 *connections.Connection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, api.UpdateConnectionParams) (*connections.Connection, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, api.UpdateConnectionParams) *connections.Connection); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*connections.Connection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, api.UpdateConnectionParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAPI creates a new instance of API. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAPI(t interface {
	mock.TestingT
	Cleanup(func())
},
) *API {
	mock := &API{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
