version: "3.8"
services:
  datalk-postgres:
    container_name: datalk_db
    image: "pgvector/pgvector:pg15"
    volumes:
      - "./db/init:/docker-entrypoint-initdb.d"
      - "datalk-postgres-data:/var/lib/postgresql/data"
    ports:
      - "5437:5432"
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "postgres",
          "-h",
          "localhost"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

volumes:
  datalk-postgres-data:
  datalk-redis-data: