// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"github.com/stephenafamo/bob/clause"
	"github.com/stephenafamo/bob/dialect/sqlite"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
)

var (
	SelectWhere     = Where[*dialect.SelectQuery]()
	UpdateWhere     = Where[*dialect.UpdateQuery]()
	DeleteWhere     = Where[*dialect.DeleteQuery]()
	OnConflictWhere = Where[*clause.ConflictClause]() // Used in ON CONFLICT DO UPDATE
)

func Where[Q sqlite.Filterable]() struct {
	ConnectionAccesses connectionAccessWhere[Q]
	Connections        connectionWhere[Q]
	Organizations      organizationWhere[Q]
	Users              userWhere[Q]
} {
	return struct {
		ConnectionAccesses connectionAccessWhere[Q]
		Connections        connectionWhere[Q]
		Organizations      organizationWhere[Q]
		Users              userWhere[Q]
	}{
		ConnectionAccesses: buildConnectionAccessWhere[Q](ConnectionAccesses.Columns),
		Connections:        buildConnectionWhere[Q](Connections.Columns),
		Organizations:      buildOrganizationWhere[Q](Organizations.Columns),
		Users:              buildUserWhere[Q](Users.Columns),
	}
}
