// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
	"github.com/stephenafamo/scan"
)

// ChatMessage is an object representing the database table.
type ChatMessage struct {
	ID              int64            `db:"id,pk" `
	ConversationID  int64            `db:"conversation_id" `
	Role            string           `db:"role" `
	Content         string           `db:"content" `
	Provider        null.Val[string] `db:"provider" `
	Model           null.Val[string] `db:"model" `
	Status          string           `db:"status" `
	ErrorMessage    null.Val[string] `db:"error_message" `
	CreatedAt       time.Time        `db:"created_at" `
	NaturalResponse null.Val[string] `db:"natural_response" `

	R chatMessageR `db:"-" `

	C chatMessageC `db:"-" `
}

// ChatMessageSlice is an alias for a slice of pointers to ChatMessage.
// This should almost always be used instead of []*ChatMessage.
type ChatMessageSlice []*ChatMessage

// ChatMessages contains methods to work with the chat_messages table
var ChatMessages = psql.NewTablex[*ChatMessage, ChatMessageSlice, *ChatMessageSetter]("", "chat_messages", buildChatMessageColumns("chat_messages"))

// ChatMessagesQuery is a query on the chat_messages table
type ChatMessagesQuery = *psql.ViewQuery[*ChatMessage, ChatMessageSlice]

// chatMessageR is where relationships are stored.
type chatMessageR struct {
	MessageChatMessageExecution  *ChatMessageExecution   // chat_message_executions.chat_message_executions_message_id_fkey
	MessageChatMessageLLMCalls   ChatMessageLLMCallSlice // chat_message_llm_calls.chat_message_llm_calls_message_id_fkey
	MessageChatMessageRetrieval  *ChatMessageRetrieval   // chat_message_retrievals.chat_message_retrievals_message_id_fkey
	ConversationChatConversation *ChatConversation       // chat_messages.chat_messages_conversation_id_fkey
	// Loaded reports whether each relationship has been loaded.
	// A relationship's bool is set by Load*, Preload, ThenLoad, factory builds,
	// and to-one Attach/Insert operations. To-many Attach/Insert operations leave it unchanged.
	Loaded chatMessageRLoaded `db:"-" `
}

// chatMessageRLoaded tracks which relationships on ChatMessage have been loaded.
type chatMessageRLoaded struct {
	MessageChatMessageExecution  bool // chat_message_executions.chat_message_executions_message_id_fkey
	MessageChatMessageLLMCalls   bool // chat_message_llm_calls.chat_message_llm_calls_message_id_fkey
	MessageChatMessageRetrieval  bool // chat_message_retrievals.chat_message_retrievals_message_id_fkey
	ConversationChatConversation bool // chat_messages.chat_messages_conversation_id_fkey
}

func buildChatMessageColumns(tableName string) chatMessageColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "conversation_id", "role", "content", "provider", "model", "status", "error_message", "created_at", "natural_response",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return chatMessageColumns{
		ColumnsExpr:     columnsExpr,
		tableAlias:      tableName,
		ID:              buildChatMessageColumn(tableName, "id"),
		ConversationID:  buildChatMessageColumn(tableName, "conversation_id"),
		Role:            buildChatMessageColumn(tableName, "role"),
		Content:         buildChatMessageColumn(tableName, "content"),
		Provider:        buildChatMessageColumn(tableName, "provider"),
		Model:           buildChatMessageColumn(tableName, "model"),
		Status:          buildChatMessageColumn(tableName, "status"),
		ErrorMessage:    buildChatMessageColumn(tableName, "error_message"),
		CreatedAt:       buildChatMessageColumn(tableName, "created_at"),
		NaturalResponse: buildChatMessageColumn(tableName, "natural_response"),
	}
}

type chatMessageColumns struct {
	expr.ColumnsExpr
	tableAlias      string
	ID              chatMessageColumn
	ConversationID  chatMessageColumn
	Role            chatMessageColumn
	Content         chatMessageColumn
	Provider        chatMessageColumn
	Model           chatMessageColumn
	Status          chatMessageColumn
	ErrorMessage    chatMessageColumn
	CreatedAt       chatMessageColumn
	NaturalResponse chatMessageColumn
}

// Alias returns the current table alias for the columns set.
func (c chatMessageColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (chatMessageColumns) AliasedAs(tableName string) chatMessageColumns {
	return buildChatMessageColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c chatMessageColumns) Unqualified() chatMessageColumns {
	return buildChatMessageColumns("")
}

func buildChatMessageColumn(alias, name string) chatMessageColumn {
	return chatMessageColumn{
		Expression: psql.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type chatMessageColumn struct {
	psql.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c chatMessageColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c chatMessageColumn) ShouldOmitParens() bool {
	return true
}

// ChatMessageSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type ChatMessageSetter struct {
	ID              omit.Val[int64]      `db:"id,pk" `
	ConversationID  omit.Val[int64]      `db:"conversation_id" `
	Role            omit.Val[string]     `db:"role" `
	Content         omit.Val[string]     `db:"content" `
	Provider        omitnull.Val[string] `db:"provider" `
	Model           omitnull.Val[string] `db:"model" `
	Status          omit.Val[string]     `db:"status" `
	ErrorMessage    omitnull.Val[string] `db:"error_message" `
	CreatedAt       omit.Val[time.Time]  `db:"created_at" `
	NaturalResponse omitnull.Val[string] `db:"natural_response" `
}

func (s ChatMessageSetter) SetColumns() []string {
	vals := make([]string, 0, 10)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.ConversationID.IsValue() {
		vals = append(vals, "conversation_id")
	}
	if s.Role.IsValue() {
		vals = append(vals, "role")
	}
	if s.Content.IsValue() {
		vals = append(vals, "content")
	}
	if !s.Provider.IsUnset() {
		vals = append(vals, "provider")
	}
	if !s.Model.IsUnset() {
		vals = append(vals, "model")
	}
	if s.Status.IsValue() {
		vals = append(vals, "status")
	}
	if !s.ErrorMessage.IsUnset() {
		vals = append(vals, "error_message")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if !s.NaturalResponse.IsUnset() {
		vals = append(vals, "natural_response")
	}
	return vals
}

func (s ChatMessageSetter) Overwrite(t *ChatMessage) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.ConversationID.IsValue() {
		t.ConversationID = s.ConversationID.MustGet()
	}
	if s.Role.IsValue() {
		t.Role = s.Role.MustGet()
	}
	if s.Content.IsValue() {
		t.Content = s.Content.MustGet()
	}
	if !s.Provider.IsUnset() {
		t.Provider = s.Provider.MustGetNull()
	}
	if !s.Model.IsUnset() {
		t.Model = s.Model.MustGetNull()
	}
	if s.Status.IsValue() {
		t.Status = s.Status.MustGet()
	}
	if !s.ErrorMessage.IsUnset() {
		t.ErrorMessage = s.ErrorMessage.MustGetNull()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if !s.NaturalResponse.IsUnset() {
		t.NaturalResponse = s.NaturalResponse.MustGetNull()
	}
}

func (s *ChatMessageSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return ChatMessages.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 10)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.ConversationID.IsValue() {
			vals[1] = psql.Arg(s.ConversationID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Role.IsValue() {
			vals[2] = psql.Arg(s.Role.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.Content.IsValue() {
			vals[3] = psql.Arg(s.Content.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if !s.Provider.IsUnset() {
			vals[4] = psql.Arg(s.Provider.MustGetNull())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if !s.Model.IsUnset() {
			vals[5] = psql.Arg(s.Model.MustGetNull())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.Status.IsValue() {
			vals[6] = psql.Arg(s.Status.MustGet())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if !s.ErrorMessage.IsUnset() {
			vals[7] = psql.Arg(s.ErrorMessage.MustGetNull())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[8] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[8] = psql.Raw("DEFAULT")
		}

		if !s.NaturalResponse.IsUnset() {
			vals[9] = psql.Arg(s.NaturalResponse.MustGetNull())
		} else {
			vals[9] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s ChatMessageSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s ChatMessageSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 10)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.ConversationID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "conversation_id")...),
			psql.Arg(s.ConversationID),
		}})
	}

	if s.Role.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "role")...),
			psql.Arg(s.Role),
		}})
	}

	if s.Content.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "content")...),
			psql.Arg(s.Content),
		}})
	}

	if !s.Provider.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "provider")...),
			psql.Arg(s.Provider),
		}})
	}

	if !s.Model.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "model")...),
			psql.Arg(s.Model),
		}})
	}

	if s.Status.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "status")...),
			psql.Arg(s.Status),
		}})
	}

	if !s.ErrorMessage.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "error_message")...),
			psql.Arg(s.ErrorMessage),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if !s.NaturalResponse.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "natural_response")...),
			psql.Arg(s.NaturalResponse),
		}})
	}

	return exprs
}

// FindChatMessage retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindChatMessage(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*ChatMessage, error) {
	if len(cols) == 0 {
		return ChatMessages.Query(
			sm.Where(ChatMessages.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return ChatMessages.Query(
		sm.Where(ChatMessages.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(ChatMessages.Columns.Only(cols...)),
	).One(ctx, exec)
}

// ChatMessageExists checks the presence of a single record by primary key
func ChatMessageExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return ChatMessages.Query(
		sm.Where(ChatMessages.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after ChatMessage is retrieved from the database
func (o *ChatMessage) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = ChatMessages.AfterSelectHooks.RunHooks(ctx, exec, ChatMessageSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = ChatMessages.AfterInsertHooks.RunHooks(ctx, exec, ChatMessageSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = ChatMessages.AfterUpdateHooks.RunHooks(ctx, exec, ChatMessageSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = ChatMessages.AfterDeleteHooks.RunHooks(ctx, exec, ChatMessageSlice{o})
	case bob.QueryTypeMerge:
		ctx, err = ChatMessages.AfterMergeHooks.RunHooks(ctx, exec, ChatMessageSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the ChatMessage
func (o *ChatMessage) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *ChatMessage) pkEQ() dialect.Expression {
	return psql.Quote("chat_messages", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the ChatMessage
func (o *ChatMessage) Update(ctx context.Context, exec bob.Executor, s *ChatMessageSetter) error {
	v, err := ChatMessages.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single ChatMessage record with an executor
func (o *ChatMessage) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := ChatMessages.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the ChatMessage using the executor
func (o *ChatMessage) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := ChatMessages.Query(
		sm.Where(ChatMessages.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after ChatMessageSlice is retrieved from the database
func (o ChatMessageSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = ChatMessages.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = ChatMessages.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = ChatMessages.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = ChatMessages.AfterDeleteHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeMerge:
		ctx, err = ChatMessages.AfterMergeHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o ChatMessageSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("chat_messages", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o ChatMessageSlice) copyMatchingRows(from ...*ChatMessage) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o ChatMessageSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return ChatMessages.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *ChatMessage:
				o.copyMatchingRows(retrieved)
			case []*ChatMessage:
				o.copyMatchingRows(retrieved...)
			case ChatMessageSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a ChatMessage or a slice of ChatMessage
				// then run the AfterUpdateHooks on the slice
				_, err = ChatMessages.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o ChatMessageSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return ChatMessages.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *ChatMessage:
				o.copyMatchingRows(retrieved)
			case []*ChatMessage:
				o.copyMatchingRows(retrieved...)
			case ChatMessageSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a ChatMessage or a slice of ChatMessage
				// then run the AfterDeleteHooks on the slice
				_, err = ChatMessages.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// MergeMod modifies a merge query to run BeforeMergeHooks and AfterMergeHooks
// and updates the slice with the returned rows.
func (o ChatMessageSlice) MergeMod() bob.Mod[*dialect.MergeQuery] {
	return bob.ModFunc[*dialect.MergeQuery](func(q *dialect.MergeQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return ChatMessages.BeforeMergeHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *ChatMessage:
				o.copyMatchingRows(retrieved)
			case []*ChatMessage:
				o.copyMatchingRows(retrieved...)
			case ChatMessageSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a ChatMessage or a slice of ChatMessage
				// then run the AfterMergeHooks on the slice
				_, err = ChatMessages.AfterMergeHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))
	})
}

func (o ChatMessageSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals ChatMessageSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := ChatMessages.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o ChatMessageSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := ChatMessages.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o ChatMessageSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := ChatMessages.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// MessageChatMessageExecution starts a query for related objects on chat_message_executions
func (o *ChatMessage) MessageChatMessageExecution(mods ...bob.Mod[*dialect.SelectQuery]) ChatMessageExecutionsQuery {
	return ChatMessageExecutions.Query(append(mods,
		sm.Where(ChatMessageExecutions.Columns.MessageID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os ChatMessageSlice) MessageChatMessageExecution(mods ...bob.Mod[*dialect.SelectQuery]) ChatMessageExecutionsQuery {
	pkID := make(pgtypes.Array[int64], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "bigint[]")),
	))

	return ChatMessageExecutions.Query(append(mods,
		sm.Where(psql.Group(ChatMessageExecutions.Columns.MessageID).OP("IN", PKArgExpr)),
	)...)
}

// MessageChatMessageLLMCalls starts a query for related objects on chat_message_llm_calls
func (o *ChatMessage) MessageChatMessageLLMCalls(mods ...bob.Mod[*dialect.SelectQuery]) ChatMessageLLMCallsQuery {
	return ChatMessageLLMCalls.Query(append(mods,
		sm.Where(ChatMessageLLMCalls.Columns.MessageID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os ChatMessageSlice) MessageChatMessageLLMCalls(mods ...bob.Mod[*dialect.SelectQuery]) ChatMessageLLMCallsQuery {
	pkID := make(pgtypes.Array[int64], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "bigint[]")),
	))

	return ChatMessageLLMCalls.Query(append(mods,
		sm.Where(psql.Group(ChatMessageLLMCalls.Columns.MessageID).OP("IN", PKArgExpr)),
	)...)
}

// MessageChatMessageRetrieval starts a query for related objects on chat_message_retrievals
func (o *ChatMessage) MessageChatMessageRetrieval(mods ...bob.Mod[*dialect.SelectQuery]) ChatMessageRetrievalsQuery {
	return ChatMessageRetrievals.Query(append(mods,
		sm.Where(ChatMessageRetrievals.Columns.MessageID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os ChatMessageSlice) MessageChatMessageRetrieval(mods ...bob.Mod[*dialect.SelectQuery]) ChatMessageRetrievalsQuery {
	pkID := make(pgtypes.Array[int64], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "bigint[]")),
	))

	return ChatMessageRetrievals.Query(append(mods,
		sm.Where(psql.Group(ChatMessageRetrievals.Columns.MessageID).OP("IN", PKArgExpr)),
	)...)
}

// ConversationChatConversation starts a query for related objects on chat_conversations
func (o *ChatMessage) ConversationChatConversation(mods ...bob.Mod[*dialect.SelectQuery]) ChatConversationsQuery {
	return ChatConversations.Query(append(mods,
		sm.Where(ChatConversations.Columns.ID.EQ(psql.Arg(o.ConversationID))),
	)...)
}

func (os ChatMessageSlice) ConversationChatConversation(mods ...bob.Mod[*dialect.SelectQuery]) ChatConversationsQuery {
	pkConversationID := make(pgtypes.Array[int64], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkConversationID = append(pkConversationID, o.ConversationID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkConversationID), "bigint[]")),
	))

	return ChatConversations.Query(append(mods,
		sm.Where(psql.Group(ChatConversations.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func insertChatMessageMessageChatMessageExecution0(ctx context.Context, exec bob.Executor, chatMessageExecution1 *ChatMessageExecutionSetter, chatMessage0 *ChatMessage) (*ChatMessageExecution, error) {
	chatMessageExecution1.MessageID = omit.From(chatMessage0.ID)

	ret, err := ChatMessageExecutions.Insert(chatMessageExecution1).One(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertChatMessageMessageChatMessageExecution0: %w", err)
	}

	return ret, nil
}

func attachChatMessageMessageChatMessageExecution0(ctx context.Context, exec bob.Executor, count int, chatMessageExecution1 *ChatMessageExecution, chatMessage0 *ChatMessage) (*ChatMessageExecution, error) {
	setter := &ChatMessageExecutionSetter{
		MessageID: omit.From(chatMessage0.ID),
	}

	err := chatMessageExecution1.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachChatMessageMessageChatMessageExecution0: %w", err)
	}

	return chatMessageExecution1, nil
}

func (chatMessage0 *ChatMessage) InsertMessageChatMessageExecution(ctx context.Context, exec bob.Executor, related *ChatMessageExecutionSetter) error {
	var err error

	chatMessageExecution1, err := insertChatMessageMessageChatMessageExecution0(ctx, exec, related, chatMessage0)
	if err != nil {
		return err
	}

	chatMessage0.R.MessageChatMessageExecution = chatMessageExecution1
	chatMessage0.R.Loaded.MessageChatMessageExecution = true

	return nil
}

func (chatMessage0 *ChatMessage) AttachMessageChatMessageExecution(ctx context.Context, exec bob.Executor, chatMessageExecution1 *ChatMessageExecution) error {
	var err error

	_, err = attachChatMessageMessageChatMessageExecution0(ctx, exec, 1, chatMessageExecution1, chatMessage0)
	if err != nil {
		return err
	}

	chatMessage0.R.MessageChatMessageExecution = chatMessageExecution1
	chatMessage0.R.Loaded.MessageChatMessageExecution = true

	return nil
}

func insertChatMessageMessageChatMessageLLMCalls0(ctx context.Context, exec bob.Executor, chatMessageLLMCalls1 []*ChatMessageLLMCallSetter, chatMessage0 *ChatMessage) (ChatMessageLLMCallSlice, error) {
	for i := range chatMessageLLMCalls1 {
		chatMessageLLMCalls1[i].MessageID = omit.From(chatMessage0.ID)
	}

	ret, err := ChatMessageLLMCalls.Insert(bob.ToMods(chatMessageLLMCalls1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertChatMessageMessageChatMessageLLMCalls0: %w", err)
	}

	return ret, nil
}

func attachChatMessageMessageChatMessageLLMCalls0(ctx context.Context, exec bob.Executor, count int, chatMessageLLMCalls1 ChatMessageLLMCallSlice, chatMessage0 *ChatMessage) (ChatMessageLLMCallSlice, error) {
	setter := &ChatMessageLLMCallSetter{
		MessageID: omit.From(chatMessage0.ID),
	}

	err := chatMessageLLMCalls1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachChatMessageMessageChatMessageLLMCalls0: %w", err)
	}

	return chatMessageLLMCalls1, nil
}

func (chatMessage0 *ChatMessage) InsertMessageChatMessageLLMCalls(ctx context.Context, exec bob.Executor, related ...*ChatMessageLLMCallSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	chatMessageLLMCalls1, err := insertChatMessageMessageChatMessageLLMCalls0(ctx, exec, related, chatMessage0)
	if err != nil {
		return err
	}

	chatMessage0.R.MessageChatMessageLLMCalls = append(chatMessage0.R.MessageChatMessageLLMCalls, chatMessageLLMCalls1...)

	return nil
}

func (chatMessage0 *ChatMessage) AttachMessageChatMessageLLMCalls(ctx context.Context, exec bob.Executor, related ...*ChatMessageLLMCall) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	chatMessageLLMCalls1 := ChatMessageLLMCallSlice(related)

	_, err = attachChatMessageMessageChatMessageLLMCalls0(ctx, exec, len(related), chatMessageLLMCalls1, chatMessage0)
	if err != nil {
		return err
	}

	chatMessage0.R.MessageChatMessageLLMCalls = append(chatMessage0.R.MessageChatMessageLLMCalls, chatMessageLLMCalls1...)

	return nil
}

func insertChatMessageMessageChatMessageRetrieval0(ctx context.Context, exec bob.Executor, chatMessageRetrieval1 *ChatMessageRetrievalSetter, chatMessage0 *ChatMessage) (*ChatMessageRetrieval, error) {
	chatMessageRetrieval1.MessageID = omit.From(chatMessage0.ID)

	ret, err := ChatMessageRetrievals.Insert(chatMessageRetrieval1).One(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertChatMessageMessageChatMessageRetrieval0: %w", err)
	}

	return ret, nil
}

func attachChatMessageMessageChatMessageRetrieval0(ctx context.Context, exec bob.Executor, count int, chatMessageRetrieval1 *ChatMessageRetrieval, chatMessage0 *ChatMessage) (*ChatMessageRetrieval, error) {
	setter := &ChatMessageRetrievalSetter{
		MessageID: omit.From(chatMessage0.ID),
	}

	err := chatMessageRetrieval1.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachChatMessageMessageChatMessageRetrieval0: %w", err)
	}

	return chatMessageRetrieval1, nil
}

func (chatMessage0 *ChatMessage) InsertMessageChatMessageRetrieval(ctx context.Context, exec bob.Executor, related *ChatMessageRetrievalSetter) error {
	var err error

	chatMessageRetrieval1, err := insertChatMessageMessageChatMessageRetrieval0(ctx, exec, related, chatMessage0)
	if err != nil {
		return err
	}

	chatMessage0.R.MessageChatMessageRetrieval = chatMessageRetrieval1
	chatMessage0.R.Loaded.MessageChatMessageRetrieval = true

	return nil
}

func (chatMessage0 *ChatMessage) AttachMessageChatMessageRetrieval(ctx context.Context, exec bob.Executor, chatMessageRetrieval1 *ChatMessageRetrieval) error {
	var err error

	_, err = attachChatMessageMessageChatMessageRetrieval0(ctx, exec, 1, chatMessageRetrieval1, chatMessage0)
	if err != nil {
		return err
	}

	chatMessage0.R.MessageChatMessageRetrieval = chatMessageRetrieval1
	chatMessage0.R.Loaded.MessageChatMessageRetrieval = true

	return nil
}

func attachChatMessageConversationChatConversation0(ctx context.Context, exec bob.Executor, count int, chatMessage0 *ChatMessage, chatConversation1 *ChatConversation) (*ChatMessage, error) {
	setter := &ChatMessageSetter{
		ConversationID: omit.From(chatConversation1.ID),
	}

	err := chatMessage0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachChatMessageConversationChatConversation0: %w", err)
	}

	return chatMessage0, nil
}

func (chatMessage0 *ChatMessage) InsertConversationChatConversation(ctx context.Context, exec bob.Executor, related *ChatConversationSetter) error {
	var err error

	chatConversation1, err := ChatConversations.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachChatMessageConversationChatConversation0(ctx, exec, 1, chatMessage0, chatConversation1)
	if err != nil {
		return err
	}

	chatMessage0.R.ConversationChatConversation = chatConversation1
	chatMessage0.R.Loaded.ConversationChatConversation = true

	return nil
}

func (chatMessage0 *ChatMessage) AttachConversationChatConversation(ctx context.Context, exec bob.Executor, chatConversation1 *ChatConversation) error {
	var err error

	_, err = attachChatMessageConversationChatConversation0(ctx, exec, 1, chatMessage0, chatConversation1)
	if err != nil {
		return err
	}

	chatMessage0.R.ConversationChatConversation = chatConversation1
	chatMessage0.R.Loaded.ConversationChatConversation = true

	return nil
}

type chatMessageWhere[Q psql.Filterable] struct {
	ID              psql.WhereMod[Q, int64]
	ConversationID  psql.WhereMod[Q, int64]
	Role            psql.WhereMod[Q, string]
	Content         psql.WhereMod[Q, string]
	Provider        psql.WhereNullMod[Q, string]
	Model           psql.WhereNullMod[Q, string]
	Status          psql.WhereMod[Q, string]
	ErrorMessage    psql.WhereNullMod[Q, string]
	CreatedAt       psql.WhereMod[Q, time.Time]
	NaturalResponse psql.WhereNullMod[Q, string]
}

func (chatMessageWhere[Q]) AliasedAs(alias string) chatMessageWhere[Q] {
	return buildChatMessageWhere[Q](buildChatMessageColumns(alias))
}

func buildChatMessageWhere[Q psql.Filterable](cols chatMessageColumns) chatMessageWhere[Q] {
	return chatMessageWhere[Q]{
		ID:              psql.Where[Q, int64](cols.ID.Expression),
		ConversationID:  psql.Where[Q, int64](cols.ConversationID.Expression),
		Role:            psql.Where[Q, string](cols.Role.Expression),
		Content:         psql.Where[Q, string](cols.Content.Expression),
		Provider:        psql.WhereNull[Q, string](cols.Provider.Expression),
		Model:           psql.WhereNull[Q, string](cols.Model.Expression),
		Status:          psql.Where[Q, string](cols.Status.Expression),
		ErrorMessage:    psql.WhereNull[Q, string](cols.ErrorMessage.Expression),
		CreatedAt:       psql.Where[Q, time.Time](cols.CreatedAt.Expression),
		NaturalResponse: psql.WhereNull[Q, string](cols.NaturalResponse.Expression),
	}
}

func (o *ChatMessage) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "MessageChatMessageExecution":
		rel, ok := retrieved.(*ChatMessageExecution)
		if !ok {
			return fmt.Errorf("chatMessage cannot load %T as %q", retrieved, name)
		}

		o.R.MessageChatMessageExecution = rel
		o.R.Loaded.MessageChatMessageExecution = true

		return nil
	case "MessageChatMessageLLMCalls":
		rels, ok := retrieved.(ChatMessageLLMCallSlice)
		if !ok {
			return fmt.Errorf("chatMessage cannot load %T as %q", retrieved, name)
		}

		o.R.MessageChatMessageLLMCalls = rels
		o.R.Loaded.MessageChatMessageLLMCalls = true

		return nil
	case "MessageChatMessageRetrieval":
		rel, ok := retrieved.(*ChatMessageRetrieval)
		if !ok {
			return fmt.Errorf("chatMessage cannot load %T as %q", retrieved, name)
		}

		o.R.MessageChatMessageRetrieval = rel
		o.R.Loaded.MessageChatMessageRetrieval = true

		return nil
	case "ConversationChatConversation":
		rel, ok := retrieved.(*ChatConversation)
		if !ok {
			return fmt.Errorf("chatMessage cannot load %T as %q", retrieved, name)
		}

		o.R.ConversationChatConversation = rel
		o.R.Loaded.ConversationChatConversation = true

		return nil
	default:
		return fmt.Errorf("chatMessage has no relationship %q", name)
	}
}

type chatMessagePreloader struct {
	MessageChatMessageExecution  func(...psql.PreloadOption) psql.Preloader
	MessageChatMessageRetrieval  func(...psql.PreloadOption) psql.Preloader
	ConversationChatConversation func(...psql.PreloadOption) psql.Preloader
}

func buildChatMessagePreloader() chatMessagePreloader {
	return chatMessagePreloader{
		MessageChatMessageExecution: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*ChatMessageExecution, ChatMessageExecutionSlice](psql.PreloadRel{
				Name: "MessageChatMessageExecution",
				Sides: []psql.PreloadSide{
					{
						From:        ChatMessages,
						To:          ChatMessageExecutions,
						FromColumns: []string{"id"},
						ToColumns:   []string{"message_id"},
					},
				},
			}, ChatMessageExecutions.Columns.Names(), opts...)
		},
		MessageChatMessageRetrieval: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*ChatMessageRetrieval, ChatMessageRetrievalSlice](psql.PreloadRel{
				Name: "MessageChatMessageRetrieval",
				Sides: []psql.PreloadSide{
					{
						From:        ChatMessages,
						To:          ChatMessageRetrievals,
						FromColumns: []string{"id"},
						ToColumns:   []string{"message_id"},
					},
				},
			}, ChatMessageRetrievals.Columns.Names(), opts...)
		},
		ConversationChatConversation: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*ChatConversation, ChatConversationSlice](psql.PreloadRel{
				Name: "ConversationChatConversation",
				Sides: []psql.PreloadSide{
					{
						From:        ChatMessages,
						To:          ChatConversations,
						FromColumns: []string{"conversation_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, ChatConversations.Columns.Names(), opts...)
		},
	}
}

type chatMessageThenLoader[Q orm.Loadable] struct {
	MessageChatMessageExecution  func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	MessageChatMessageLLMCalls   func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	MessageChatMessageRetrieval  func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	ConversationChatConversation func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildChatMessageThenLoader[Q orm.Loadable]() chatMessageThenLoader[Q] {
	type MessageChatMessageExecutionLoadInterface interface {
		LoadMessageChatMessageExecution(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type MessageChatMessageLLMCallsLoadInterface interface {
		LoadMessageChatMessageLLMCalls(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type MessageChatMessageRetrievalLoadInterface interface {
		LoadMessageChatMessageRetrieval(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type ConversationChatConversationLoadInterface interface {
		LoadConversationChatConversation(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return chatMessageThenLoader[Q]{
		MessageChatMessageExecution: thenLoadBuilder[Q](
			"MessageChatMessageExecution",
			func(ctx context.Context, exec bob.Executor, retrieved MessageChatMessageExecutionLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadMessageChatMessageExecution(ctx, exec, mods...)
			},
		),
		MessageChatMessageLLMCalls: thenLoadBuilder[Q](
			"MessageChatMessageLLMCalls",
			func(ctx context.Context, exec bob.Executor, retrieved MessageChatMessageLLMCallsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadMessageChatMessageLLMCalls(ctx, exec, mods...)
			},
		),
		MessageChatMessageRetrieval: thenLoadBuilder[Q](
			"MessageChatMessageRetrieval",
			func(ctx context.Context, exec bob.Executor, retrieved MessageChatMessageRetrievalLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadMessageChatMessageRetrieval(ctx, exec, mods...)
			},
		),
		ConversationChatConversation: thenLoadBuilder[Q](
			"ConversationChatConversation",
			func(ctx context.Context, exec bob.Executor, retrieved ConversationChatConversationLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadConversationChatConversation(ctx, exec, mods...)
			},
		),
	}
}

// LoadMessageChatMessageExecution loads the chatMessage's MessageChatMessageExecution into the .R struct
func (o *ChatMessage) LoadMessageChatMessageExecution(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.MessageChatMessageExecution = nil
	o.R.Loaded.MessageChatMessageExecution = false

	related, err := o.MessageChatMessageExecution(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R.MessageChatMessageExecution = related
	o.R.Loaded.MessageChatMessageExecution = true
	return nil
}

// LoadMessageChatMessageExecution loads the chatMessage's MessageChatMessageExecution into the .R struct
func (os ChatMessageSlice) LoadMessageChatMessageExecution(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	chatMessageExecutions, err := os.MessageChatMessageExecution(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.MessageChatMessageExecution = nil
		o.R.Loaded.MessageChatMessageExecution = true
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range chatMessageExecutions {

			if !(o.ID == rel.MessageID) {
				continue
			}

			o.R.MessageChatMessageExecution = rel
			break
		}
	}

	return nil
}

// LoadMessageChatMessageLLMCalls loads the chatMessage's MessageChatMessageLLMCalls into the .R struct
func (o *ChatMessage) LoadMessageChatMessageLLMCalls(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.MessageChatMessageLLMCalls = nil
	o.R.Loaded.MessageChatMessageLLMCalls = false

	related, err := o.MessageChatMessageLLMCalls(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	o.R.MessageChatMessageLLMCalls = related
	o.R.Loaded.MessageChatMessageLLMCalls = true
	return nil
}

// LoadMessageChatMessageLLMCalls loads the chatMessage's MessageChatMessageLLMCalls into the .R struct
func (os ChatMessageSlice) LoadMessageChatMessageLLMCalls(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	chatMessageLLMCalls, err := os.MessageChatMessageLLMCalls(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.MessageChatMessageLLMCalls = nil
		o.R.Loaded.MessageChatMessageLLMCalls = true
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range chatMessageLLMCalls {

			if !(o.ID == rel.MessageID) {
				continue
			}

			o.R.MessageChatMessageLLMCalls = append(o.R.MessageChatMessageLLMCalls, rel)
		}
	}

	return nil
}

// LoadMessageChatMessageRetrieval loads the chatMessage's MessageChatMessageRetrieval into the .R struct
func (o *ChatMessage) LoadMessageChatMessageRetrieval(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.MessageChatMessageRetrieval = nil
	o.R.Loaded.MessageChatMessageRetrieval = false

	related, err := o.MessageChatMessageRetrieval(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R.MessageChatMessageRetrieval = related
	o.R.Loaded.MessageChatMessageRetrieval = true
	return nil
}

// LoadMessageChatMessageRetrieval loads the chatMessage's MessageChatMessageRetrieval into the .R struct
func (os ChatMessageSlice) LoadMessageChatMessageRetrieval(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	chatMessageRetrievals, err := os.MessageChatMessageRetrieval(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.MessageChatMessageRetrieval = nil
		o.R.Loaded.MessageChatMessageRetrieval = true
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range chatMessageRetrievals {

			if !(o.ID == rel.MessageID) {
				continue
			}

			o.R.MessageChatMessageRetrieval = rel
			break
		}
	}

	return nil
}

// LoadConversationChatConversation loads the chatMessage's ConversationChatConversation into the .R struct
func (o *ChatMessage) LoadConversationChatConversation(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.ConversationChatConversation = nil
	o.R.Loaded.ConversationChatConversation = false

	related, err := o.ConversationChatConversation(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R.ConversationChatConversation = related
	o.R.Loaded.ConversationChatConversation = true
	return nil
}

// LoadConversationChatConversation loads the chatMessage's ConversationChatConversation into the .R struct
func (os ChatMessageSlice) LoadConversationChatConversation(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	chatConversations, err := os.ConversationChatConversation(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.ConversationChatConversation = nil
		o.R.Loaded.ConversationChatConversation = true
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range chatConversations {

			if !(o.ConversationID == rel.ID) {
				continue
			}

			o.R.ConversationChatConversation = rel
			break
		}
	}

	return nil
}

// chatMessageC is where relationship counts are stored.
type chatMessageC struct {
	MessageChatMessageLLMCalls *int64
}

// PreloadCount sets a count in the C struct by name
func (o *ChatMessage) PreloadCount(name string, count int64) error {
	if o == nil {
		return nil
	}

	switch name {
	case "MessageChatMessageLLMCalls":
		o.C.MessageChatMessageLLMCalls = &count
	}
	return nil
}

type chatMessageCountPreloader struct {
	MessageChatMessageLLMCalls func(...bob.Mod[*dialect.SelectQuery]) psql.Preloader
}

func buildChatMessageCountPreloader() chatMessageCountPreloader {
	return chatMessageCountPreloader{
		MessageChatMessageLLMCalls: func(mods ...bob.Mod[*dialect.SelectQuery]) psql.Preloader {
			return countPreloader[*ChatMessage]("MessageChatMessageLLMCalls", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = ChatMessages.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(psql.Raw("count(*)")),

					sm.From(ChatMessageLLMCalls.Name()),
					sm.Where(psql.Quote(ChatMessageLLMCalls.Alias(), "message_id").EQ(psql.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return psql.Group(psql.Select(subqueryMods...).Expression)
			})
		},
	}
}

type chatMessageCountThenLoader[Q orm.Loadable] struct {
	MessageChatMessageLLMCalls func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildChatMessageCountThenLoader[Q orm.Loadable]() chatMessageCountThenLoader[Q] {
	type MessageChatMessageLLMCallsCountInterface interface {
		LoadCountMessageChatMessageLLMCalls(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return chatMessageCountThenLoader[Q]{
		MessageChatMessageLLMCalls: countThenLoadBuilder[Q](
			"MessageChatMessageLLMCalls",
			func(ctx context.Context, exec bob.Executor, retrieved MessageChatMessageLLMCallsCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountMessageChatMessageLLMCalls(ctx, exec, mods...)
			},
		),
	}
}

// LoadCountMessageChatMessageLLMCalls loads the count of MessageChatMessageLLMCalls into the C struct
func (o *ChatMessage) LoadCountMessageChatMessageLLMCalls(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.MessageChatMessageLLMCalls(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.MessageChatMessageLLMCalls = &count
	return nil
}

// LoadCountMessageChatMessageLLMCalls loads the count of MessageChatMessageLLMCalls for a slice in a single batch query
func (os ChatMessageSlice) LoadCountMessageChatMessageLLMCalls(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// Build the IN arg expression from parent PKs

	pkID := make(pgtypes.Array[int64], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "bigint[]")),
	))

	// countResult holds one scanned row from the batch count query.
	// FK columns are aliased to the parent PK column names for direct map lookup.
	type countResult struct {
		ID    int64
		Count int64
	}

	batchMods := []bob.Mod[*dialect.SelectQuery]{
		// SELECT fk AS parent_pk, count(*)
		sm.Columns(
			ChatMessageLLMCalls.Columns.MessageID.As("id"),
			psql.Raw("count(*) as count"),
		),
		// Single-hop: FROM related table directly
		sm.From(ChatMessageLLMCalls.NameAs()),

		// WHERE fk IN (parent PKs)
		sm.Where(ChatMessageLLMCalls.Columns.MessageID.OP("IN", PKArgExpr)),
		// GROUP BY fk columns
		sm.GroupBy(ChatMessageLLMCalls.Columns.MessageID),
	}
	batchMods = append(batchMods, mods...)

	results, err := bob.All(ctx, exec,
		psql.Select(batchMods...),
		scan.StructMapper[countResult](),
	)
	if err != nil {
		return err
	}

	// Single-column FK: direct map lookup
	countMap := make(map[int64]int64, len(results))
	for _, r := range results {
		countMap[r.ID] = r.Count
	}
	for _, o := range os {
		if o == nil {
			continue
		}
		count := countMap[o.ID]
		o.C.MessageChatMessageLLMCalls = &count
	}

	return nil
}

type chatMessageJoins[Q dialect.Joinable] struct {
	typ                          string
	MessageChatMessageExecution  modAs[Q, chatMessageExecutionColumns]
	MessageChatMessageLLMCalls   modAs[Q, chatMessageLLMCallColumns]
	MessageChatMessageRetrieval  modAs[Q, chatMessageRetrievalColumns]
	ConversationChatConversation modAs[Q, chatConversationColumns]
}

func (j chatMessageJoins[Q]) aliasedAs(alias string) chatMessageJoins[Q] {
	return buildChatMessageJoins[Q](buildChatMessageColumns(alias), j.typ)
}

func buildChatMessageJoins[Q dialect.Joinable](cols chatMessageColumns, typ string) chatMessageJoins[Q] {
	return chatMessageJoins[Q]{
		typ: typ,
		MessageChatMessageExecution: modAs[Q, chatMessageExecutionColumns]{
			c: ChatMessageExecutions.Columns,
			f: func(to chatMessageExecutionColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, ChatMessageExecutions.Name().As(to.Alias())).On(
						to.MessageID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		MessageChatMessageLLMCalls: modAs[Q, chatMessageLLMCallColumns]{
			c: ChatMessageLLMCalls.Columns,
			f: func(to chatMessageLLMCallColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, ChatMessageLLMCalls.Name().As(to.Alias())).On(
						to.MessageID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		MessageChatMessageRetrieval: modAs[Q, chatMessageRetrievalColumns]{
			c: ChatMessageRetrievals.Columns,
			f: func(to chatMessageRetrievalColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, ChatMessageRetrievals.Name().As(to.Alias())).On(
						to.MessageID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		ConversationChatConversation: modAs[Q, chatConversationColumns]{
			c: ChatConversations.Columns,
			f: func(to chatConversationColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, ChatConversations.Name().As(to.Alias())).On(
						to.ID.EQ(cols.ConversationID),
					))
				}

				return mods
			},
		},
	}
}
