// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"

	"github.com/aarondl/opt/omit"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/sqlite"
	"github.com/stephenafamo/bob/dialect/sqlite/dialect"
	"github.com/stephenafamo/bob/dialect/sqlite/dm"
	"github.com/stephenafamo/bob/dialect/sqlite/sm"
	"github.com/stephenafamo/bob/dialect/sqlite/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
)

// ConnectionAccess is an object representing the database table.
type ConnectionAccess struct {
	UserID       int64  `db:"user_id,pk" `
	ConnectionID int64  `db:"connection_id,pk" `
	CanQuery     int64  `db:"can_query" `
	AllowWrites  int64  `db:"allow_writes" `
	CanManage    int64  `db:"can_manage" `
	GrantedAt    string `db:"granted_at" `

	R connectionAccessR `db:"-" `
}

// ConnectionAccessSlice is an alias for a slice of pointers to ConnectionAccess.
// This should almost always be used instead of []*ConnectionAccess.
type ConnectionAccessSlice []*ConnectionAccess

// ConnectionAccesses contains methods to work with the connection_access table
var ConnectionAccesses = sqlite.NewTablex[*ConnectionAccess, ConnectionAccessSlice, *ConnectionAccessSetter]("", "connection_access", buildConnectionAccessColumns("connection_access"))

// ConnectionAccessesQuery is a query on the connection_access table
type ConnectionAccessesQuery = *sqlite.ViewQuery[*ConnectionAccess, ConnectionAccessSlice]

// connectionAccessR is where relationships are stored.
type connectionAccessR struct {
	Connection *Connection // fk_connection_access_0
	User       *User       // fk_connection_access_1
}

func buildConnectionAccessColumns(alias string) connectionAccessColumns {
	return connectionAccessColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"user_id", "connection_id", "can_query", "allow_writes", "can_manage", "granted_at",
		).WithParent("connection_access"),
		tableAlias:   alias,
		UserID:       sqlite.Quote(alias, "user_id"),
		ConnectionID: sqlite.Quote(alias, "connection_id"),
		CanQuery:     sqlite.Quote(alias, "can_query"),
		AllowWrites:  sqlite.Quote(alias, "allow_writes"),
		CanManage:    sqlite.Quote(alias, "can_manage"),
		GrantedAt:    sqlite.Quote(alias, "granted_at"),
	}
}

type connectionAccessColumns struct {
	expr.ColumnsExpr
	tableAlias   string
	UserID       sqlite.Expression
	ConnectionID sqlite.Expression
	CanQuery     sqlite.Expression
	AllowWrites  sqlite.Expression
	CanManage    sqlite.Expression
	GrantedAt    sqlite.Expression
}

func (c connectionAccessColumns) Alias() string {
	return c.tableAlias
}

func (connectionAccessColumns) AliasedAs(alias string) connectionAccessColumns {
	return buildConnectionAccessColumns(alias)
}

// ConnectionAccessSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type ConnectionAccessSetter struct {
	UserID       omit.Val[int64]  `db:"user_id,pk" `
	ConnectionID omit.Val[int64]  `db:"connection_id,pk" `
	CanQuery     omit.Val[int64]  `db:"can_query" `
	AllowWrites  omit.Val[int64]  `db:"allow_writes" `
	CanManage    omit.Val[int64]  `db:"can_manage" `
	GrantedAt    omit.Val[string] `db:"granted_at" `
}

func (s ConnectionAccessSetter) SetColumns() []string {
	vals := make([]string, 0, 6)
	if s.UserID.IsValue() {
		vals = append(vals, "user_id")
	}
	if s.ConnectionID.IsValue() {
		vals = append(vals, "connection_id")
	}
	if s.CanQuery.IsValue() {
		vals = append(vals, "can_query")
	}
	if s.AllowWrites.IsValue() {
		vals = append(vals, "allow_writes")
	}
	if s.CanManage.IsValue() {
		vals = append(vals, "can_manage")
	}
	if s.GrantedAt.IsValue() {
		vals = append(vals, "granted_at")
	}
	return vals
}

func (s ConnectionAccessSetter) Overwrite(t *ConnectionAccess) {
	if s.UserID.IsValue() {
		t.UserID = s.UserID.MustGet()
	}
	if s.ConnectionID.IsValue() {
		t.ConnectionID = s.ConnectionID.MustGet()
	}
	if s.CanQuery.IsValue() {
		t.CanQuery = s.CanQuery.MustGet()
	}
	if s.AllowWrites.IsValue() {
		t.AllowWrites = s.AllowWrites.MustGet()
	}
	if s.CanManage.IsValue() {
		t.CanManage = s.CanManage.MustGet()
	}
	if s.GrantedAt.IsValue() {
		t.GrantedAt = s.GrantedAt.MustGet()
	}
}

func (s *ConnectionAccessSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return ConnectionAccesses.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	if len(q.TableRef.Columns) == 0 {
		q.TableRef.Columns = s.SetColumns()
		if len(q.TableRef.Columns) == 0 {
			q.TableRef.Columns = []string{"user_id", "connection_id"}
		}

	}

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 0, 6)
		if s.UserID.IsValue() {
			vals = append(vals, sqlite.Arg(s.UserID.MustGet()))
		}

		if s.ConnectionID.IsValue() {
			vals = append(vals, sqlite.Arg(s.ConnectionID.MustGet()))
		}

		if s.CanQuery.IsValue() {
			vals = append(vals, sqlite.Arg(s.CanQuery.MustGet()))
		}

		if s.AllowWrites.IsValue() {
			vals = append(vals, sqlite.Arg(s.AllowWrites.MustGet()))
		}

		if s.CanManage.IsValue() {
			vals = append(vals, sqlite.Arg(s.CanManage.MustGet()))
		}

		if s.GrantedAt.IsValue() {
			vals = append(vals, sqlite.Arg(s.GrantedAt.MustGet()))
		}

		if len(vals) == 0 {
			vals = append(vals, sqlite.Arg(nil), sqlite.Arg(nil))
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s ConnectionAccessSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s ConnectionAccessSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 6)

	if s.UserID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "user_id")...),
			sqlite.Arg(s.UserID),
		}})
	}

	if s.ConnectionID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "connection_id")...),
			sqlite.Arg(s.ConnectionID),
		}})
	}

	if s.CanQuery.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "can_query")...),
			sqlite.Arg(s.CanQuery),
		}})
	}

	if s.AllowWrites.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "allow_writes")...),
			sqlite.Arg(s.AllowWrites),
		}})
	}

	if s.CanManage.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "can_manage")...),
			sqlite.Arg(s.CanManage),
		}})
	}

	if s.GrantedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			sqlite.Quote(append(prefix, "granted_at")...),
			sqlite.Arg(s.GrantedAt),
		}})
	}

	return exprs
}

// FindConnectionAccess retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindConnectionAccess(ctx context.Context, exec bob.Executor, UserIDPK int64, ConnectionIDPK int64, cols ...string) (*ConnectionAccess, error) {
	if len(cols) == 0 {
		return ConnectionAccesses.Query(
			sm.Where(ConnectionAccesses.Columns.UserID.EQ(sqlite.Arg(UserIDPK))),
			sm.Where(ConnectionAccesses.Columns.ConnectionID.EQ(sqlite.Arg(ConnectionIDPK))),
		).One(ctx, exec)
	}

	return ConnectionAccesses.Query(
		sm.Where(ConnectionAccesses.Columns.UserID.EQ(sqlite.Arg(UserIDPK))),
		sm.Where(ConnectionAccesses.Columns.ConnectionID.EQ(sqlite.Arg(ConnectionIDPK))),
		sm.Columns(ConnectionAccesses.Columns.Only(cols...)),
	).One(ctx, exec)
}

// ConnectionAccessExists checks the presence of a single record by primary key
func ConnectionAccessExists(ctx context.Context, exec bob.Executor, UserIDPK int64, ConnectionIDPK int64) (bool, error) {
	return ConnectionAccesses.Query(
		sm.Where(ConnectionAccesses.Columns.UserID.EQ(sqlite.Arg(UserIDPK))),
		sm.Where(ConnectionAccesses.Columns.ConnectionID.EQ(sqlite.Arg(ConnectionIDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after ConnectionAccess is retrieved from the database
func (o *ConnectionAccess) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = ConnectionAccesses.AfterSelectHooks.RunHooks(ctx, exec, ConnectionAccessSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = ConnectionAccesses.AfterInsertHooks.RunHooks(ctx, exec, ConnectionAccessSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = ConnectionAccesses.AfterUpdateHooks.RunHooks(ctx, exec, ConnectionAccessSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = ConnectionAccesses.AfterDeleteHooks.RunHooks(ctx, exec, ConnectionAccessSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the ConnectionAccess
func (o *ConnectionAccess) primaryKeyVals() bob.Expression {
	return sqlite.ArgGroup(
		o.UserID,
		o.ConnectionID,
	)
}

func (o *ConnectionAccess) pkEQ() dialect.Expression {
	return sqlite.Group(sqlite.Quote("connection_access", "user_id"), sqlite.Quote("connection_access", "connection_id")).EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the ConnectionAccess
func (o *ConnectionAccess) Update(ctx context.Context, exec bob.Executor, s *ConnectionAccessSetter) error {
	v, err := ConnectionAccesses.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single ConnectionAccess record with an executor
func (o *ConnectionAccess) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := ConnectionAccesses.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the ConnectionAccess using the executor
func (o *ConnectionAccess) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := ConnectionAccesses.Query(
		sm.Where(ConnectionAccesses.Columns.UserID.EQ(sqlite.Arg(o.UserID))),
		sm.Where(ConnectionAccesses.Columns.ConnectionID.EQ(sqlite.Arg(o.ConnectionID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after ConnectionAccessSlice is retrieved from the database
func (o ConnectionAccessSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = ConnectionAccesses.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = ConnectionAccesses.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = ConnectionAccesses.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = ConnectionAccesses.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o ConnectionAccessSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return sqlite.Raw("NULL")
	}

	return sqlite.Group(sqlite.Quote("connection_access", "user_id"), sqlite.Quote("connection_access", "connection_id")).In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o ConnectionAccessSlice) copyMatchingRows(from ...*ConnectionAccess) {
	for i, old := range o {
		for _, new := range from {
			if new.UserID != old.UserID {
				continue
			}
			if new.ConnectionID != old.ConnectionID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o ConnectionAccessSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return ConnectionAccesses.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *ConnectionAccess:
				o.copyMatchingRows(retrieved)
			case []*ConnectionAccess:
				o.copyMatchingRows(retrieved...)
			case ConnectionAccessSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a ConnectionAccess or a slice of ConnectionAccess
				// then run the AfterUpdateHooks on the slice
				_, err = ConnectionAccesses.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o ConnectionAccessSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return ConnectionAccesses.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *ConnectionAccess:
				o.copyMatchingRows(retrieved)
			case []*ConnectionAccess:
				o.copyMatchingRows(retrieved...)
			case ConnectionAccessSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a ConnectionAccess or a slice of ConnectionAccess
				// then run the AfterDeleteHooks on the slice
				_, err = ConnectionAccesses.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o ConnectionAccessSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals ConnectionAccessSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := ConnectionAccesses.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o ConnectionAccessSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := ConnectionAccesses.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o ConnectionAccessSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := ConnectionAccesses.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Connection starts a query for related objects on connections
func (o *ConnectionAccess) Connection(mods ...bob.Mod[*dialect.SelectQuery]) ConnectionsQuery {
	return Connections.Query(append(mods,
		sm.Where(Connections.Columns.ID.EQ(sqlite.Arg(o.ConnectionID))),
	)...)
}

func (os ConnectionAccessSlice) Connection(mods ...bob.Mod[*dialect.SelectQuery]) ConnectionsQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = sqlite.ArgGroup(o.ConnectionID)
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	return Connections.Query(append(mods,
		sm.Where(sqlite.Group(Connections.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// User starts a query for related objects on users
func (o *ConnectionAccess) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(sqlite.Arg(o.UserID))),
	)...)
}

func (os ConnectionAccessSlice) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = sqlite.ArgGroup(o.UserID)
	}
	PKArgExpr := sqlite.Group(PKArgSlice...)

	return Users.Query(append(mods,
		sm.Where(sqlite.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachConnectionAccessConnection0(ctx context.Context, exec bob.Executor, count int, connectionAccess0 *ConnectionAccess, connection1 *Connection) (*ConnectionAccess, error) {
	setter := &ConnectionAccessSetter{
		ConnectionID: omit.From(connection1.ID),
	}

	err := connectionAccess0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachConnectionAccessConnection0: %w", err)
	}

	return connectionAccess0, nil
}

func (connectionAccess0 *ConnectionAccess) InsertConnection(ctx context.Context, exec bob.Executor, related *ConnectionSetter) error {
	var err error

	connection1, err := Connections.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachConnectionAccessConnection0(ctx, exec, 1, connectionAccess0, connection1)
	if err != nil {
		return err
	}

	connectionAccess0.R.Connection = connection1

	return nil
}

func (connectionAccess0 *ConnectionAccess) AttachConnection(ctx context.Context, exec bob.Executor, connection1 *Connection) error {
	var err error

	_, err = attachConnectionAccessConnection0(ctx, exec, 1, connectionAccess0, connection1)
	if err != nil {
		return err
	}

	connectionAccess0.R.Connection = connection1

	return nil
}

func attachConnectionAccessUser0(ctx context.Context, exec bob.Executor, count int, connectionAccess0 *ConnectionAccess, user1 *User) (*ConnectionAccess, error) {
	setter := &ConnectionAccessSetter{
		UserID: omit.From(user1.ID),
	}

	err := connectionAccess0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachConnectionAccessUser0: %w", err)
	}

	return connectionAccess0, nil
}

func (connectionAccess0 *ConnectionAccess) InsertUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	var err error

	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachConnectionAccessUser0(ctx, exec, 1, connectionAccess0, user1)
	if err != nil {
		return err
	}

	connectionAccess0.R.User = user1

	return nil
}

func (connectionAccess0 *ConnectionAccess) AttachUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachConnectionAccessUser0(ctx, exec, 1, connectionAccess0, user1)
	if err != nil {
		return err
	}

	connectionAccess0.R.User = user1

	return nil
}

type connectionAccessWhere[Q sqlite.Filterable] struct {
	UserID       sqlite.WhereMod[Q, int64]
	ConnectionID sqlite.WhereMod[Q, int64]
	CanQuery     sqlite.WhereMod[Q, int64]
	AllowWrites  sqlite.WhereMod[Q, int64]
	CanManage    sqlite.WhereMod[Q, int64]
	GrantedAt    sqlite.WhereMod[Q, string]
}

func (connectionAccessWhere[Q]) AliasedAs(alias string) connectionAccessWhere[Q] {
	return buildConnectionAccessWhere[Q](buildConnectionAccessColumns(alias))
}

func buildConnectionAccessWhere[Q sqlite.Filterable](cols connectionAccessColumns) connectionAccessWhere[Q] {
	return connectionAccessWhere[Q]{
		UserID:       sqlite.Where[Q, int64](cols.UserID),
		ConnectionID: sqlite.Where[Q, int64](cols.ConnectionID),
		CanQuery:     sqlite.Where[Q, int64](cols.CanQuery),
		AllowWrites:  sqlite.Where[Q, int64](cols.AllowWrites),
		CanManage:    sqlite.Where[Q, int64](cols.CanManage),
		GrantedAt:    sqlite.Where[Q, string](cols.GrantedAt),
	}
}

func (o *ConnectionAccess) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Connection":
		rel, ok := retrieved.(*Connection)
		if !ok {
			return fmt.Errorf("connectionAccess cannot load %T as %q", retrieved, name)
		}

		o.R.Connection = rel

		return nil
	case "User":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("connectionAccess cannot load %T as %q", retrieved, name)
		}

		o.R.User = rel

		return nil
	default:
		return fmt.Errorf("connectionAccess has no relationship %q", name)
	}
}

type connectionAccessPreloader struct {
	Connection func(...sqlite.PreloadOption) sqlite.Preloader
	User       func(...sqlite.PreloadOption) sqlite.Preloader
}

func buildConnectionAccessPreloader() connectionAccessPreloader {
	return connectionAccessPreloader{
		Connection: func(opts ...sqlite.PreloadOption) sqlite.Preloader {
			return sqlite.Preload[*Connection, ConnectionSlice](sqlite.PreloadRel{
				Name: "Connection",
				Sides: []sqlite.PreloadSide{
					{
						From:        ConnectionAccesses,
						To:          Connections,
						FromColumns: []string{"connection_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Connections.Columns.Names(), opts...)
		},
		User: func(opts ...sqlite.PreloadOption) sqlite.Preloader {
			return sqlite.Preload[*User, UserSlice](sqlite.PreloadRel{
				Name: "User",
				Sides: []sqlite.PreloadSide{
					{
						From:        ConnectionAccesses,
						To:          Users,
						FromColumns: []string{"user_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
	}
}

type connectionAccessThenLoader[Q orm.Loadable] struct {
	Connection func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	User       func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildConnectionAccessThenLoader[Q orm.Loadable]() connectionAccessThenLoader[Q] {
	type ConnectionLoadInterface interface {
		LoadConnection(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type UserLoadInterface interface {
		LoadUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return connectionAccessThenLoader[Q]{
		Connection: thenLoadBuilder[Q](
			"Connection",
			func(ctx context.Context, exec bob.Executor, retrieved ConnectionLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadConnection(ctx, exec, mods...)
			},
		),
		User: thenLoadBuilder[Q](
			"User",
			func(ctx context.Context, exec bob.Executor, retrieved UserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUser(ctx, exec, mods...)
			},
		),
	}
}

// LoadConnection loads the connectionAccess's Connection into the .R struct
func (o *ConnectionAccess) LoadConnection(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Connection = nil

	related, err := o.Connection(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R.Connection = related
	return nil
}

// LoadConnection loads the connectionAccess's Connection into the .R struct
func (os ConnectionAccessSlice) LoadConnection(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	connections, err := os.Connection(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range connections {

			if !(o.ConnectionID == rel.ID) {
				continue
			}

			o.R.Connection = rel
			break
		}
	}

	return nil
}

// LoadUser loads the connectionAccess's User into the .R struct
func (o *ConnectionAccess) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.User = nil

	related, err := o.User(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R.User = related
	return nil
}

// LoadUser loads the connectionAccess's User into the .R struct
func (os ConnectionAccessSlice) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.User(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {

			if !(o.UserID == rel.ID) {
				continue
			}

			o.R.User = rel
			break
		}
	}

	return nil
}

type connectionAccessJoins[Q dialect.Joinable] struct {
	typ        string
	Connection modAs[Q, connectionColumns]
	User       modAs[Q, userColumns]
}

func (j connectionAccessJoins[Q]) aliasedAs(alias string) connectionAccessJoins[Q] {
	return buildConnectionAccessJoins[Q](buildConnectionAccessColumns(alias), j.typ)
}

func buildConnectionAccessJoins[Q dialect.Joinable](cols connectionAccessColumns, typ string) connectionAccessJoins[Q] {
	return connectionAccessJoins[Q]{
		typ: typ,
		Connection: modAs[Q, connectionColumns]{
			c: Connections.Columns,
			f: func(to connectionColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Connections.Name().As(to.Alias())).On(
						to.ID.EQ(cols.ConnectionID),
					))
				}

				return mods
			},
		},
		User: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.UserID),
					))
				}

				return mods
			},
		},
	}
}
