// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// LLMProviderModel is an object representing the database table.
type LLMProviderModel struct {
	ID               int64           `db:"id,pk" `
	ProviderConfigID int64           `db:"provider_config_id" `
	Model            string          `db:"model" `
	DisplayName      string          `db:"display_name" `
	ContextWindow    null.Val[int32] `db:"context_window" `
	SupportsSQL      bool            `db:"supports_sql" `
	IsEnabled        bool            `db:"is_enabled" `
	DiscoveredAt     time.Time       `db:"discovered_at" `

	R llmProviderModelR `db:"-" `
}

// LLMProviderModelSlice is an alias for a slice of pointers to LLMProviderModel.
// This should almost always be used instead of []*LLMProviderModel.
type LLMProviderModelSlice []*LLMProviderModel

// LLMProviderModels contains methods to work with the llm_provider_models table
var LLMProviderModels = psql.NewTablex[*LLMProviderModel, LLMProviderModelSlice, *LLMProviderModelSetter]("", "llm_provider_models", buildLLMProviderModelColumns("llm_provider_models"))

// LLMProviderModelsQuery is a query on the llm_provider_models table
type LLMProviderModelsQuery = *psql.ViewQuery[*LLMProviderModel, LLMProviderModelSlice]

// llmProviderModelR is where relationships are stored.
type llmProviderModelR struct {
	ProviderConfigLLMProviderConfig *LLMProviderConfig // llm_provider_models.llm_provider_models_provider_config_id_fkey
}

func buildLLMProviderModelColumns(alias string) llmProviderModelColumns {
	return llmProviderModelColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "provider_config_id", "model", "display_name", "context_window", "supports_sql", "is_enabled", "discovered_at",
		).WithParent("llm_provider_models"),
		tableAlias:       alias,
		ID:               psql.Quote(alias, "id"),
		ProviderConfigID: psql.Quote(alias, "provider_config_id"),
		Model:            psql.Quote(alias, "model"),
		DisplayName:      psql.Quote(alias, "display_name"),
		ContextWindow:    psql.Quote(alias, "context_window"),
		SupportsSQL:      psql.Quote(alias, "supports_sql"),
		IsEnabled:        psql.Quote(alias, "is_enabled"),
		DiscoveredAt:     psql.Quote(alias, "discovered_at"),
	}
}

type llmProviderModelColumns struct {
	expr.ColumnsExpr
	tableAlias       string
	ID               psql.Expression
	ProviderConfigID psql.Expression
	Model            psql.Expression
	DisplayName      psql.Expression
	ContextWindow    psql.Expression
	SupportsSQL      psql.Expression
	IsEnabled        psql.Expression
	DiscoveredAt     psql.Expression
}

func (c llmProviderModelColumns) Alias() string {
	return c.tableAlias
}

func (llmProviderModelColumns) AliasedAs(alias string) llmProviderModelColumns {
	return buildLLMProviderModelColumns(alias)
}

// LLMProviderModelSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type LLMProviderModelSetter struct {
	ID               omit.Val[int64]     `db:"id,pk" `
	ProviderConfigID omit.Val[int64]     `db:"provider_config_id" `
	Model            omit.Val[string]    `db:"model" `
	DisplayName      omit.Val[string]    `db:"display_name" `
	ContextWindow    omitnull.Val[int32] `db:"context_window" `
	SupportsSQL      omit.Val[bool]      `db:"supports_sql" `
	IsEnabled        omit.Val[bool]      `db:"is_enabled" `
	DiscoveredAt     omit.Val[time.Time] `db:"discovered_at" `
}

func (s LLMProviderModelSetter) SetColumns() []string {
	vals := make([]string, 0, 8)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.ProviderConfigID.IsValue() {
		vals = append(vals, "provider_config_id")
	}
	if s.Model.IsValue() {
		vals = append(vals, "model")
	}
	if s.DisplayName.IsValue() {
		vals = append(vals, "display_name")
	}
	if !s.ContextWindow.IsUnset() {
		vals = append(vals, "context_window")
	}
	if s.SupportsSQL.IsValue() {
		vals = append(vals, "supports_sql")
	}
	if s.IsEnabled.IsValue() {
		vals = append(vals, "is_enabled")
	}
	if s.DiscoveredAt.IsValue() {
		vals = append(vals, "discovered_at")
	}
	return vals
}

func (s LLMProviderModelSetter) Overwrite(t *LLMProviderModel) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.ProviderConfigID.IsValue() {
		t.ProviderConfigID = s.ProviderConfigID.MustGet()
	}
	if s.Model.IsValue() {
		t.Model = s.Model.MustGet()
	}
	if s.DisplayName.IsValue() {
		t.DisplayName = s.DisplayName.MustGet()
	}
	if !s.ContextWindow.IsUnset() {
		t.ContextWindow = s.ContextWindow.MustGetNull()
	}
	if s.SupportsSQL.IsValue() {
		t.SupportsSQL = s.SupportsSQL.MustGet()
	}
	if s.IsEnabled.IsValue() {
		t.IsEnabled = s.IsEnabled.MustGet()
	}
	if s.DiscoveredAt.IsValue() {
		t.DiscoveredAt = s.DiscoveredAt.MustGet()
	}
}

func (s *LLMProviderModelSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return LLMProviderModels.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 8)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.ProviderConfigID.IsValue() {
			vals[1] = psql.Arg(s.ProviderConfigID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Model.IsValue() {
			vals[2] = psql.Arg(s.Model.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.DisplayName.IsValue() {
			vals[3] = psql.Arg(s.DisplayName.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if !s.ContextWindow.IsUnset() {
			vals[4] = psql.Arg(s.ContextWindow.MustGetNull())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.SupportsSQL.IsValue() {
			vals[5] = psql.Arg(s.SupportsSQL.MustGet())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.IsEnabled.IsValue() {
			vals[6] = psql.Arg(s.IsEnabled.MustGet())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if s.DiscoveredAt.IsValue() {
			vals[7] = psql.Arg(s.DiscoveredAt.MustGet())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s LLMProviderModelSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s LLMProviderModelSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 8)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.ProviderConfigID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "provider_config_id")...),
			psql.Arg(s.ProviderConfigID),
		}})
	}

	if s.Model.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "model")...),
			psql.Arg(s.Model),
		}})
	}

	if s.DisplayName.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "display_name")...),
			psql.Arg(s.DisplayName),
		}})
	}

	if !s.ContextWindow.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "context_window")...),
			psql.Arg(s.ContextWindow),
		}})
	}

	if s.SupportsSQL.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "supports_sql")...),
			psql.Arg(s.SupportsSQL),
		}})
	}

	if s.IsEnabled.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "is_enabled")...),
			psql.Arg(s.IsEnabled),
		}})
	}

	if s.DiscoveredAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "discovered_at")...),
			psql.Arg(s.DiscoveredAt),
		}})
	}

	return exprs
}

// FindLLMProviderModel retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindLLMProviderModel(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*LLMProviderModel, error) {
	if len(cols) == 0 {
		return LLMProviderModels.Query(
			sm.Where(LLMProviderModels.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return LLMProviderModels.Query(
		sm.Where(LLMProviderModels.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(LLMProviderModels.Columns.Only(cols...)),
	).One(ctx, exec)
}

// LLMProviderModelExists checks the presence of a single record by primary key
func LLMProviderModelExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return LLMProviderModels.Query(
		sm.Where(LLMProviderModels.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after LLMProviderModel is retrieved from the database
func (o *LLMProviderModel) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = LLMProviderModels.AfterSelectHooks.RunHooks(ctx, exec, LLMProviderModelSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = LLMProviderModels.AfterInsertHooks.RunHooks(ctx, exec, LLMProviderModelSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = LLMProviderModels.AfterUpdateHooks.RunHooks(ctx, exec, LLMProviderModelSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = LLMProviderModels.AfterDeleteHooks.RunHooks(ctx, exec, LLMProviderModelSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the LLMProviderModel
func (o *LLMProviderModel) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *LLMProviderModel) pkEQ() dialect.Expression {
	return psql.Quote("llm_provider_models", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the LLMProviderModel
func (o *LLMProviderModel) Update(ctx context.Context, exec bob.Executor, s *LLMProviderModelSetter) error {
	v, err := LLMProviderModels.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single LLMProviderModel record with an executor
func (o *LLMProviderModel) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := LLMProviderModels.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the LLMProviderModel using the executor
func (o *LLMProviderModel) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := LLMProviderModels.Query(
		sm.Where(LLMProviderModels.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after LLMProviderModelSlice is retrieved from the database
func (o LLMProviderModelSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = LLMProviderModels.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = LLMProviderModels.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = LLMProviderModels.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = LLMProviderModels.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o LLMProviderModelSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("llm_provider_models", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o LLMProviderModelSlice) copyMatchingRows(from ...*LLMProviderModel) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o LLMProviderModelSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return LLMProviderModels.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *LLMProviderModel:
				o.copyMatchingRows(retrieved)
			case []*LLMProviderModel:
				o.copyMatchingRows(retrieved...)
			case LLMProviderModelSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a LLMProviderModel or a slice of LLMProviderModel
				// then run the AfterUpdateHooks on the slice
				_, err = LLMProviderModels.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o LLMProviderModelSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return LLMProviderModels.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *LLMProviderModel:
				o.copyMatchingRows(retrieved)
			case []*LLMProviderModel:
				o.copyMatchingRows(retrieved...)
			case LLMProviderModelSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a LLMProviderModel or a slice of LLMProviderModel
				// then run the AfterDeleteHooks on the slice
				_, err = LLMProviderModels.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o LLMProviderModelSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals LLMProviderModelSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := LLMProviderModels.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o LLMProviderModelSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := LLMProviderModels.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o LLMProviderModelSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := LLMProviderModels.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// ProviderConfigLLMProviderConfig starts a query for related objects on llm_provider_configs
func (o *LLMProviderModel) ProviderConfigLLMProviderConfig(mods ...bob.Mod[*dialect.SelectQuery]) LLMProviderConfigsQuery {
	return LLMProviderConfigs.Query(append(mods,
		sm.Where(LLMProviderConfigs.Columns.ID.EQ(psql.Arg(o.ProviderConfigID))),
	)...)
}

func (os LLMProviderModelSlice) ProviderConfigLLMProviderConfig(mods ...bob.Mod[*dialect.SelectQuery]) LLMProviderConfigsQuery {
	pkProviderConfigID := make(pgtypes.Array[int64], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkProviderConfigID = append(pkProviderConfigID, o.ProviderConfigID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkProviderConfigID), "bigint[]")),
	))

	return LLMProviderConfigs.Query(append(mods,
		sm.Where(psql.Group(LLMProviderConfigs.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachLLMProviderModelProviderConfigLLMProviderConfig0(ctx context.Context, exec bob.Executor, count int, llmProviderModel0 *LLMProviderModel, llmProviderConfig1 *LLMProviderConfig) (*LLMProviderModel, error) {
	setter := &LLMProviderModelSetter{
		ProviderConfigID: omit.From(llmProviderConfig1.ID),
	}

	err := llmProviderModel0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachLLMProviderModelProviderConfigLLMProviderConfig0: %w", err)
	}

	return llmProviderModel0, nil
}

func (llmProviderModel0 *LLMProviderModel) InsertProviderConfigLLMProviderConfig(ctx context.Context, exec bob.Executor, related *LLMProviderConfigSetter) error {
	var err error

	llmProviderConfig1, err := LLMProviderConfigs.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachLLMProviderModelProviderConfigLLMProviderConfig0(ctx, exec, 1, llmProviderModel0, llmProviderConfig1)
	if err != nil {
		return err
	}

	llmProviderModel0.R.ProviderConfigLLMProviderConfig = llmProviderConfig1

	return nil
}

func (llmProviderModel0 *LLMProviderModel) AttachProviderConfigLLMProviderConfig(ctx context.Context, exec bob.Executor, llmProviderConfig1 *LLMProviderConfig) error {
	var err error

	_, err = attachLLMProviderModelProviderConfigLLMProviderConfig0(ctx, exec, 1, llmProviderModel0, llmProviderConfig1)
	if err != nil {
		return err
	}

	llmProviderModel0.R.ProviderConfigLLMProviderConfig = llmProviderConfig1

	return nil
}

type llmProviderModelWhere[Q psql.Filterable] struct {
	ID               psql.WhereMod[Q, int64]
	ProviderConfigID psql.WhereMod[Q, int64]
	Model            psql.WhereMod[Q, string]
	DisplayName      psql.WhereMod[Q, string]
	ContextWindow    psql.WhereNullMod[Q, int32]
	SupportsSQL      psql.WhereMod[Q, bool]
	IsEnabled        psql.WhereMod[Q, bool]
	DiscoveredAt     psql.WhereMod[Q, time.Time]
}

func (llmProviderModelWhere[Q]) AliasedAs(alias string) llmProviderModelWhere[Q] {
	return buildLLMProviderModelWhere[Q](buildLLMProviderModelColumns(alias))
}

func buildLLMProviderModelWhere[Q psql.Filterable](cols llmProviderModelColumns) llmProviderModelWhere[Q] {
	return llmProviderModelWhere[Q]{
		ID:               psql.Where[Q, int64](cols.ID),
		ProviderConfigID: psql.Where[Q, int64](cols.ProviderConfigID),
		Model:            psql.Where[Q, string](cols.Model),
		DisplayName:      psql.Where[Q, string](cols.DisplayName),
		ContextWindow:    psql.WhereNull[Q, int32](cols.ContextWindow),
		SupportsSQL:      psql.Where[Q, bool](cols.SupportsSQL),
		IsEnabled:        psql.Where[Q, bool](cols.IsEnabled),
		DiscoveredAt:     psql.Where[Q, time.Time](cols.DiscoveredAt),
	}
}

func (o *LLMProviderModel) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "ProviderConfigLLMProviderConfig":
		rel, ok := retrieved.(*LLMProviderConfig)
		if !ok {
			return fmt.Errorf("llmProviderModel cannot load %T as %q", retrieved, name)
		}

		o.R.ProviderConfigLLMProviderConfig = rel

		return nil
	default:
		return fmt.Errorf("llmProviderModel has no relationship %q", name)
	}
}

type llmProviderModelPreloader struct {
	ProviderConfigLLMProviderConfig func(...psql.PreloadOption) psql.Preloader
}

func buildLLMProviderModelPreloader() llmProviderModelPreloader {
	return llmProviderModelPreloader{
		ProviderConfigLLMProviderConfig: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*LLMProviderConfig, LLMProviderConfigSlice](psql.PreloadRel{
				Name: "ProviderConfigLLMProviderConfig",
				Sides: []psql.PreloadSide{
					{
						From:        LLMProviderModels,
						To:          LLMProviderConfigs,
						FromColumns: []string{"provider_config_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, LLMProviderConfigs.Columns.Names(), opts...)
		},
	}
}

type llmProviderModelThenLoader[Q orm.Loadable] struct {
	ProviderConfigLLMProviderConfig func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildLLMProviderModelThenLoader[Q orm.Loadable]() llmProviderModelThenLoader[Q] {
	type ProviderConfigLLMProviderConfigLoadInterface interface {
		LoadProviderConfigLLMProviderConfig(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return llmProviderModelThenLoader[Q]{
		ProviderConfigLLMProviderConfig: thenLoadBuilder[Q](
			"ProviderConfigLLMProviderConfig",
			func(ctx context.Context, exec bob.Executor, retrieved ProviderConfigLLMProviderConfigLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadProviderConfigLLMProviderConfig(ctx, exec, mods...)
			},
		),
	}
}

// LoadProviderConfigLLMProviderConfig loads the llmProviderModel's ProviderConfigLLMProviderConfig into the .R struct
func (o *LLMProviderModel) LoadProviderConfigLLMProviderConfig(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.ProviderConfigLLMProviderConfig = nil

	related, err := o.ProviderConfigLLMProviderConfig(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R.ProviderConfigLLMProviderConfig = related
	return nil
}

// LoadProviderConfigLLMProviderConfig loads the llmProviderModel's ProviderConfigLLMProviderConfig into the .R struct
func (os LLMProviderModelSlice) LoadProviderConfigLLMProviderConfig(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	llmProviderConfigs, err := os.ProviderConfigLLMProviderConfig(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range llmProviderConfigs {

			if !(o.ProviderConfigID == rel.ID) {
				continue
			}

			o.R.ProviderConfigLLMProviderConfig = rel
			break
		}
	}

	return nil
}

type llmProviderModelJoins[Q dialect.Joinable] struct {
	typ                             string
	ProviderConfigLLMProviderConfig modAs[Q, llmProviderConfigColumns]
}

func (j llmProviderModelJoins[Q]) aliasedAs(alias string) llmProviderModelJoins[Q] {
	return buildLLMProviderModelJoins[Q](buildLLMProviderModelColumns(alias), j.typ)
}

func buildLLMProviderModelJoins[Q dialect.Joinable](cols llmProviderModelColumns, typ string) llmProviderModelJoins[Q] {
	return llmProviderModelJoins[Q]{
		typ: typ,
		ProviderConfigLLMProviderConfig: modAs[Q, llmProviderConfigColumns]{
			c: LLMProviderConfigs.Columns,
			f: func(to llmProviderConfigColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, LLMProviderConfigs.Name().As(to.Alias())).On(
						to.ID.EQ(cols.ProviderConfigID),
					))
				}

				return mods
			},
		},
	}
}
