// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// RefreshToken is an object representing the database table.
type RefreshToken struct {
	ID        int32               `db:"id,pk" `
	UserID    int32               `db:"user_id" `
	TokenHash string              `db:"token_hash" `
	ExpiresAt time.Time           `db:"expires_at" `
	RevokedAt null.Val[time.Time] `db:"revoked_at" `
	CreatedAt time.Time           `db:"created_at" `

	R refreshTokenR `db:"-" `
}

// RefreshTokenSlice is an alias for a slice of pointers to RefreshToken.
// This should almost always be used instead of []*RefreshToken.
type RefreshTokenSlice []*RefreshToken

// RefreshTokens contains methods to work with the refresh_tokens table
var RefreshTokens = psql.NewTablex[*RefreshToken, RefreshTokenSlice, *RefreshTokenSetter]("", "refresh_tokens", buildRefreshTokenColumns("refresh_tokens"))

// RefreshTokensQuery is a query on the refresh_tokens table
type RefreshTokensQuery = *psql.ViewQuery[*RefreshToken, RefreshTokenSlice]

// refreshTokenR is where relationships are stored.
type refreshTokenR struct {
	User *User // refresh_tokens.refresh_tokens_user_id_fkey
	// Loaded reports whether each relationship has been loaded.
	// A relationship's bool is set by Load*, Preload, ThenLoad, factory builds,
	// and to-one Attach/Insert operations. To-many Attach/Insert operations leave it unchanged.
	Loaded refreshTokenRLoaded `db:"-" `
}

// refreshTokenRLoaded tracks which relationships on RefreshToken have been loaded.
type refreshTokenRLoaded struct {
	User bool // refresh_tokens.refresh_tokens_user_id_fkey
}

func buildRefreshTokenColumns(tableName string) refreshTokenColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "user_id", "token_hash", "expires_at", "revoked_at", "created_at",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return refreshTokenColumns{
		ColumnsExpr: columnsExpr,
		tableAlias:  tableName,
		ID:          buildRefreshTokenColumn(tableName, "id"),
		UserID:      buildRefreshTokenColumn(tableName, "user_id"),
		TokenHash:   buildRefreshTokenColumn(tableName, "token_hash"),
		ExpiresAt:   buildRefreshTokenColumn(tableName, "expires_at"),
		RevokedAt:   buildRefreshTokenColumn(tableName, "revoked_at"),
		CreatedAt:   buildRefreshTokenColumn(tableName, "created_at"),
	}
}

type refreshTokenColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         refreshTokenColumn
	UserID     refreshTokenColumn
	TokenHash  refreshTokenColumn
	ExpiresAt  refreshTokenColumn
	RevokedAt  refreshTokenColumn
	CreatedAt  refreshTokenColumn
}

// Alias returns the current table alias for the columns set.
func (c refreshTokenColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (refreshTokenColumns) AliasedAs(tableName string) refreshTokenColumns {
	return buildRefreshTokenColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c refreshTokenColumns) Unqualified() refreshTokenColumns {
	return buildRefreshTokenColumns("")
}

func buildRefreshTokenColumn(alias, name string) refreshTokenColumn {
	return refreshTokenColumn{
		Expression: psql.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type refreshTokenColumn struct {
	psql.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c refreshTokenColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c refreshTokenColumn) ShouldOmitParens() bool {
	return true
}

// RefreshTokenSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type RefreshTokenSetter struct {
	ID        omit.Val[int32]         `db:"id,pk" `
	UserID    omit.Val[int32]         `db:"user_id" `
	TokenHash omit.Val[string]        `db:"token_hash" `
	ExpiresAt omit.Val[time.Time]     `db:"expires_at" `
	RevokedAt omitnull.Val[time.Time] `db:"revoked_at" `
	CreatedAt omit.Val[time.Time]     `db:"created_at" `
}

func (s RefreshTokenSetter) SetColumns() []string {
	vals := make([]string, 0, 6)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.UserID.IsValue() {
		vals = append(vals, "user_id")
	}
	if s.TokenHash.IsValue() {
		vals = append(vals, "token_hash")
	}
	if s.ExpiresAt.IsValue() {
		vals = append(vals, "expires_at")
	}
	if !s.RevokedAt.IsUnset() {
		vals = append(vals, "revoked_at")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	return vals
}

func (s RefreshTokenSetter) Overwrite(t *RefreshToken) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.UserID.IsValue() {
		t.UserID = s.UserID.MustGet()
	}
	if s.TokenHash.IsValue() {
		t.TokenHash = s.TokenHash.MustGet()
	}
	if s.ExpiresAt.IsValue() {
		t.ExpiresAt = s.ExpiresAt.MustGet()
	}
	if !s.RevokedAt.IsUnset() {
		t.RevokedAt = s.RevokedAt.MustGetNull()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
}

func (s *RefreshTokenSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return RefreshTokens.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 6)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.UserID.IsValue() {
			vals[1] = psql.Arg(s.UserID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.TokenHash.IsValue() {
			vals[2] = psql.Arg(s.TokenHash.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.ExpiresAt.IsValue() {
			vals[3] = psql.Arg(s.ExpiresAt.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if !s.RevokedAt.IsUnset() {
			vals[4] = psql.Arg(s.RevokedAt.MustGetNull())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[5] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s RefreshTokenSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s RefreshTokenSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 6)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.UserID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "user_id")...),
			psql.Arg(s.UserID),
		}})
	}

	if s.TokenHash.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "token_hash")...),
			psql.Arg(s.TokenHash),
		}})
	}

	if s.ExpiresAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "expires_at")...),
			psql.Arg(s.ExpiresAt),
		}})
	}

	if !s.RevokedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "revoked_at")...),
			psql.Arg(s.RevokedAt),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	return exprs
}

// FindRefreshToken retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindRefreshToken(ctx context.Context, exec bob.Executor, IDPK int32, cols ...string) (*RefreshToken, error) {
	if len(cols) == 0 {
		return RefreshTokens.Query(
			sm.Where(RefreshTokens.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return RefreshTokens.Query(
		sm.Where(RefreshTokens.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(RefreshTokens.Columns.Only(cols...)),
	).One(ctx, exec)
}

// RefreshTokenExists checks the presence of a single record by primary key
func RefreshTokenExists(ctx context.Context, exec bob.Executor, IDPK int32) (bool, error) {
	return RefreshTokens.Query(
		sm.Where(RefreshTokens.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after RefreshToken is retrieved from the database
func (o *RefreshToken) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = RefreshTokens.AfterSelectHooks.RunHooks(ctx, exec, RefreshTokenSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = RefreshTokens.AfterInsertHooks.RunHooks(ctx, exec, RefreshTokenSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = RefreshTokens.AfterUpdateHooks.RunHooks(ctx, exec, RefreshTokenSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = RefreshTokens.AfterDeleteHooks.RunHooks(ctx, exec, RefreshTokenSlice{o})
	case bob.QueryTypeMerge:
		ctx, err = RefreshTokens.AfterMergeHooks.RunHooks(ctx, exec, RefreshTokenSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the RefreshToken
func (o *RefreshToken) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *RefreshToken) pkEQ() dialect.Expression {
	return psql.Quote("refresh_tokens", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the RefreshToken
func (o *RefreshToken) Update(ctx context.Context, exec bob.Executor, s *RefreshTokenSetter) error {
	v, err := RefreshTokens.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single RefreshToken record with an executor
func (o *RefreshToken) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := RefreshTokens.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the RefreshToken using the executor
func (o *RefreshToken) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := RefreshTokens.Query(
		sm.Where(RefreshTokens.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after RefreshTokenSlice is retrieved from the database
func (o RefreshTokenSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = RefreshTokens.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = RefreshTokens.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = RefreshTokens.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = RefreshTokens.AfterDeleteHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeMerge:
		ctx, err = RefreshTokens.AfterMergeHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o RefreshTokenSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("refresh_tokens", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o RefreshTokenSlice) copyMatchingRows(from ...*RefreshToken) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o RefreshTokenSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return RefreshTokens.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *RefreshToken:
				o.copyMatchingRows(retrieved)
			case []*RefreshToken:
				o.copyMatchingRows(retrieved...)
			case RefreshTokenSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a RefreshToken or a slice of RefreshToken
				// then run the AfterUpdateHooks on the slice
				_, err = RefreshTokens.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o RefreshTokenSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return RefreshTokens.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *RefreshToken:
				o.copyMatchingRows(retrieved)
			case []*RefreshToken:
				o.copyMatchingRows(retrieved...)
			case RefreshTokenSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a RefreshToken or a slice of RefreshToken
				// then run the AfterDeleteHooks on the slice
				_, err = RefreshTokens.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// MergeMod modifies a merge query to run BeforeMergeHooks and AfterMergeHooks
// and updates the slice with the returned rows.
func (o RefreshTokenSlice) MergeMod() bob.Mod[*dialect.MergeQuery] {
	return bob.ModFunc[*dialect.MergeQuery](func(q *dialect.MergeQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return RefreshTokens.BeforeMergeHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *RefreshToken:
				o.copyMatchingRows(retrieved)
			case []*RefreshToken:
				o.copyMatchingRows(retrieved...)
			case RefreshTokenSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a RefreshToken or a slice of RefreshToken
				// then run the AfterMergeHooks on the slice
				_, err = RefreshTokens.AfterMergeHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))
	})
}

func (o RefreshTokenSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals RefreshTokenSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := RefreshTokens.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o RefreshTokenSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := RefreshTokens.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o RefreshTokenSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := RefreshTokens.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// User starts a query for related objects on users
func (o *RefreshToken) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(Users.Columns.ID.EQ(psql.Arg(o.UserID))),
	)...)
}

func (os RefreshTokenSlice) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkUserID := make(pgtypes.Array[int32], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkUserID = append(pkUserID, o.UserID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkUserID), "integer[]")),
	))

	return Users.Query(append(mods,
		sm.Where(psql.Group(Users.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachRefreshTokenUser0(ctx context.Context, exec bob.Executor, count int, refreshToken0 *RefreshToken, user1 *User) (*RefreshToken, error) {
	setter := &RefreshTokenSetter{
		UserID: omit.From(user1.ID),
	}

	err := refreshToken0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachRefreshTokenUser0: %w", err)
	}

	return refreshToken0, nil
}

func (refreshToken0 *RefreshToken) InsertUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	var err error

	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachRefreshTokenUser0(ctx, exec, 1, refreshToken0, user1)
	if err != nil {
		return err
	}

	refreshToken0.R.User = user1
	refreshToken0.R.Loaded.User = true

	return nil
}

func (refreshToken0 *RefreshToken) AttachUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachRefreshTokenUser0(ctx, exec, 1, refreshToken0, user1)
	if err != nil {
		return err
	}

	refreshToken0.R.User = user1
	refreshToken0.R.Loaded.User = true

	return nil
}

type refreshTokenWhere[Q psql.Filterable] struct {
	ID        psql.WhereMod[Q, int32]
	UserID    psql.WhereMod[Q, int32]
	TokenHash psql.WhereMod[Q, string]
	ExpiresAt psql.WhereMod[Q, time.Time]
	RevokedAt psql.WhereNullMod[Q, time.Time]
	CreatedAt psql.WhereMod[Q, time.Time]
}

func (refreshTokenWhere[Q]) AliasedAs(alias string) refreshTokenWhere[Q] {
	return buildRefreshTokenWhere[Q](buildRefreshTokenColumns(alias))
}

func buildRefreshTokenWhere[Q psql.Filterable](cols refreshTokenColumns) refreshTokenWhere[Q] {
	return refreshTokenWhere[Q]{
		ID:        psql.Where[Q, int32](cols.ID.Expression),
		UserID:    psql.Where[Q, int32](cols.UserID.Expression),
		TokenHash: psql.Where[Q, string](cols.TokenHash.Expression),
		ExpiresAt: psql.Where[Q, time.Time](cols.ExpiresAt.Expression),
		RevokedAt: psql.WhereNull[Q, time.Time](cols.RevokedAt.Expression),
		CreatedAt: psql.Where[Q, time.Time](cols.CreatedAt.Expression),
	}
}

func (o *RefreshToken) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "User":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("refreshToken cannot load %T as %q", retrieved, name)
		}

		o.R.User = rel
		o.R.Loaded.User = true

		return nil
	default:
		return fmt.Errorf("refreshToken has no relationship %q", name)
	}
}

type refreshTokenPreloader struct {
	User func(...psql.PreloadOption) psql.Preloader
}

func buildRefreshTokenPreloader() refreshTokenPreloader {
	return refreshTokenPreloader{
		User: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*User, UserSlice](psql.PreloadRel{
				Name: "User",
				Sides: []psql.PreloadSide{
					{
						From:        RefreshTokens,
						To:          Users,
						FromColumns: []string{"user_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Users.Columns.Names(), opts...)
		},
	}
}

type refreshTokenThenLoader[Q orm.Loadable] struct {
	User func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildRefreshTokenThenLoader[Q orm.Loadable]() refreshTokenThenLoader[Q] {
	type UserLoadInterface interface {
		LoadUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return refreshTokenThenLoader[Q]{
		User: thenLoadBuilder[Q](
			"User",
			func(ctx context.Context, exec bob.Executor, retrieved UserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUser(ctx, exec, mods...)
			},
		),
	}
}

// LoadUser loads the refreshToken's User into the .R struct
func (o *RefreshToken) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.User = nil
	o.R.Loaded.User = false

	related, err := o.User(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R.User = related
	o.R.Loaded.User = true
	return nil
}

// LoadUser loads the refreshToken's User into the .R struct
func (os RefreshTokenSlice) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.User(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.User = nil
		o.R.Loaded.User = true
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range users {

			if !(o.UserID == rel.ID) {
				continue
			}

			o.R.User = rel
			break
		}
	}

	return nil
}

type refreshTokenJoins[Q dialect.Joinable] struct {
	typ  string
	User modAs[Q, userColumns]
}

func (j refreshTokenJoins[Q]) aliasedAs(alias string) refreshTokenJoins[Q] {
	return buildRefreshTokenJoins[Q](buildRefreshTokenColumns(alias), j.typ)
}

func buildRefreshTokenJoins[Q dialect.Joinable](cols refreshTokenColumns, typ string) refreshTokenJoins[Q] {
	return refreshTokenJoins[Q]{
		typ: typ,
		User: modAs[Q, userColumns]{
			c: Users.Columns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.UserID),
					))
				}

				return mods
			},
		},
	}
}
