// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// SchemaEmbeddingJob is an object representing the database table.
type SchemaEmbeddingJob struct {
	SnapshotID   int32               `db:"snapshot_id" `
	Status       string              `db:"status" `
	ErrorMessage null.Val[string]    `db:"error_message" `
	RetryCount   int32               `db:"retry_count" `
	StartedAt    time.Time           `db:"started_at" `
	CompletedAt  null.Val[time.Time] `db:"completed_at" `

	R schemaEmbeddingJobR `db:"-" `
}

// SchemaEmbeddingJobSlice is an alias for a slice of pointers to SchemaEmbeddingJob.
// This should almost always be used instead of []*SchemaEmbeddingJob.
type SchemaEmbeddingJobSlice []*SchemaEmbeddingJob

// SchemaEmbeddingJobs contains methods to work with the schema_embedding_jobs view
var SchemaEmbeddingJobs = psql.NewViewx[*SchemaEmbeddingJob, SchemaEmbeddingJobSlice]("", "schema_embedding_jobs", buildSchemaEmbeddingJobColumns("schema_embedding_jobs"))

// SchemaEmbeddingJobsQuery is a query on the schema_embedding_jobs view
type SchemaEmbeddingJobsQuery = *psql.ViewQuery[*SchemaEmbeddingJob, SchemaEmbeddingJobSlice]

// schemaEmbeddingJobR is where relationships are stored.
type schemaEmbeddingJobR struct {
	SnapshotSchemaSnapshot *SchemaSnapshot // schema_embedding_jobs.schema_embedding_jobs_snapshot_id_fkey
}

func buildSchemaEmbeddingJobColumns(alias string) schemaEmbeddingJobColumns {
	return schemaEmbeddingJobColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"snapshot_id", "status", "error_message", "retry_count", "started_at", "completed_at",
		).WithParent("schema_embedding_jobs"),
		tableAlias:   alias,
		SnapshotID:   psql.Quote(alias, "snapshot_id"),
		Status:       psql.Quote(alias, "status"),
		ErrorMessage: psql.Quote(alias, "error_message"),
		RetryCount:   psql.Quote(alias, "retry_count"),
		StartedAt:    psql.Quote(alias, "started_at"),
		CompletedAt:  psql.Quote(alias, "completed_at"),
	}
}

type schemaEmbeddingJobColumns struct {
	expr.ColumnsExpr
	tableAlias   string
	SnapshotID   psql.Expression
	Status       psql.Expression
	ErrorMessage psql.Expression
	RetryCount   psql.Expression
	StartedAt    psql.Expression
	CompletedAt  psql.Expression
}

func (c schemaEmbeddingJobColumns) Alias() string {
	return c.tableAlias
}

func (schemaEmbeddingJobColumns) AliasedAs(alias string) schemaEmbeddingJobColumns {
	return buildSchemaEmbeddingJobColumns(alias)
}

// SchemaEmbeddingJobSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type SchemaEmbeddingJobSetter struct {
	SnapshotID   omit.Val[int32]         `db:"snapshot_id" `
	Status       omit.Val[string]        `db:"status" `
	ErrorMessage omitnull.Val[string]    `db:"error_message" `
	RetryCount   omit.Val[int32]         `db:"retry_count" `
	StartedAt    omit.Val[time.Time]     `db:"started_at" `
	CompletedAt  omitnull.Val[time.Time] `db:"completed_at" `
}

func (s SchemaEmbeddingJobSetter) SetColumns() []string {
	vals := make([]string, 0, 6)
	if s.SnapshotID.IsValue() {
		vals = append(vals, "snapshot_id")
	}
	if s.Status.IsValue() {
		vals = append(vals, "status")
	}
	if !s.ErrorMessage.IsUnset() {
		vals = append(vals, "error_message")
	}
	if s.RetryCount.IsValue() {
		vals = append(vals, "retry_count")
	}
	if s.StartedAt.IsValue() {
		vals = append(vals, "started_at")
	}
	if !s.CompletedAt.IsUnset() {
		vals = append(vals, "completed_at")
	}
	return vals
}

func (s SchemaEmbeddingJobSetter) Overwrite(t *SchemaEmbeddingJob) {
	if s.SnapshotID.IsValue() {
		t.SnapshotID = s.SnapshotID.MustGet()
	}
	if s.Status.IsValue() {
		t.Status = s.Status.MustGet()
	}
	if !s.ErrorMessage.IsUnset() {
		t.ErrorMessage = s.ErrorMessage.MustGetNull()
	}
	if s.RetryCount.IsValue() {
		t.RetryCount = s.RetryCount.MustGet()
	}
	if s.StartedAt.IsValue() {
		t.StartedAt = s.StartedAt.MustGet()
	}
	if !s.CompletedAt.IsUnset() {
		t.CompletedAt = s.CompletedAt.MustGetNull()
	}
}

func (s *SchemaEmbeddingJobSetter) Apply(q *dialect.InsertQuery) {
	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 6)
		if s.SnapshotID.IsValue() {
			vals[0] = psql.Arg(s.SnapshotID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.Status.IsValue() {
			vals[1] = psql.Arg(s.Status.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if !s.ErrorMessage.IsUnset() {
			vals[2] = psql.Arg(s.ErrorMessage.MustGetNull())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.RetryCount.IsValue() {
			vals[3] = psql.Arg(s.RetryCount.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.StartedAt.IsValue() {
			vals[4] = psql.Arg(s.StartedAt.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if !s.CompletedAt.IsUnset() {
			vals[5] = psql.Arg(s.CompletedAt.MustGetNull())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s SchemaEmbeddingJobSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s SchemaEmbeddingJobSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 6)

	if s.SnapshotID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "snapshot_id")...),
			psql.Arg(s.SnapshotID),
		}})
	}

	if s.Status.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "status")...),
			psql.Arg(s.Status),
		}})
	}

	if !s.ErrorMessage.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "error_message")...),
			psql.Arg(s.ErrorMessage),
		}})
	}

	if s.RetryCount.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "retry_count")...),
			psql.Arg(s.RetryCount),
		}})
	}

	if s.StartedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "started_at")...),
			psql.Arg(s.StartedAt),
		}})
	}

	if !s.CompletedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "completed_at")...),
			psql.Arg(s.CompletedAt),
		}})
	}

	return exprs
}

// AfterQueryHook is called after SchemaEmbeddingJob is retrieved from the database
func (o *SchemaEmbeddingJob) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = SchemaEmbeddingJobs.AfterSelectHooks.RunHooks(ctx, exec, SchemaEmbeddingJobSlice{o})
	}

	return err
}

// AfterQueryHook is called after SchemaEmbeddingJobSlice is retrieved from the database
func (o SchemaEmbeddingJobSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = SchemaEmbeddingJobs.AfterSelectHooks.RunHooks(ctx, exec, o)
	}

	return err
}

// SnapshotSchemaSnapshot starts a query for related objects on schema_snapshots
func (o *SchemaEmbeddingJob) SnapshotSchemaSnapshot(mods ...bob.Mod[*dialect.SelectQuery]) SchemaSnapshotsQuery {
	return SchemaSnapshots.Query(append(mods,
		sm.Where(SchemaSnapshots.Columns.ID.EQ(psql.Arg(o.SnapshotID))),
	)...)
}

func (os SchemaEmbeddingJobSlice) SnapshotSchemaSnapshot(mods ...bob.Mod[*dialect.SelectQuery]) SchemaSnapshotsQuery {
	pkSnapshotID := make(pgtypes.Array[int32], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkSnapshotID = append(pkSnapshotID, o.SnapshotID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkSnapshotID), "integer[]")),
	))

	return SchemaSnapshots.Query(append(mods,
		sm.Where(psql.Group(SchemaSnapshots.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

type schemaEmbeddingJobWhere[Q psql.Filterable] struct {
	SnapshotID   psql.WhereMod[Q, int32]
	Status       psql.WhereMod[Q, string]
	ErrorMessage psql.WhereNullMod[Q, string]
	RetryCount   psql.WhereMod[Q, int32]
	StartedAt    psql.WhereMod[Q, time.Time]
	CompletedAt  psql.WhereNullMod[Q, time.Time]
}

func (schemaEmbeddingJobWhere[Q]) AliasedAs(alias string) schemaEmbeddingJobWhere[Q] {
	return buildSchemaEmbeddingJobWhere[Q](buildSchemaEmbeddingJobColumns(alias))
}

func buildSchemaEmbeddingJobWhere[Q psql.Filterable](cols schemaEmbeddingJobColumns) schemaEmbeddingJobWhere[Q] {
	return schemaEmbeddingJobWhere[Q]{
		SnapshotID:   psql.Where[Q, int32](cols.SnapshotID),
		Status:       psql.Where[Q, string](cols.Status),
		ErrorMessage: psql.WhereNull[Q, string](cols.ErrorMessage),
		RetryCount:   psql.Where[Q, int32](cols.RetryCount),
		StartedAt:    psql.Where[Q, time.Time](cols.StartedAt),
		CompletedAt:  psql.WhereNull[Q, time.Time](cols.CompletedAt),
	}
}

func (o *SchemaEmbeddingJob) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "SnapshotSchemaSnapshot":
		rel, ok := retrieved.(*SchemaSnapshot)
		if !ok {
			return fmt.Errorf("schemaEmbeddingJob cannot load %T as %q", retrieved, name)
		}

		o.R.SnapshotSchemaSnapshot = rel

		return nil
	default:
		return fmt.Errorf("schemaEmbeddingJob has no relationship %q", name)
	}
}

type schemaEmbeddingJobPreloader struct {
	SnapshotSchemaSnapshot func(...psql.PreloadOption) psql.Preloader
}

func buildSchemaEmbeddingJobPreloader() schemaEmbeddingJobPreloader {
	return schemaEmbeddingJobPreloader{
		SnapshotSchemaSnapshot: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*SchemaSnapshot, SchemaSnapshotSlice](psql.PreloadRel{
				Name: "SnapshotSchemaSnapshot",
				Sides: []psql.PreloadSide{
					{
						From:        SchemaEmbeddingJobs,
						To:          SchemaSnapshots,
						FromColumns: []string{"snapshot_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, SchemaSnapshots.Columns.Names(), opts...)
		},
	}
}

type schemaEmbeddingJobThenLoader[Q orm.Loadable] struct {
	SnapshotSchemaSnapshot func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildSchemaEmbeddingJobThenLoader[Q orm.Loadable]() schemaEmbeddingJobThenLoader[Q] {
	type SnapshotSchemaSnapshotLoadInterface interface {
		LoadSnapshotSchemaSnapshot(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return schemaEmbeddingJobThenLoader[Q]{
		SnapshotSchemaSnapshot: thenLoadBuilder[Q](
			"SnapshotSchemaSnapshot",
			func(ctx context.Context, exec bob.Executor, retrieved SnapshotSchemaSnapshotLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadSnapshotSchemaSnapshot(ctx, exec, mods...)
			},
		),
	}
}

// LoadSnapshotSchemaSnapshot loads the schemaEmbeddingJob's SnapshotSchemaSnapshot into the .R struct
func (o *SchemaEmbeddingJob) LoadSnapshotSchemaSnapshot(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.SnapshotSchemaSnapshot = nil

	related, err := o.SnapshotSchemaSnapshot(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R.SnapshotSchemaSnapshot = related
	return nil
}

// LoadSnapshotSchemaSnapshot loads the schemaEmbeddingJob's SnapshotSchemaSnapshot into the .R struct
func (os SchemaEmbeddingJobSlice) LoadSnapshotSchemaSnapshot(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	schemaSnapshots, err := os.SnapshotSchemaSnapshot(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range schemaSnapshots {

			if !(o.SnapshotID == rel.ID) {
				continue
			}

			o.R.SnapshotSchemaSnapshot = rel
			break
		}
	}

	return nil
}

type schemaEmbeddingJobJoins[Q dialect.Joinable] struct {
	typ                    string
	SnapshotSchemaSnapshot modAs[Q, schemaSnapshotColumns]
}

func (j schemaEmbeddingJobJoins[Q]) aliasedAs(alias string) schemaEmbeddingJobJoins[Q] {
	return buildSchemaEmbeddingJobJoins[Q](buildSchemaEmbeddingJobColumns(alias), j.typ)
}

func buildSchemaEmbeddingJobJoins[Q dialect.Joinable](cols schemaEmbeddingJobColumns, typ string) schemaEmbeddingJobJoins[Q] {
	return schemaEmbeddingJobJoins[Q]{
		typ: typ,
		SnapshotSchemaSnapshot: modAs[Q, schemaSnapshotColumns]{
			c: SchemaSnapshots.Columns,
			f: func(to schemaSnapshotColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, SchemaSnapshots.Name().As(to.Alias())).On(
						to.ID.EQ(cols.SnapshotID),
					))
				}

				return mods
			},
		},
	}
}
