// Code generated by mockery v2.53.5. DO NOT EDIT.

package testing

import (
	context "context"

	pubsub "github.com/Uncensored-Developer/datalk/apps/backend/pkg/pubsub"
	mock "github.com/stretchr/testify/mock"
)

// Subscriber is an autogenerated mock type for the Subscriber type
type Subscriber struct {
	mock.Mock
}

// Subscribe provides a mock function with given fields: ctx, topic, handler, opts
func (_m *Subscriber) Subscribe(ctx context.Context, topic string, handler pubsub.Handler, opts ...pubsub.SubscribeOption) (pubsub.Subscription, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, topic, handler)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 pubsub.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, pubsub.Handler, ...pubsub.SubscribeOption) (pubsub.Subscription, error)); ok {
		return rf(ctx, topic, handler, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, pubsub.Handler, ...pubsub.SubscribeOption) pubsub.Subscription); ok {
		r0 = rf(ctx, topic, handler, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pubsub.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, pubsub.Handler, ...pubsub.SubscribeOption) error); ok {
		r1 = rf(ctx, topic, handler, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSubscriber creates a new instance of Subscriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubscriber(t interface {
	mock.TestingT
	Cleanup(func())
},
) *Subscriber {
	mock := &Subscriber{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
