// Code generated by mockery v2.53.5. DO NOT EDIT.

package testing

import mock "github.com/stretchr/testify/mock"

// LockedResources is an autogenerated mock type for the LockedResources type
type LockedResources struct {
	mock.Mock
}

// Resources provides a mock function with no fields
func (_m *LockedResources) Resources() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Resources")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// UncheckedUnlock provides a mock function with no fields
func (_m *LockedResources) UncheckedUnlock() {
	_m.Called()
}

// Unlock provides a mock function with no fields
func (_m *LockedResources) Unlock() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Unlock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewLockedResources creates a new instance of LockedResources. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLockedResources(t interface {
	mock.TestingT
	Cleanup(func())
},
) *LockedResources {
	mock := &LockedResources{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
