// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package errors

var ChatConversationErrors = &chatConversationErrors{
	ErrUniqueChatConversationsPkey: &UniqueConstraintError{
		schema:  "",
		table:   "chat_conversations",
		columns: []string{"id"},
		s:       "chat_conversations_pkey",
	},
}

type chatConversationErrors struct {
	ErrUniqueChatConversationsPkey *UniqueConstraintError
}
