// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package errors

var ConnectionAccessErrors = &connectionAccessErrors{
	ErrUniquePkMainConnectionAccess: &UniqueConstraintError{
		schema:  "",
		table:   "connection_access",
		columns: []string{"user_id", "connection_id"},
		s:       "pk_main_connection_access",
	},
}

type connectionAccessErrors struct {
	ErrUniquePkMainConnectionAccess *UniqueConstraintError
}
