// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package errors

var ConnectionNamespaceErrors = &connectionNamespaceErrors{
	ErrUniqueConnectionNamespacesPkey: &UniqueConstraintError{
		schema:  "",
		table:   "connection_namespaces",
		columns: []string{"id"},
		s:       "connection_namespaces_pkey",
	},

	ErrUniqueConnectionNamespacesConnectionIdNamespaceTypeNameKey: &UniqueConstraintError{
		schema:  "",
		table:   "connection_namespaces",
		columns: []string{"connection_id", "namespace_type", "name"},
		s:       "connection_namespaces_connection_id_namespace_type_name_key",
	},
}

type connectionNamespaceErrors struct {
	ErrUniqueConnectionNamespacesPkey *UniqueConstraintError

	ErrUniqueConnectionNamespacesConnectionIdNamespaceTypeNameKey *UniqueConstraintError
}
