// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package errors

var LLMProviderConfigErrors = &llmProviderConfigErrors{
	ErrUniqueLlmProviderConfigsPkey: &UniqueConstraintError{
		schema:  "",
		table:   "llm_provider_configs",
		columns: []string{"id"},
		s:       "llm_provider_configs_pkey",
	},
}

type llmProviderConfigErrors struct {
	ErrUniqueLlmProviderConfigsPkey *UniqueConstraintError
}
