// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package errors

var OrganizationErrors = &organizationErrors{
	ErrUniquePkMainOrganization: &UniqueConstraintError{
		schema:  "",
		table:   "organization",
		columns: []string{"id"},
		s:       "pk_main_organization",
	},

	ErrUniqueSqliteAutoindexOrganization1: &UniqueConstraintError{
		schema:  "",
		table:   "organization",
		columns: []string{"singleton"},
		s:       "sqlite_autoindex_organization_1",
	},
}

type organizationErrors struct {
	ErrUniquePkMainOrganization *UniqueConstraintError

	ErrUniqueSqliteAutoindexOrganization1 *UniqueConstraintError
}
