// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package errors

var SchemaSnapshotErrors = &schemaSnapshotErrors{
	ErrUniqueSchemaSnapshotsPkey: &UniqueConstraintError{
		schema:  "",
		table:   "schema_snapshots",
		columns: []string{"id"},
		s:       "schema_snapshots_pkey",
	},

	ErrUniqueSchemaSnapshotsConnectionIdSchemaHashKey: &UniqueConstraintError{
		schema:  "",
		table:   "schema_snapshots",
		columns: []string{"connection_id", "schema_hash"},
		s:       "schema_snapshots_connection_id_schema_hash_key",
	},
}

type schemaSnapshotErrors struct {
	ErrUniqueSchemaSnapshotsPkey *UniqueConstraintError

	ErrUniqueSchemaSnapshotsConnectionIdSchemaHashKey *UniqueConstraintError
}
