// Code generated by mockery v2.53.5. DO NOT EDIT.

package testing

import (
	context "context"

	sqlrunner "github.com/Uncensored-Developer/datalk/apps/backend/services/chat/internal/chat/sqlrunner"
	chat "github.com/Uncensored-Developer/datalk/apps/backend/services/chat/pkg/chat"
	connections "github.com/Uncensored-Developer/datalk/apps/backend/services/connections/pkg/connections"
	mock "github.com/stretchr/testify/mock"
)

// SQLRunner is an autogenerated mock type for the SQLRunner type
type SQLRunner struct {
	mock.Mock
}

// Run provides a mock function with given fields: ctx, connection, query, options
func (_m *SQLRunner) Run(ctx context.Context, connection connections.Connection, query string, options sqlrunner.RunOptions) (*chat.QueryResult, error) {
	ret := _m.Called(ctx, connection, query, options)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 *chat.QueryResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, connections.Connection, string, sqlrunner.RunOptions) (*chat.QueryResult, error)); ok {
		return rf(ctx, connection, query, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, connections.Connection, string, sqlrunner.RunOptions) *chat.QueryResult); ok {
		r0 = rf(ctx, connection, query, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chat.QueryResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, connections.Connection, string, sqlrunner.RunOptions) error); ok {
		r1 = rf(ctx, connection, query, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSQLRunner creates a new instance of SQLRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSQLRunner(t interface {
	mock.TestingT
	Cleanup(func())
},
) *SQLRunner {
	mock := &SQLRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
