// Code generated by mockery v2.53.5. DO NOT EDIT.

package testing

import (
	context "context"

	connections "github.com/Uncensored-Developer/datalk/apps/backend/services/connections/pkg/connections"
	introspector "github.com/Uncensored-Developer/datalk/apps/backend/services/schemas/internal/schemas/introspector"
	mock "github.com/stretchr/testify/mock"
)

// IntrospectorFactory is an autogenerated mock type for the IntrospectorFactory type
type IntrospectorFactory struct {
	mock.Mock
}

// ForConnection provides a mock function with given fields: ctx, connection
func (_m *IntrospectorFactory) ForConnection(ctx context.Context, connection connections.Connection) (introspector.Introspector, error) {
	ret := _m.Called(ctx, connection)

	if len(ret) == 0 {
		panic("no return value specified for ForConnection")
	}

	var r0 introspector.Introspector
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, connections.Connection) (introspector.Introspector, error)); ok {
		return rf(ctx, connection)
	}
	if rf, ok := ret.Get(0).(func(context.Context, connections.Connection) introspector.Introspector); ok {
		r0 = rf(ctx, connection)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(introspector.Introspector)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, connections.Connection) error); ok {
		r1 = rf(ctx, connection)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIntrospectorFactory creates a new instance of IntrospectorFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIntrospectorFactory(t interface {
	mock.TestingT
	Cleanup(func())
},
) *IntrospectorFactory {
	mock := &IntrospectorFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
