// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package info

import "github.com/aarondl/opt/null"

var ChatMessages = Table[
	chatMessageColumns,
	chatMessageIndexes,
	chatMessageForeignKeys,
	chatMessageUniques,
	chatMessageChecks,
]{
	Schema: "",
	Name:   "chat_messages",
	Columns: chatMessageColumns{
		ID: column{
			Name:      "id",
			DBType:    "bigint",
			Default:   "nextval('datalk.chat_messages_id_seq'::regclass)",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ConversationID: column{
			Name:      "conversation_id",
			DBType:    "bigint",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Role: column{
			Name:      "role",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Content: column{
			Name:      "content",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Provider: column{
			Name:      "provider",
			DBType:    "text",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Model: column{
			Name:      "model",
			DBType:    "text",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Status: column{
			Name:      "status",
			DBType:    "text",
			Default:   "'completed'::text",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ErrorMessage: column{
			Name:      "error_message",
			DBType:    "text",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: chatMessageIndexes{
		ChatMessagesPkey: index{
			Type: "btree",
			Name: "chat_messages_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		ChatMessagesConversationCreatedIdx: index{
			Type: "btree",
			Name: "chat_messages_conversation_created_idx",
			Columns: []indexColumn{
				{
					Name:         "conversation_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "created_at",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false, false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "chat_messages_pkey",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: chatMessageForeignKeys{
		ChatMessagesChatMessagesConversationIDFkey: foreignKey{
			constraint: constraint{
				Name:    "chat_messages.chat_messages_conversation_id_fkey",
				Columns: []string{"conversation_id"},
				Comment: "",
			},
			ForeignTable:   "chat_conversations",
			ForeignColumns: []string{"id"},
		},
	},

	Checks: chatMessageChecks{
		ChatMessagesProviderCheck: check{
			constraint: constraint{
				Name:    "chat_messages_provider_check",
				Columns: []string{"provider"},
				Comment: "",
			},
			Expression: "(provider = ANY (ARRAY['openai'::text, 'anthropic'::text, 'gemini'::text, 'ollama'::text]))",
		},
		ChatMessagesRoleCheck: check{
			constraint: constraint{
				Name:    "chat_messages_role_check",
				Columns: []string{"role"},
				Comment: "",
			},
			Expression: "(role = ANY (ARRAY['user'::text, 'assistant'::text]))",
		},
		ChatMessagesStatusCheck: check{
			constraint: constraint{
				Name:    "chat_messages_status_check",
				Columns: []string{"status"},
				Comment: "",
			},
			Expression: "(status = ANY (ARRAY['pending'::text, 'completed'::text, 'failed'::text]))",
		},
	},
	Comment: "",
}

type chatMessageColumns struct {
	ID             column
	ConversationID column
	Role           column
	Content        column
	Provider       column
	Model          column
	Status         column
	ErrorMessage   column
	CreatedAt      column
}

func (c chatMessageColumns) AsSlice() []column {
	return []column{
		c.ID, c.ConversationID, c.Role, c.Content, c.Provider, c.Model, c.Status, c.ErrorMessage, c.CreatedAt,
	}
}

type chatMessageIndexes struct {
	ChatMessagesPkey                   index
	ChatMessagesConversationCreatedIdx index
}

func (i chatMessageIndexes) AsSlice() []index {
	return []index{
		i.ChatMessagesPkey, i.ChatMessagesConversationCreatedIdx,
	}
}

type chatMessageForeignKeys struct {
	ChatMessagesChatMessagesConversationIDFkey foreignKey
}

func (f chatMessageForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.ChatMessagesChatMessagesConversationIDFkey,
	}
}

type chatMessageUniques struct{}

func (u chatMessageUniques) AsSlice() []constraint {
	return []constraint{}
}

type chatMessageChecks struct {
	ChatMessagesProviderCheck check
	ChatMessagesRoleCheck     check
	ChatMessagesStatusCheck   check
}

func (c chatMessageChecks) AsSlice() []check {
	return []check{
		c.ChatMessagesProviderCheck, c.ChatMessagesRoleCheck, c.ChatMessagesStatusCheck,
	}
}
