// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package info

import "github.com/aarondl/opt/null"

var ChatMessageLLMCalls = Table[
	chatMessageLLMCallColumns,
	chatMessageLLMCallIndexes,
	chatMessageLLMCallForeignKeys,
	chatMessageLLMCallUniques,
	chatMessageLLMCallChecks,
]{
	Schema: "",
	Name:   "chat_message_llm_calls",
	Columns: chatMessageLLMCallColumns{
		ID: column{
			Name:      "id",
			DBType:    "bigint",
			Default:   "nextval('datalk.chat_message_llm_calls_id_seq'::regclass)",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		MessageID: column{
			Name:      "message_id",
			DBType:    "bigint",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ProviderConfigID: column{
			Name:      "provider_config_id",
			DBType:    "bigint",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Provider: column{
			Name:      "provider",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Model: column{
			Name:      "model",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		RequestJSON: column{
			Name:      "request_json",
			DBType:    "jsonb",
			Default:   "'{}'::jsonb",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ResponseJSON: column{
			Name:      "response_json",
			DBType:    "jsonb",
			Default:   "'{}'::jsonb",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		InputTokens: column{
			Name:      "input_tokens",
			DBType:    "integer",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		OutputTokens: column{
			Name:      "output_tokens",
			DBType:    "integer",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		LatencyMS: column{
			Name:      "latency_ms",
			DBType:    "integer",
			Default:   "0",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: chatMessageLLMCallIndexes{
		ChatMessageLLMCallsPkey: index{
			Type: "btree",
			Name: "chat_message_llm_calls_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		ChatMessageLLMCallsMessageIDIdx: index{
			Type: "btree",
			Name: "chat_message_llm_calls_message_id_idx",
			Columns: []indexColumn{
				{
					Name:         "message_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "created_at",
					Desc:         null.FromCond(true, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false, true},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		ChatMessageLLMCallsProviderConfigIDIdx: index{
			Type: "btree",
			Name: "chat_message_llm_calls_provider_config_id_idx",
			Columns: []indexColumn{
				{
					Name:         "provider_config_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "created_at",
					Desc:         null.FromCond(true, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false, true},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "chat_message_llm_calls_pkey",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: chatMessageLLMCallForeignKeys{
		ChatMessageLLMCallsChatMessageLLMCallsMessageIDFkey: foreignKey{
			constraint: constraint{
				Name:    "chat_message_llm_calls.chat_message_llm_calls_message_id_fkey",
				Columns: []string{"message_id"},
				Comment: "",
			},
			ForeignTable:   "chat_messages",
			ForeignColumns: []string{"id"},
		},
		ChatMessageLLMCallsChatMessageLLMCallsProviderConfigIDFkey: foreignKey{
			constraint: constraint{
				Name:    "chat_message_llm_calls.chat_message_llm_calls_provider_config_id_fkey",
				Columns: []string{"provider_config_id"},
				Comment: "",
			},
			ForeignTable:   "llm_provider_configs",
			ForeignColumns: []string{"id"},
		},
	},

	Checks: chatMessageLLMCallChecks{
		ChatMessageLLMCallsProviderCheck: check{
			constraint: constraint{
				Name:    "chat_message_llm_calls_provider_check",
				Columns: []string{"provider"},
				Comment: "",
			},
			Expression: "(provider = ANY (ARRAY['openai'::text, 'anthropic'::text, 'gemini'::text, 'ollama'::text]))",
		},
	},
	Comment: "",
}

type chatMessageLLMCallColumns struct {
	ID               column
	MessageID        column
	ProviderConfigID column
	Provider         column
	Model            column
	RequestJSON      column
	ResponseJSON     column
	InputTokens      column
	OutputTokens     column
	LatencyMS        column
	CreatedAt        column
}

func (c chatMessageLLMCallColumns) AsSlice() []column {
	return []column{
		c.ID, c.MessageID, c.ProviderConfigID, c.Provider, c.Model, c.RequestJSON, c.ResponseJSON, c.InputTokens, c.OutputTokens, c.LatencyMS, c.CreatedAt,
	}
}

type chatMessageLLMCallIndexes struct {
	ChatMessageLLMCallsPkey                index
	ChatMessageLLMCallsMessageIDIdx        index
	ChatMessageLLMCallsProviderConfigIDIdx index
}

func (i chatMessageLLMCallIndexes) AsSlice() []index {
	return []index{
		i.ChatMessageLLMCallsPkey, i.ChatMessageLLMCallsMessageIDIdx, i.ChatMessageLLMCallsProviderConfigIDIdx,
	}
}

type chatMessageLLMCallForeignKeys struct {
	ChatMessageLLMCallsChatMessageLLMCallsMessageIDFkey        foreignKey
	ChatMessageLLMCallsChatMessageLLMCallsProviderConfigIDFkey foreignKey
}

func (f chatMessageLLMCallForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.ChatMessageLLMCallsChatMessageLLMCallsMessageIDFkey, f.ChatMessageLLMCallsChatMessageLLMCallsProviderConfigIDFkey,
	}
}

type chatMessageLLMCallUniques struct{}

func (u chatMessageLLMCallUniques) AsSlice() []constraint {
	return []constraint{}
}

type chatMessageLLMCallChecks struct {
	ChatMessageLLMCallsProviderCheck check
}

func (c chatMessageLLMCallChecks) AsSlice() []check {
	return []check{
		c.ChatMessageLLMCallsProviderCheck,
	}
}
