// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package info

import "github.com/aarondl/opt/null"

var ChatMessageRetrievals = Table[
	chatMessageRetrievalColumns,
	chatMessageRetrievalIndexes,
	chatMessageRetrievalForeignKeys,
	chatMessageRetrievalUniques,
	chatMessageRetrievalChecks,
]{
	Schema: "",
	Name:   "chat_message_retrievals",
	Columns: chatMessageRetrievalColumns{
		MessageID: column{
			Name:      "message_id",
			DBType:    "bigint",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		SnapshotID: column{
			Name:      "snapshot_id",
			DBType:    "integer",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		QueryText: column{
			Name:      "query_text",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Chunks: column{
			Name:      "chunks",
			DBType:    "jsonb",
			Default:   "'[]'::jsonb",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		RetrievedAt: column{
			Name:      "retrieved_at",
			DBType:    "timestamp with time zone",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: chatMessageRetrievalIndexes{
		ChatMessageRetrievalsPkey: index{
			Type: "btree",
			Name: "chat_message_retrievals_pkey",
			Columns: []indexColumn{
				{
					Name:         "message_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "chat_message_retrievals_pkey",
		Columns: []string{"message_id"},
		Comment: "",
	},
	ForeignKeys: chatMessageRetrievalForeignKeys{
		ChatMessageRetrievalsChatMessageRetrievalsMessageIDFkey: foreignKey{
			constraint: constraint{
				Name:    "chat_message_retrievals.chat_message_retrievals_message_id_fkey",
				Columns: []string{"message_id"},
				Comment: "",
			},
			ForeignTable:   "chat_messages",
			ForeignColumns: []string{"id"},
		},
		ChatMessageRetrievalsChatMessageRetrievalsSnapshotIDFkey: foreignKey{
			constraint: constraint{
				Name:    "chat_message_retrievals.chat_message_retrievals_snapshot_id_fkey",
				Columns: []string{"snapshot_id"},
				Comment: "",
			},
			ForeignTable:   "schema_snapshots",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type chatMessageRetrievalColumns struct {
	MessageID   column
	SnapshotID  column
	QueryText   column
	Chunks      column
	RetrievedAt column
}

func (c chatMessageRetrievalColumns) AsSlice() []column {
	return []column{
		c.MessageID, c.SnapshotID, c.QueryText, c.Chunks, c.RetrievedAt,
	}
}

type chatMessageRetrievalIndexes struct {
	ChatMessageRetrievalsPkey index
}

func (i chatMessageRetrievalIndexes) AsSlice() []index {
	return []index{
		i.ChatMessageRetrievalsPkey,
	}
}

type chatMessageRetrievalForeignKeys struct {
	ChatMessageRetrievalsChatMessageRetrievalsMessageIDFkey  foreignKey
	ChatMessageRetrievalsChatMessageRetrievalsSnapshotIDFkey foreignKey
}

func (f chatMessageRetrievalForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.ChatMessageRetrievalsChatMessageRetrievalsMessageIDFkey, f.ChatMessageRetrievalsChatMessageRetrievalsSnapshotIDFkey,
	}
}

type chatMessageRetrievalUniques struct{}

func (u chatMessageRetrievalUniques) AsSlice() []constraint {
	return []constraint{}
}

type chatMessageRetrievalChecks struct{}

func (c chatMessageRetrievalChecks) AsSlice() []check {
	return []check{}
}
