// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package info

import "github.com/aarondl/opt/null"

var ConnectionAccesses = Table[
	connectionAccessColumns,
	connectionAccessIndexes,
	connectionAccessForeignKeys,
	connectionAccessUniques,
	connectionAccessChecks,
]{
	Schema: "",
	Name:   "connection_access",
	Columns: connectionAccessColumns{
		UserID: column{
			Name:      "user_id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ConnectionID: column{
			Name:      "connection_id",
			DBType:    "TEXT",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CanQuery: column{
			Name:      "can_query",
			DBType:    "INTEGER",
			Default:   "1",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		AllowWrites: column{
			Name:      "allow_writes",
			DBType:    "INTEGER",
			Default:   "0",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CanManage: column{
			Name:      "can_manage",
			DBType:    "INTEGER",
			Default:   "0",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		GrantedAt: column{
			Name:      "granted_at",
			DBType:    "TEXT",
			Default:   "strftime('%Y-%m-%d %H:%M:%f','now')",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: connectionAccessIndexes{
		SqliteAutoindexConnectionAccess1: index{
			Type: "pk",
			Name: "sqlite_autoindex_connection_access_1",
			Columns: []indexColumn{
				{
					Name:         "user_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "connection_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
			Partial: false,
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_main_connection_access",
		Columns: []string{"user_id", "connection_id"},
		Comment: "",
	},
	ForeignKeys: connectionAccessForeignKeys{
		FKConnectionAccess0: foreignKey{
			constraint: constraint{
				Name:    "fk_connection_access_0",
				Columns: []string{"connection_id"},
				Comment: "",
			},
			ForeignTable:   "connections",
			ForeignColumns: []string{"id"},
		},
		FKConnectionAccess1: foreignKey{
			constraint: constraint{
				Name:    "fk_connection_access_1",
				Columns: []string{"user_id"},
				Comment: "",
			},
			ForeignTable:   "users",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type connectionAccessColumns struct {
	UserID       column
	ConnectionID column
	CanQuery     column
	AllowWrites  column
	CanManage    column
	GrantedAt    column
}

func (c connectionAccessColumns) AsSlice() []column {
	return []column{
		c.UserID, c.ConnectionID, c.CanQuery, c.AllowWrites, c.CanManage, c.GrantedAt,
	}
}

type connectionAccessIndexes struct {
	SqliteAutoindexConnectionAccess1 index
}

func (i connectionAccessIndexes) AsSlice() []index {
	return []index{
		i.SqliteAutoindexConnectionAccess1,
	}
}

type connectionAccessForeignKeys struct {
	FKConnectionAccess0 foreignKey
	FKConnectionAccess1 foreignKey
}

func (f connectionAccessForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.FKConnectionAccess0, f.FKConnectionAccess1,
	}
}

type connectionAccessUniques struct{}

func (u connectionAccessUniques) AsSlice() []constraint {
	return []constraint{}
}

type connectionAccessChecks struct{}

func (c connectionAccessChecks) AsSlice() []check {
	return []check{}
}
