// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package info

import "github.com/aarondl/opt/null"

var Connections = Table[
	connectionColumns,
	connectionIndexes,
	connectionForeignKeys,
	connectionUniques,
	connectionChecks,
]{
	Schema: "",
	Name:   "connections",
	Columns: connectionColumns{
		ID: column{
			Name:      "id",
			DBType:    "integer",
			Default:   "nextval('datalk.connections_id_seq'::regclass)",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Name: column{
			Name:      "name",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Kind: column{
			Name:      "kind",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		DSN: column{
			Name:      "dsn",
			DBType:    "text",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		IsEnabled: column{
			Name:      "is_enabled",
			DBType:    "boolean",
			Default:   "true",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UserID: column{
			Name:      "user_id",
			DBType:    "integer",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Metadata: column{
			Name:      "metadata",
			DBType:    "jsonb",
			Default:   "'{}'::jsonb",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: connectionIndexes{
		ConnectionsPkey: index{
			Type: "btree",
			Name: "connections_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		ConnectionsNameKey: index{
			Type: "btree",
			Name: "connections_name_key",
			Columns: []indexColumn{
				{
					Name:         "name",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "connections_pkey",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: connectionForeignKeys{
		ConnectionsConnectionsUserIDFkey: foreignKey{
			constraint: constraint{
				Name:    "connections.connections_user_id_fkey",
				Columns: []string{"user_id"},
				Comment: "",
			},
			ForeignTable:   "users",
			ForeignColumns: []string{"id"},
		},
	},
	Uniques: connectionUniques{
		ConnectionsNameKey: constraint{
			Name:    "connections_name_key",
			Columns: []string{"name"},
			Comment: "",
		},
	},
	Checks: connectionChecks{
		ConnectionsKindCheck: check{
			constraint: constraint{
				Name:    "connections_kind_check",
				Columns: []string{"kind"},
				Comment: "",
			},
			Expression: "(kind = ANY (ARRAY['postgres'::text, 'mysql'::text, 'cql'::text]))",
		},
	},
	Comment: "",
}

type connectionColumns struct {
	ID        column
	Name      column
	Kind      column
	DSN       column
	IsEnabled column
	UserID    column
	CreatedAt column
	Metadata  column
}

func (c connectionColumns) AsSlice() []column {
	return []column{
		c.ID, c.Name, c.Kind, c.DSN, c.IsEnabled, c.UserID, c.CreatedAt, c.Metadata,
	}
}

type connectionIndexes struct {
	ConnectionsPkey    index
	ConnectionsNameKey index
}

func (i connectionIndexes) AsSlice() []index {
	return []index{
		i.ConnectionsPkey, i.ConnectionsNameKey,
	}
}

type connectionForeignKeys struct {
	ConnectionsConnectionsUserIDFkey foreignKey
}

func (f connectionForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.ConnectionsConnectionsUserIDFkey,
	}
}

type connectionUniques struct {
	ConnectionsNameKey constraint
}

func (u connectionUniques) AsSlice() []constraint {
	return []constraint{
		u.ConnectionsNameKey,
	}
}

type connectionChecks struct {
	ConnectionsKindCheck check
}

func (c connectionChecks) AsSlice() []check {
	return []check{
		c.ConnectionsKindCheck,
	}
}
