// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package info

import "github.com/aarondl/opt/null"

var LLMProviderModels = Table[
	llmProviderModelColumns,
	llmProviderModelIndexes,
	llmProviderModelForeignKeys,
	llmProviderModelUniques,
	llmProviderModelChecks,
]{
	Schema: "",
	Name:   "llm_provider_models",
	Columns: llmProviderModelColumns{
		ID: column{
			Name:      "id",
			DBType:    "bigint",
			Default:   "nextval('datalk.llm_provider_models_id_seq'::regclass)",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ProviderConfigID: column{
			Name:      "provider_config_id",
			DBType:    "bigint",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Model: column{
			Name:      "model",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		DisplayName: column{
			Name:      "display_name",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ContextWindow: column{
			Name:      "context_window",
			DBType:    "integer",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		SupportsSQL: column{
			Name:      "supports_sql",
			DBType:    "boolean",
			Default:   "true",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		IsEnabled: column{
			Name:      "is_enabled",
			DBType:    "boolean",
			Default:   "true",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		DiscoveredAt: column{
			Name:      "discovered_at",
			DBType:    "timestamp with time zone",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: llmProviderModelIndexes{
		LLMProviderModelsPkey: index{
			Type: "btree",
			Name: "llm_provider_models_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		LLMProviderModelsProviderConfigIDModelKey: index{
			Type: "btree",
			Name: "llm_provider_models_provider_config_id_model_key",
			Columns: []indexColumn{
				{
					Name:         "provider_config_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "model",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false, false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "llm_provider_models_pkey",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: llmProviderModelForeignKeys{
		LLMProviderModelsLLMProviderModelsProviderConfigIDFkey: foreignKey{
			constraint: constraint{
				Name:    "llm_provider_models.llm_provider_models_provider_config_id_fkey",
				Columns: []string{"provider_config_id"},
				Comment: "",
			},
			ForeignTable:   "llm_provider_configs",
			ForeignColumns: []string{"id"},
		},
	},
	Uniques: llmProviderModelUniques{
		LLMProviderModelsProviderConfigIDModelKey: constraint{
			Name:    "llm_provider_models_provider_config_id_model_key",
			Columns: []string{"provider_config_id", "model"},
			Comment: "",
		},
	},

	Comment: "",
}

type llmProviderModelColumns struct {
	ID               column
	ProviderConfigID column
	Model            column
	DisplayName      column
	ContextWindow    column
	SupportsSQL      column
	IsEnabled        column
	DiscoveredAt     column
}

func (c llmProviderModelColumns) AsSlice() []column {
	return []column{
		c.ID, c.ProviderConfigID, c.Model, c.DisplayName, c.ContextWindow, c.SupportsSQL, c.IsEnabled, c.DiscoveredAt,
	}
}

type llmProviderModelIndexes struct {
	LLMProviderModelsPkey                     index
	LLMProviderModelsProviderConfigIDModelKey index
}

func (i llmProviderModelIndexes) AsSlice() []index {
	return []index{
		i.LLMProviderModelsPkey, i.LLMProviderModelsProviderConfigIDModelKey,
	}
}

type llmProviderModelForeignKeys struct {
	LLMProviderModelsLLMProviderModelsProviderConfigIDFkey foreignKey
}

func (f llmProviderModelForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.LLMProviderModelsLLMProviderModelsProviderConfigIDFkey,
	}
}

type llmProviderModelUniques struct {
	LLMProviderModelsProviderConfigIDModelKey constraint
}

func (u llmProviderModelUniques) AsSlice() []constraint {
	return []constraint{
		u.LLMProviderModelsProviderConfigIDModelKey,
	}
}

type llmProviderModelChecks struct{}

func (c llmProviderModelChecks) AsSlice() []check {
	return []check{}
}
