// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"encoding/json"
	"time"
	"unsafe"

	models "github.com/Uncensored-Developer/datalk/apps/backend/db/models"
	"github.com/aarondl/opt/null"
	pgvector "github.com/pgvector/pgvector-go"
	"github.com/stephenafamo/bob/types"
)

type Factory struct {
	baseChatConversationMods     ChatConversationModSlice
	baseChatMessageExecutionMods ChatMessageExecutionModSlice
	baseChatMessageLLMCallMods   ChatMessageLLMCallModSlice
	baseChatMessageRetrievalMods ChatMessageRetrievalModSlice
	baseChatMessageMods          ChatMessageModSlice
	baseConnectionAccessMods     ConnectionAccessModSlice
	baseConnectionMods           ConnectionModSlice
	baseLLMProviderConfigMods    LLMProviderConfigModSlice
	baseLLMProviderModelMods     LLMProviderModelModSlice
	baseOrganizationMods         OrganizationModSlice
	baseRefreshTokenMods         RefreshTokenModSlice
	baseSchemaChunkMods          SchemaChunkModSlice
	baseSchemaEmbeddingJobMods   SchemaEmbeddingJobModSlice
	baseSchemaSnapshotMods       SchemaSnapshotModSlice
	baseUserMods                 UserModSlice
}

func New() *Factory {
	return &Factory{}
}

func (f *Factory) NewChatConversation(mods ...ChatConversationMod) *ChatConversationTemplate {
	return f.NewChatConversationWithContext(context.Background(), mods...)
}

func (f *Factory) NewChatConversationWithContext(ctx context.Context, mods ...ChatConversationMod) *ChatConversationTemplate {
	o := &ChatConversationTemplate{f: f}

	if f != nil {
		f.baseChatConversationMods.Apply(ctx, o)
	}

	ChatConversationModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingChatConversation(ctx context.Context, m *models.ChatConversation) *ChatConversationTemplate {
	visited := make(map[uintptr]struct{})
	ctx = factoryVisitedCtx.WithValue(ctx, visited)
	return f.fromExistingChatConversation(ctx, m)
}

func (f *Factory) fromExistingChatConversation(ctx context.Context, m *models.ChatConversation) *ChatConversationTemplate {
	o := &ChatConversationTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int64 { return m.ID }
	o.UserID = func() int32 { return m.UserID }
	o.ConnectionID = func() int32 { return m.ConnectionID }
	o.Title = func() null.Val[string] { return m.Title }
	o.CreatedAt = func() time.Time { return m.CreatedAt }
	o.UpdatedAt = func() time.Time { return m.UpdatedAt }

	if visited, ok := factoryVisitedCtx.Value(ctx); ok {
		ptr := uintptr(unsafe.Pointer(m))
		if _, seen := visited[ptr]; seen {
			return o
		}
		visited[ptr] = struct{}{}
	}
	if m.R.Connection != nil {
		ChatConversationMods.WithExistingConnection(m.R.Connection).Apply(ctx, o)
	}
	if m.R.User != nil {
		ChatConversationMods.WithExistingUser(m.R.User).Apply(ctx, o)
	}
	if len(m.R.ConversationChatMessages) > 0 {
		ChatConversationMods.AddExistingConversationChatMessages(m.R.ConversationChatMessages...).Apply(ctx, o)
	}

	return o
}

func (f *Factory) NewChatMessageExecution(mods ...ChatMessageExecutionMod) *ChatMessageExecutionTemplate {
	return f.NewChatMessageExecutionWithContext(context.Background(), mods...)
}

func (f *Factory) NewChatMessageExecutionWithContext(ctx context.Context, mods ...ChatMessageExecutionMod) *ChatMessageExecutionTemplate {
	o := &ChatMessageExecutionTemplate{f: f}

	if f != nil {
		f.baseChatMessageExecutionMods.Apply(ctx, o)
	}

	ChatMessageExecutionModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingChatMessageExecution(ctx context.Context, m *models.ChatMessageExecution) *ChatMessageExecutionTemplate {
	visited := make(map[uintptr]struct{})
	ctx = factoryVisitedCtx.WithValue(ctx, visited)
	return f.fromExistingChatMessageExecution(ctx, m)
}

func (f *Factory) fromExistingChatMessageExecution(ctx context.Context, m *models.ChatMessageExecution) *ChatMessageExecutionTemplate {
	o := &ChatMessageExecutionTemplate{f: f, alreadyPersisted: true}

	o.MessageID = func() int64 { return m.MessageID }
	o.ConnectionID = func() int32 { return m.ConnectionID }
	o.DatabaseKind = func() string { return m.DatabaseKind }
	o.GeneratedSQL = func() string { return m.GeneratedSQL }
	o.NormalizedSQL = func() string { return m.NormalizedSQL }
	o.ResultJSON = func() types.JSON[json.RawMessage] { return m.ResultJSON }
	o.ExecutionLatencyMS = func() int32 { return m.ExecutionLatencyMS }
	o.ExecutedAt = func() time.Time { return m.ExecutedAt }

	if visited, ok := factoryVisitedCtx.Value(ctx); ok {
		ptr := uintptr(unsafe.Pointer(m))
		if _, seen := visited[ptr]; seen {
			return o
		}
		visited[ptr] = struct{}{}
	}
	if m.R.Connection != nil {
		ChatMessageExecutionMods.WithExistingConnection(m.R.Connection).Apply(ctx, o)
	}
	if m.R.MessageChatMessage != nil {
		ChatMessageExecutionMods.WithExistingMessageChatMessage(m.R.MessageChatMessage).Apply(ctx, o)
	}

	return o
}

func (f *Factory) NewChatMessageLLMCall(mods ...ChatMessageLLMCallMod) *ChatMessageLLMCallTemplate {
	return f.NewChatMessageLLMCallWithContext(context.Background(), mods...)
}

func (f *Factory) NewChatMessageLLMCallWithContext(ctx context.Context, mods ...ChatMessageLLMCallMod) *ChatMessageLLMCallTemplate {
	o := &ChatMessageLLMCallTemplate{f: f}

	if f != nil {
		f.baseChatMessageLLMCallMods.Apply(ctx, o)
	}

	ChatMessageLLMCallModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingChatMessageLLMCall(ctx context.Context, m *models.ChatMessageLLMCall) *ChatMessageLLMCallTemplate {
	visited := make(map[uintptr]struct{})
	ctx = factoryVisitedCtx.WithValue(ctx, visited)
	return f.fromExistingChatMessageLLMCall(ctx, m)
}

func (f *Factory) fromExistingChatMessageLLMCall(ctx context.Context, m *models.ChatMessageLLMCall) *ChatMessageLLMCallTemplate {
	o := &ChatMessageLLMCallTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int64 { return m.ID }
	o.MessageID = func() int64 { return m.MessageID }
	o.ProviderConfigID = func() int64 { return m.ProviderConfigID }
	o.Provider = func() string { return m.Provider }
	o.Model = func() string { return m.Model }
	o.RequestJSON = func() types.JSON[json.RawMessage] { return m.RequestJSON }
	o.ResponseJSON = func() types.JSON[json.RawMessage] { return m.ResponseJSON }
	o.InputTokens = func() null.Val[int32] { return m.InputTokens }
	o.OutputTokens = func() null.Val[int32] { return m.OutputTokens }
	o.LatencyMS = func() int32 { return m.LatencyMS }
	o.CreatedAt = func() time.Time { return m.CreatedAt }

	if visited, ok := factoryVisitedCtx.Value(ctx); ok {
		ptr := uintptr(unsafe.Pointer(m))
		if _, seen := visited[ptr]; seen {
			return o
		}
		visited[ptr] = struct{}{}
	}
	if m.R.MessageChatMessage != nil {
		ChatMessageLLMCallMods.WithExistingMessageChatMessage(m.R.MessageChatMessage).Apply(ctx, o)
	}
	if m.R.ProviderConfigLLMProviderConfig != nil {
		ChatMessageLLMCallMods.WithExistingProviderConfigLLMProviderConfig(m.R.ProviderConfigLLMProviderConfig).Apply(ctx, o)
	}

	return o
}

func (f *Factory) NewChatMessageRetrieval(mods ...ChatMessageRetrievalMod) *ChatMessageRetrievalTemplate {
	return f.NewChatMessageRetrievalWithContext(context.Background(), mods...)
}

func (f *Factory) NewChatMessageRetrievalWithContext(ctx context.Context, mods ...ChatMessageRetrievalMod) *ChatMessageRetrievalTemplate {
	o := &ChatMessageRetrievalTemplate{f: f}

	if f != nil {
		f.baseChatMessageRetrievalMods.Apply(ctx, o)
	}

	ChatMessageRetrievalModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingChatMessageRetrieval(ctx context.Context, m *models.ChatMessageRetrieval) *ChatMessageRetrievalTemplate {
	visited := make(map[uintptr]struct{})
	ctx = factoryVisitedCtx.WithValue(ctx, visited)
	return f.fromExistingChatMessageRetrieval(ctx, m)
}

func (f *Factory) fromExistingChatMessageRetrieval(ctx context.Context, m *models.ChatMessageRetrieval) *ChatMessageRetrievalTemplate {
	o := &ChatMessageRetrievalTemplate{f: f, alreadyPersisted: true}

	o.MessageID = func() int64 { return m.MessageID }
	o.SnapshotID = func() int32 { return m.SnapshotID }
	o.QueryText = func() string { return m.QueryText }
	o.Chunks = func() types.JSON[json.RawMessage] { return m.Chunks }
	o.RetrievedAt = func() time.Time { return m.RetrievedAt }

	if visited, ok := factoryVisitedCtx.Value(ctx); ok {
		ptr := uintptr(unsafe.Pointer(m))
		if _, seen := visited[ptr]; seen {
			return o
		}
		visited[ptr] = struct{}{}
	}
	if m.R.MessageChatMessage != nil {
		ChatMessageRetrievalMods.WithExistingMessageChatMessage(m.R.MessageChatMessage).Apply(ctx, o)
	}
	if m.R.SnapshotSchemaSnapshot != nil {
		ChatMessageRetrievalMods.WithExistingSnapshotSchemaSnapshot(m.R.SnapshotSchemaSnapshot).Apply(ctx, o)
	}

	return o
}

func (f *Factory) NewChatMessage(mods ...ChatMessageMod) *ChatMessageTemplate {
	return f.NewChatMessageWithContext(context.Background(), mods...)
}

func (f *Factory) NewChatMessageWithContext(ctx context.Context, mods ...ChatMessageMod) *ChatMessageTemplate {
	o := &ChatMessageTemplate{f: f}

	if f != nil {
		f.baseChatMessageMods.Apply(ctx, o)
	}

	ChatMessageModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingChatMessage(ctx context.Context, m *models.ChatMessage) *ChatMessageTemplate {
	visited := make(map[uintptr]struct{})
	ctx = factoryVisitedCtx.WithValue(ctx, visited)
	return f.fromExistingChatMessage(ctx, m)
}

func (f *Factory) fromExistingChatMessage(ctx context.Context, m *models.ChatMessage) *ChatMessageTemplate {
	o := &ChatMessageTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int64 { return m.ID }
	o.ConversationID = func() int64 { return m.ConversationID }
	o.Role = func() string { return m.Role }
	o.Content = func() string { return m.Content }
	o.Provider = func() null.Val[string] { return m.Provider }
	o.Model = func() null.Val[string] { return m.Model }
	o.Status = func() string { return m.Status }
	o.ErrorMessage = func() null.Val[string] { return m.ErrorMessage }
	o.CreatedAt = func() time.Time { return m.CreatedAt }

	if visited, ok := factoryVisitedCtx.Value(ctx); ok {
		ptr := uintptr(unsafe.Pointer(m))
		if _, seen := visited[ptr]; seen {
			return o
		}
		visited[ptr] = struct{}{}
	}
	if m.R.MessageChatMessageExecution != nil {
		ChatMessageMods.WithExistingMessageChatMessageExecution(m.R.MessageChatMessageExecution).Apply(ctx, o)
	}
	if len(m.R.MessageChatMessageLLMCalls) > 0 {
		ChatMessageMods.AddExistingMessageChatMessageLLMCalls(m.R.MessageChatMessageLLMCalls...).Apply(ctx, o)
	}
	if m.R.MessageChatMessageRetrieval != nil {
		ChatMessageMods.WithExistingMessageChatMessageRetrieval(m.R.MessageChatMessageRetrieval).Apply(ctx, o)
	}
	if m.R.ConversationChatConversation != nil {
		ChatMessageMods.WithExistingConversationChatConversation(m.R.ConversationChatConversation).Apply(ctx, o)
	}

	return o
}

func (f *Factory) NewConnectionAccess(mods ...ConnectionAccessMod) *ConnectionAccessTemplate {
	return f.NewConnectionAccessWithContext(context.Background(), mods...)
}

func (f *Factory) NewConnectionAccessWithContext(ctx context.Context, mods ...ConnectionAccessMod) *ConnectionAccessTemplate {
	o := &ConnectionAccessTemplate{f: f}

	if f != nil {
		f.baseConnectionAccessMods.Apply(ctx, o)
	}

	ConnectionAccessModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingConnectionAccess(ctx context.Context, m *models.ConnectionAccess) *ConnectionAccessTemplate {
	visited := make(map[uintptr]struct{})
	ctx = factoryVisitedCtx.WithValue(ctx, visited)
	return f.fromExistingConnectionAccess(ctx, m)
}

func (f *Factory) fromExistingConnectionAccess(ctx context.Context, m *models.ConnectionAccess) *ConnectionAccessTemplate {
	o := &ConnectionAccessTemplate{f: f, alreadyPersisted: true}

	o.UserID = func() int32 { return m.UserID }
	o.ConnectionID = func() int32 { return m.ConnectionID }
	o.CanQuery = func() bool { return m.CanQuery }
	o.AllowWrites = func() bool { return m.AllowWrites }
	o.CanManage = func() bool { return m.CanManage }
	o.GrantedAt = func() time.Time { return m.GrantedAt }

	if visited, ok := factoryVisitedCtx.Value(ctx); ok {
		ptr := uintptr(unsafe.Pointer(m))
		if _, seen := visited[ptr]; seen {
			return o
		}
		visited[ptr] = struct{}{}
	}
	if m.R.Connection != nil {
		ConnectionAccessMods.WithExistingConnection(m.R.Connection).Apply(ctx, o)
	}
	if m.R.User != nil {
		ConnectionAccessMods.WithExistingUser(m.R.User).Apply(ctx, o)
	}

	return o
}

func (f *Factory) NewConnection(mods ...ConnectionMod) *ConnectionTemplate {
	return f.NewConnectionWithContext(context.Background(), mods...)
}

func (f *Factory) NewConnectionWithContext(ctx context.Context, mods ...ConnectionMod) *ConnectionTemplate {
	o := &ConnectionTemplate{f: f}

	if f != nil {
		f.baseConnectionMods.Apply(ctx, o)
	}

	ConnectionModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingConnection(ctx context.Context, m *models.Connection) *ConnectionTemplate {
	visited := make(map[uintptr]struct{})
	ctx = factoryVisitedCtx.WithValue(ctx, visited)
	return f.fromExistingConnection(ctx, m)
}

func (f *Factory) fromExistingConnection(ctx context.Context, m *models.Connection) *ConnectionTemplate {
	o := &ConnectionTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int32 { return m.ID }
	o.Name = func() string { return m.Name }
	o.Kind = func() string { return m.Kind }
	o.DSN = func() null.Val[string] { return m.DSN }
	o.IsEnabled = func() bool { return m.IsEnabled }
	o.UserID = func() int32 { return m.UserID }
	o.CreatedAt = func() time.Time { return m.CreatedAt }
	o.Metadata = func() types.JSON[json.RawMessage] { return m.Metadata }

	if visited, ok := factoryVisitedCtx.Value(ctx); ok {
		ptr := uintptr(unsafe.Pointer(m))
		if _, seen := visited[ptr]; seen {
			return o
		}
		visited[ptr] = struct{}{}
	}
	if len(m.R.ChatConversations) > 0 {
		ConnectionMods.AddExistingChatConversations(m.R.ChatConversations...).Apply(ctx, o)
	}
	if len(m.R.ChatMessageExecutions) > 0 {
		ConnectionMods.AddExistingChatMessageExecutions(m.R.ChatMessageExecutions...).Apply(ctx, o)
	}
	if len(m.R.ConnectionAccesses) > 0 {
		ConnectionMods.AddExistingConnectionAccesses(m.R.ConnectionAccesses...).Apply(ctx, o)
	}
	if m.R.User != nil {
		ConnectionMods.WithExistingUser(m.R.User).Apply(ctx, o)
	}
	if len(m.R.SchemaChunks) > 0 {
		ConnectionMods.AddExistingSchemaChunks(m.R.SchemaChunks...).Apply(ctx, o)
	}
	if len(m.R.SchemaSnapshots) > 0 {
		ConnectionMods.AddExistingSchemaSnapshots(m.R.SchemaSnapshots...).Apply(ctx, o)
	}

	return o
}

func (f *Factory) NewLLMProviderConfig(mods ...LLMProviderConfigMod) *LLMProviderConfigTemplate {
	return f.NewLLMProviderConfigWithContext(context.Background(), mods...)
}

func (f *Factory) NewLLMProviderConfigWithContext(ctx context.Context, mods ...LLMProviderConfigMod) *LLMProviderConfigTemplate {
	o := &LLMProviderConfigTemplate{f: f}

	if f != nil {
		f.baseLLMProviderConfigMods.Apply(ctx, o)
	}

	LLMProviderConfigModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingLLMProviderConfig(ctx context.Context, m *models.LLMProviderConfig) *LLMProviderConfigTemplate {
	visited := make(map[uintptr]struct{})
	ctx = factoryVisitedCtx.WithValue(ctx, visited)
	return f.fromExistingLLMProviderConfig(ctx, m)
}

func (f *Factory) fromExistingLLMProviderConfig(ctx context.Context, m *models.LLMProviderConfig) *LLMProviderConfigTemplate {
	o := &LLMProviderConfigTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int64 { return m.ID }
	o.Provider = func() string { return m.Provider }
	o.DisplayName = func() string { return m.DisplayName }
	o.APIKeyEnc = func() string { return m.APIKeyEnc }
	o.BaseURL = func() null.Val[string] { return m.BaseURL }
	o.IsEnabled = func() bool { return m.IsEnabled }
	o.Metadata = func() types.JSON[json.RawMessage] { return m.Metadata }
	o.CreatedAt = func() time.Time { return m.CreatedAt }
	o.UpdatedAt = func() time.Time { return m.UpdatedAt }

	if visited, ok := factoryVisitedCtx.Value(ctx); ok {
		ptr := uintptr(unsafe.Pointer(m))
		if _, seen := visited[ptr]; seen {
			return o
		}
		visited[ptr] = struct{}{}
	}
	if len(m.R.ProviderConfigChatMessageLLMCalls) > 0 {
		LLMProviderConfigMods.AddExistingProviderConfigChatMessageLLMCalls(m.R.ProviderConfigChatMessageLLMCalls...).Apply(ctx, o)
	}
	if len(m.R.ProviderConfigLLMProviderModels) > 0 {
		LLMProviderConfigMods.AddExistingProviderConfigLLMProviderModels(m.R.ProviderConfigLLMProviderModels...).Apply(ctx, o)
	}

	return o
}

func (f *Factory) NewLLMProviderModel(mods ...LLMProviderModelMod) *LLMProviderModelTemplate {
	return f.NewLLMProviderModelWithContext(context.Background(), mods...)
}

func (f *Factory) NewLLMProviderModelWithContext(ctx context.Context, mods ...LLMProviderModelMod) *LLMProviderModelTemplate {
	o := &LLMProviderModelTemplate{f: f}

	if f != nil {
		f.baseLLMProviderModelMods.Apply(ctx, o)
	}

	LLMProviderModelModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingLLMProviderModel(ctx context.Context, m *models.LLMProviderModel) *LLMProviderModelTemplate {
	visited := make(map[uintptr]struct{})
	ctx = factoryVisitedCtx.WithValue(ctx, visited)
	return f.fromExistingLLMProviderModel(ctx, m)
}

func (f *Factory) fromExistingLLMProviderModel(ctx context.Context, m *models.LLMProviderModel) *LLMProviderModelTemplate {
	o := &LLMProviderModelTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int64 { return m.ID }
	o.ProviderConfigID = func() int64 { return m.ProviderConfigID }
	o.Model = func() string { return m.Model }
	o.DisplayName = func() string { return m.DisplayName }
	o.ContextWindow = func() null.Val[int32] { return m.ContextWindow }
	o.SupportsSQL = func() bool { return m.SupportsSQL }
	o.IsEnabled = func() bool { return m.IsEnabled }
	o.DiscoveredAt = func() time.Time { return m.DiscoveredAt }

	if visited, ok := factoryVisitedCtx.Value(ctx); ok {
		ptr := uintptr(unsafe.Pointer(m))
		if _, seen := visited[ptr]; seen {
			return o
		}
		visited[ptr] = struct{}{}
	}
	if m.R.ProviderConfigLLMProviderConfig != nil {
		LLMProviderModelMods.WithExistingProviderConfigLLMProviderConfig(m.R.ProviderConfigLLMProviderConfig).Apply(ctx, o)
	}

	return o
}

func (f *Factory) NewOrganization(mods ...OrganizationMod) *OrganizationTemplate {
	return f.NewOrganizationWithContext(context.Background(), mods...)
}

func (f *Factory) NewOrganizationWithContext(ctx context.Context, mods ...OrganizationMod) *OrganizationTemplate {
	o := &OrganizationTemplate{f: f}

	if f != nil {
		f.baseOrganizationMods.Apply(ctx, o)
	}

	OrganizationModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingOrganization(ctx context.Context, m *models.Organization) *OrganizationTemplate {
	return f.fromExistingOrganization(ctx, m)
}

func (f *Factory) fromExistingOrganization(ctx context.Context, m *models.Organization) *OrganizationTemplate {
	o := &OrganizationTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int32 { return m.ID }
	o.Name = func() string { return m.Name }
	o.CreatedAt = func() time.Time { return m.CreatedAt }
	o.Singleton = func() bool { return m.Singleton }

	return o
}

func (f *Factory) NewRefreshToken(mods ...RefreshTokenMod) *RefreshTokenTemplate {
	return f.NewRefreshTokenWithContext(context.Background(), mods...)
}

func (f *Factory) NewRefreshTokenWithContext(ctx context.Context, mods ...RefreshTokenMod) *RefreshTokenTemplate {
	o := &RefreshTokenTemplate{f: f}

	if f != nil {
		f.baseRefreshTokenMods.Apply(ctx, o)
	}

	RefreshTokenModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingRefreshToken(ctx context.Context, m *models.RefreshToken) *RefreshTokenTemplate {
	visited := make(map[uintptr]struct{})
	ctx = factoryVisitedCtx.WithValue(ctx, visited)
	return f.fromExistingRefreshToken(ctx, m)
}

func (f *Factory) fromExistingRefreshToken(ctx context.Context, m *models.RefreshToken) *RefreshTokenTemplate {
	o := &RefreshTokenTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int32 { return m.ID }
	o.UserID = func() int32 { return m.UserID }
	o.TokenHash = func() string { return m.TokenHash }
	o.ExpiresAt = func() time.Time { return m.ExpiresAt }
	o.RevokedAt = func() null.Val[time.Time] { return m.RevokedAt }
	o.CreatedAt = func() time.Time { return m.CreatedAt }

	if visited, ok := factoryVisitedCtx.Value(ctx); ok {
		ptr := uintptr(unsafe.Pointer(m))
		if _, seen := visited[ptr]; seen {
			return o
		}
		visited[ptr] = struct{}{}
	}
	if m.R.User != nil {
		RefreshTokenMods.WithExistingUser(m.R.User).Apply(ctx, o)
	}

	return o
}

func (f *Factory) NewSchemaChunk(mods ...SchemaChunkMod) *SchemaChunkTemplate {
	return f.NewSchemaChunkWithContext(context.Background(), mods...)
}

func (f *Factory) NewSchemaChunkWithContext(ctx context.Context, mods ...SchemaChunkMod) *SchemaChunkTemplate {
	o := &SchemaChunkTemplate{f: f}

	if f != nil {
		f.baseSchemaChunkMods.Apply(ctx, o)
	}

	SchemaChunkModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingSchemaChunk(ctx context.Context, m *models.SchemaChunk) *SchemaChunkTemplate {
	visited := make(map[uintptr]struct{})
	ctx = factoryVisitedCtx.WithValue(ctx, visited)
	return f.fromExistingSchemaChunk(ctx, m)
}

func (f *Factory) fromExistingSchemaChunk(ctx context.Context, m *models.SchemaChunk) *SchemaChunkTemplate {
	o := &SchemaChunkTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int64 { return m.ID }
	o.SnapshotID = func() int32 { return m.SnapshotID }
	o.ConnectionID = func() int32 { return m.ConnectionID }
	o.ObjectType = func() string { return m.ObjectType }
	o.ObjectName = func() string { return m.ObjectName }
	o.SchemaJSON = func() types.JSON[json.RawMessage] { return m.SchemaJSON }
	o.Content = func() string { return m.Content }
	o.Embedding = func() null.Val[pgvector.Vector] { return m.Embedding }
	o.Metadata = func() types.JSON[json.RawMessage] { return m.Metadata }
	o.CreatedAt = func() time.Time { return m.CreatedAt }

	if visited, ok := factoryVisitedCtx.Value(ctx); ok {
		ptr := uintptr(unsafe.Pointer(m))
		if _, seen := visited[ptr]; seen {
			return o
		}
		visited[ptr] = struct{}{}
	}
	if m.R.Connection != nil {
		SchemaChunkMods.WithExistingConnection(m.R.Connection).Apply(ctx, o)
	}
	if m.R.SnapshotSchemaSnapshot != nil {
		SchemaChunkMods.WithExistingSnapshotSchemaSnapshot(m.R.SnapshotSchemaSnapshot).Apply(ctx, o)
	}

	return o
}

func (f *Factory) NewSchemaEmbeddingJob(mods ...SchemaEmbeddingJobMod) *SchemaEmbeddingJobTemplate {
	return f.NewSchemaEmbeddingJobWithContext(context.Background(), mods...)
}

func (f *Factory) NewSchemaEmbeddingJobWithContext(ctx context.Context, mods ...SchemaEmbeddingJobMod) *SchemaEmbeddingJobTemplate {
	o := &SchemaEmbeddingJobTemplate{f: f}

	if f != nil {
		f.baseSchemaEmbeddingJobMods.Apply(ctx, o)
	}

	SchemaEmbeddingJobModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingSchemaEmbeddingJob(ctx context.Context, m *models.SchemaEmbeddingJob) *SchemaEmbeddingJobTemplate {
	visited := make(map[uintptr]struct{})
	ctx = factoryVisitedCtx.WithValue(ctx, visited)
	return f.fromExistingSchemaEmbeddingJob(ctx, m)
}

func (f *Factory) fromExistingSchemaEmbeddingJob(ctx context.Context, m *models.SchemaEmbeddingJob) *SchemaEmbeddingJobTemplate {
	o := &SchemaEmbeddingJobTemplate{f: f, alreadyPersisted: true}

	o.SnapshotID = func() int32 { return m.SnapshotID }
	o.Status = func() string { return m.Status }
	o.ErrorMessage = func() null.Val[string] { return m.ErrorMessage }
	o.RetryCount = func() int32 { return m.RetryCount }
	o.StartedAt = func() time.Time { return m.StartedAt }
	o.CompletedAt = func() null.Val[time.Time] { return m.CompletedAt }

	if visited, ok := factoryVisitedCtx.Value(ctx); ok {
		ptr := uintptr(unsafe.Pointer(m))
		if _, seen := visited[ptr]; seen {
			return o
		}
		visited[ptr] = struct{}{}
	}
	if m.R.SnapshotSchemaSnapshot != nil {
		SchemaEmbeddingJobMods.WithExistingSnapshotSchemaSnapshot(m.R.SnapshotSchemaSnapshot).Apply(ctx, o)
	}

	return o
}

func (f *Factory) NewSchemaSnapshot(mods ...SchemaSnapshotMod) *SchemaSnapshotTemplate {
	return f.NewSchemaSnapshotWithContext(context.Background(), mods...)
}

func (f *Factory) NewSchemaSnapshotWithContext(ctx context.Context, mods ...SchemaSnapshotMod) *SchemaSnapshotTemplate {
	o := &SchemaSnapshotTemplate{f: f}

	if f != nil {
		f.baseSchemaSnapshotMods.Apply(ctx, o)
	}

	SchemaSnapshotModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingSchemaSnapshot(ctx context.Context, m *models.SchemaSnapshot) *SchemaSnapshotTemplate {
	visited := make(map[uintptr]struct{})
	ctx = factoryVisitedCtx.WithValue(ctx, visited)
	return f.fromExistingSchemaSnapshot(ctx, m)
}

func (f *Factory) fromExistingSchemaSnapshot(ctx context.Context, m *models.SchemaSnapshot) *SchemaSnapshotTemplate {
	o := &SchemaSnapshotTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int32 { return m.ID }
	o.ConnectionID = func() int32 { return m.ConnectionID }
	o.SchemaHash = func() string { return m.SchemaHash }
	o.SliceJSON = func() types.JSON[json.RawMessage] { return m.SliceJSON }
	o.IntrospectedAt = func() time.Time { return m.IntrospectedAt }

	if visited, ok := factoryVisitedCtx.Value(ctx); ok {
		ptr := uintptr(unsafe.Pointer(m))
		if _, seen := visited[ptr]; seen {
			return o
		}
		visited[ptr] = struct{}{}
	}
	if len(m.R.SnapshotChatMessageRetrievals) > 0 {
		SchemaSnapshotMods.AddExistingSnapshotChatMessageRetrievals(m.R.SnapshotChatMessageRetrievals...).Apply(ctx, o)
	}
	if len(m.R.SnapshotSchemaChunks) > 0 {
		SchemaSnapshotMods.AddExistingSnapshotSchemaChunks(m.R.SnapshotSchemaChunks...).Apply(ctx, o)
	}
	if m.R.SnapshotSchemaEmbeddingJob != nil {
		SchemaSnapshotMods.WithExistingSnapshotSchemaEmbeddingJob(m.R.SnapshotSchemaEmbeddingJob).Apply(ctx, o)
	}
	if m.R.Connection != nil {
		SchemaSnapshotMods.WithExistingConnection(m.R.Connection).Apply(ctx, o)
	}

	return o
}

func (f *Factory) NewUser(mods ...UserMod) *UserTemplate {
	return f.NewUserWithContext(context.Background(), mods...)
}

func (f *Factory) NewUserWithContext(ctx context.Context, mods ...UserMod) *UserTemplate {
	o := &UserTemplate{f: f}

	if f != nil {
		f.baseUserMods.Apply(ctx, o)
	}

	UserModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingUser(ctx context.Context, m *models.User) *UserTemplate {
	visited := make(map[uintptr]struct{})
	ctx = factoryVisitedCtx.WithValue(ctx, visited)
	return f.fromExistingUser(ctx, m)
}

func (f *Factory) fromExistingUser(ctx context.Context, m *models.User) *UserTemplate {
	o := &UserTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int32 { return m.ID }
	o.Email = func() string { return m.Email }
	o.Name = func() string { return m.Name }
	o.PasswordHash = func() string { return m.PasswordHash }
	o.Role = func() string { return m.Role }
	o.IsActive = func() bool { return m.IsActive }
	o.LastLoginAt = func() null.Val[time.Time] { return m.LastLoginAt }
	o.CreatedAt = func() time.Time { return m.CreatedAt }
	o.MustChangePassword = func() bool { return m.MustChangePassword }
	o.UpdatedAt = func() time.Time { return m.UpdatedAt }

	if visited, ok := factoryVisitedCtx.Value(ctx); ok {
		ptr := uintptr(unsafe.Pointer(m))
		if _, seen := visited[ptr]; seen {
			return o
		}
		visited[ptr] = struct{}{}
	}
	if len(m.R.ChatConversations) > 0 {
		UserMods.AddExistingChatConversations(m.R.ChatConversations...).Apply(ctx, o)
	}
	if len(m.R.ConnectionAccesses) > 0 {
		UserMods.AddExistingConnectionAccesses(m.R.ConnectionAccesses...).Apply(ctx, o)
	}
	if len(m.R.Connections) > 0 {
		UserMods.AddExistingConnections(m.R.Connections...).Apply(ctx, o)
	}
	if len(m.R.RefreshTokens) > 0 {
		UserMods.AddExistingRefreshTokens(m.R.RefreshTokens...).Apply(ctx, o)
	}

	return o
}

func (f *Factory) ClearBaseChatConversationMods() {
	f.baseChatConversationMods = nil
}

func (f *Factory) AddBaseChatConversationMod(mods ...ChatConversationMod) {
	f.baseChatConversationMods = append(f.baseChatConversationMods, mods...)
}

func (f *Factory) ClearBaseChatMessageExecutionMods() {
	f.baseChatMessageExecutionMods = nil
}

func (f *Factory) AddBaseChatMessageExecutionMod(mods ...ChatMessageExecutionMod) {
	f.baseChatMessageExecutionMods = append(f.baseChatMessageExecutionMods, mods...)
}

func (f *Factory) ClearBaseChatMessageLLMCallMods() {
	f.baseChatMessageLLMCallMods = nil
}

func (f *Factory) AddBaseChatMessageLLMCallMod(mods ...ChatMessageLLMCallMod) {
	f.baseChatMessageLLMCallMods = append(f.baseChatMessageLLMCallMods, mods...)
}

func (f *Factory) ClearBaseChatMessageRetrievalMods() {
	f.baseChatMessageRetrievalMods = nil
}

func (f *Factory) AddBaseChatMessageRetrievalMod(mods ...ChatMessageRetrievalMod) {
	f.baseChatMessageRetrievalMods = append(f.baseChatMessageRetrievalMods, mods...)
}

func (f *Factory) ClearBaseChatMessageMods() {
	f.baseChatMessageMods = nil
}

func (f *Factory) AddBaseChatMessageMod(mods ...ChatMessageMod) {
	f.baseChatMessageMods = append(f.baseChatMessageMods, mods...)
}

func (f *Factory) ClearBaseConnectionAccessMods() {
	f.baseConnectionAccessMods = nil
}

func (f *Factory) AddBaseConnectionAccessMod(mods ...ConnectionAccessMod) {
	f.baseConnectionAccessMods = append(f.baseConnectionAccessMods, mods...)
}

func (f *Factory) ClearBaseConnectionMods() {
	f.baseConnectionMods = nil
}

func (f *Factory) AddBaseConnectionMod(mods ...ConnectionMod) {
	f.baseConnectionMods = append(f.baseConnectionMods, mods...)
}

func (f *Factory) ClearBaseLLMProviderConfigMods() {
	f.baseLLMProviderConfigMods = nil
}

func (f *Factory) AddBaseLLMProviderConfigMod(mods ...LLMProviderConfigMod) {
	f.baseLLMProviderConfigMods = append(f.baseLLMProviderConfigMods, mods...)
}

func (f *Factory) ClearBaseLLMProviderModelMods() {
	f.baseLLMProviderModelMods = nil
}

func (f *Factory) AddBaseLLMProviderModelMod(mods ...LLMProviderModelMod) {
	f.baseLLMProviderModelMods = append(f.baseLLMProviderModelMods, mods...)
}

func (f *Factory) ClearBaseOrganizationMods() {
	f.baseOrganizationMods = nil
}

func (f *Factory) AddBaseOrganizationMod(mods ...OrganizationMod) {
	f.baseOrganizationMods = append(f.baseOrganizationMods, mods...)
}

func (f *Factory) ClearBaseRefreshTokenMods() {
	f.baseRefreshTokenMods = nil
}

func (f *Factory) AddBaseRefreshTokenMod(mods ...RefreshTokenMod) {
	f.baseRefreshTokenMods = append(f.baseRefreshTokenMods, mods...)
}

func (f *Factory) ClearBaseSchemaChunkMods() {
	f.baseSchemaChunkMods = nil
}

func (f *Factory) AddBaseSchemaChunkMod(mods ...SchemaChunkMod) {
	f.baseSchemaChunkMods = append(f.baseSchemaChunkMods, mods...)
}

func (f *Factory) ClearBaseSchemaEmbeddingJobMods() {
	f.baseSchemaEmbeddingJobMods = nil
}

func (f *Factory) AddBaseSchemaEmbeddingJobMod(mods ...SchemaEmbeddingJobMod) {
	f.baseSchemaEmbeddingJobMods = append(f.baseSchemaEmbeddingJobMods, mods...)
}

func (f *Factory) ClearBaseSchemaSnapshotMods() {
	f.baseSchemaSnapshotMods = nil
}

func (f *Factory) AddBaseSchemaSnapshotMod(mods ...SchemaSnapshotMod) {
	f.baseSchemaSnapshotMods = append(f.baseSchemaSnapshotMods, mods...)
}

func (f *Factory) ClearBaseUserMods() {
	f.baseUserMods = nil
}

func (f *Factory) AddBaseUserMod(mods ...UserMod) {
	f.baseUserMods = append(f.baseUserMods, mods...)
}
