// Code generated by BobGen sqlite v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"

	models "github.com/Uncensored-Developer/datalk/apps/backend/db/models"
	"github.com/aarondl/opt/null"
)

type Factory struct {
	baseConnectionAccessMods ConnectionAccessModSlice
	baseConnectionMods       ConnectionModSlice
	baseOrganizationMods     OrganizationModSlice
	baseUserMods             UserModSlice
}

func New() *Factory {
	return &Factory{}
}

func (f *Factory) NewConnectionAccess(mods ...ConnectionAccessMod) *ConnectionAccessTemplate {
	return f.NewConnectionAccessWithContext(context.Background(), mods...)
}

func (f *Factory) NewConnectionAccessWithContext(ctx context.Context, mods ...ConnectionAccessMod) *ConnectionAccessTemplate {
	o := &ConnectionAccessTemplate{f: f}

	if f != nil {
		f.baseConnectionAccessMods.Apply(ctx, o)
	}

	ConnectionAccessModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingConnectionAccess(m *models.ConnectionAccess) *ConnectionAccessTemplate {
	o := &ConnectionAccessTemplate{f: f, alreadyPersisted: true}

	o.UserID = func() int64 { return m.UserID }
	o.ConnectionID = func() int64 { return m.ConnectionID }
	o.CanQuery = func() int64 { return m.CanQuery }
	o.AllowWrites = func() int64 { return m.AllowWrites }
	o.CanManage = func() int64 { return m.CanManage }
	o.GrantedAt = func() string { return m.GrantedAt }

	ctx := context.Background()
	if m.R.Connection != nil {
		ConnectionAccessMods.WithExistingConnection(m.R.Connection).Apply(ctx, o)
	}
	if m.R.User != nil {
		ConnectionAccessMods.WithExistingUser(m.R.User).Apply(ctx, o)
	}

	return o
}

func (f *Factory) NewConnection(mods ...ConnectionMod) *ConnectionTemplate {
	return f.NewConnectionWithContext(context.Background(), mods...)
}

func (f *Factory) NewConnectionWithContext(ctx context.Context, mods ...ConnectionMod) *ConnectionTemplate {
	o := &ConnectionTemplate{f: f}

	if f != nil {
		f.baseConnectionMods.Apply(ctx, o)
	}

	ConnectionModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingConnection(m *models.Connection) *ConnectionTemplate {
	o := &ConnectionTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int64 { return m.ID }
	o.Name = func() string { return m.Name }
	o.Kind = func() string { return m.Kind }
	o.DSN = func() null.Val[string] { return m.DSN }
	o.IsEnabled = func() int64 { return m.IsEnabled }
	o.UserID = func() null.Val[int64] { return m.UserID }
	o.CreatedAt = func() string { return m.CreatedAt }

	ctx := context.Background()
	if len(m.R.ConnectionAccesses) > 0 {
		ConnectionMods.AddExistingConnectionAccesses(m.R.ConnectionAccesses...).Apply(ctx, o)
	}
	if m.R.User != nil {
		ConnectionMods.WithExistingUser(m.R.User).Apply(ctx, o)
	}

	return o
}

func (f *Factory) NewOrganization(mods ...OrganizationMod) *OrganizationTemplate {
	return f.NewOrganizationWithContext(context.Background(), mods...)
}

func (f *Factory) NewOrganizationWithContext(ctx context.Context, mods ...OrganizationMod) *OrganizationTemplate {
	o := &OrganizationTemplate{f: f}

	if f != nil {
		f.baseOrganizationMods.Apply(ctx, o)
	}

	OrganizationModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingOrganization(m *models.Organization) *OrganizationTemplate {
	o := &OrganizationTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int64 { return m.ID }
	o.Name = func() string { return m.Name }
	o.CreatedAt = func() string { return m.CreatedAt }
	o.Singleton = func() int64 { return m.Singleton }

	return o
}

func (f *Factory) NewUser(mods ...UserMod) *UserTemplate {
	return f.NewUserWithContext(context.Background(), mods...)
}

func (f *Factory) NewUserWithContext(ctx context.Context, mods ...UserMod) *UserTemplate {
	o := &UserTemplate{f: f}

	if f != nil {
		f.baseUserMods.Apply(ctx, o)
	}

	UserModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingUser(m *models.User) *UserTemplate {
	o := &UserTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int64 { return m.ID }
	o.Email = func() string { return m.Email }
	o.Name = func() string { return m.Name }
	o.PasswordHash = func() string { return m.PasswordHash }
	o.Role = func() string { return m.Role }
	o.IsActive = func() int64 { return m.IsActive }
	o.LastLoginAt = func() null.Val[string] { return m.LastLoginAt }
	o.CreatedAt = func() string { return m.CreatedAt }

	ctx := context.Background()
	if len(m.R.ConnectionAccesses) > 0 {
		UserMods.AddExistingConnectionAccesses(m.R.ConnectionAccesses...).Apply(ctx, o)
	}
	if len(m.R.Connections) > 0 {
		UserMods.AddExistingConnections(m.R.Connections...).Apply(ctx, o)
	}

	return o
}

func (f *Factory) ClearBaseConnectionAccessMods() {
	f.baseConnectionAccessMods = nil
}

func (f *Factory) AddBaseConnectionAccessMod(mods ...ConnectionAccessMod) {
	f.baseConnectionAccessMods = append(f.baseConnectionAccessMods, mods...)
}

func (f *Factory) ClearBaseConnectionMods() {
	f.baseConnectionMods = nil
}

func (f *Factory) AddBaseConnectionMod(mods ...ConnectionMod) {
	f.baseConnectionMods = append(f.baseConnectionMods, mods...)
}

func (f *Factory) ClearBaseOrganizationMods() {
	f.baseOrganizationMods = nil
}

func (f *Factory) AddBaseOrganizationMod(mods ...OrganizationMod) {
	f.baseOrganizationMods = append(f.baseOrganizationMods, mods...)
}

func (f *Factory) ClearBaseUserMods() {
	f.baseUserMods = nil
}

func (f *Factory) AddBaseUserMod(mods ...UserMod) {
	f.baseUserMods = append(f.baseUserMods, mods...)
}
