// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import "context"

type contextKey string

var (
	// Relationship Contexts for connection_access
	connectionAccessWithParentsCascadingCtx = newContextual[bool]("connectionAccessWithParentsCascading")
	connectionAccessRelConnectionCtx        = newContextual[bool]("connection_access.connections.connection_access.connection_access_connection_id_fkey")
	connectionAccessRelUserCtx              = newContextual[bool]("connection_access.users.connection_access.connection_access_user_id_fkey")

	// Relationship Contexts for connections
	connectionWithParentsCascadingCtx  = newContextual[bool]("connectionWithParentsCascading")
	connectionRelConnectionAccessesCtx = newContextual[bool]("connection_access.connections.connection_access.connection_access_connection_id_fkey")
	connectionRelUserCtx               = newContextual[bool]("connections.users.connections.connections_user_id_fkey")

	// Relationship Contexts for organization
	organizationWithParentsCascadingCtx = newContextual[bool]("organizationWithParentsCascading")

	// Relationship Contexts for users
	userWithParentsCascadingCtx  = newContextual[bool]("userWithParentsCascading")
	userRelConnectionAccessesCtx = newContextual[bool]("connection_access.users.connection_access.connection_access_user_id_fkey")
	userRelConnectionsCtx        = newContextual[bool]("connections.users.connections.connections_user_id_fkey")
)

// Contextual is a convienience wrapper around context.WithValue and context.Value
type contextual[V any] struct {
	key contextKey
}

func newContextual[V any](key string) contextual[V] {
	return contextual[V]{key: contextKey(key)}
}

func (k contextual[V]) WithValue(ctx context.Context, val V) context.Context {
	return context.WithValue(ctx, k.key, val)
}

func (k contextual[V]) Value(ctx context.Context) (V, bool) {
	v, ok := ctx.Value(k.key).(V)
	return v, ok
}
