// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	models "github.com/Uncensored-Developer/datalk/apps/backend/db/models"
	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
)

type ChatMessageMod interface {
	Apply(context.Context, *ChatMessageTemplate)
}

type ChatMessageModFunc func(context.Context, *ChatMessageTemplate)

func (f ChatMessageModFunc) Apply(ctx context.Context, n *ChatMessageTemplate) {
	f(ctx, n)
}

type ChatMessageModSlice []ChatMessageMod

func (mods ChatMessageModSlice) Apply(ctx context.Context, n *ChatMessageTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// ChatMessageTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type ChatMessageTemplate struct {
	ID             func() int64
	ConversationID func() int64
	Role           func() string
	Content        func() string
	Provider       func() null.Val[string]
	Model          func() null.Val[string]
	Status         func() string
	ErrorMessage   func() null.Val[string]
	CreatedAt      func() time.Time

	r chatMessageR
	f *Factory

	alreadyPersisted bool
}

type chatMessageR struct {
	MessageChatMessageExecution  *chatMessageRMessageChatMessageExecutionR
	MessageChatMessageLLMCalls   []*chatMessageRMessageChatMessageLLMCallsR
	MessageChatMessageRetrieval  *chatMessageRMessageChatMessageRetrievalR
	ConversationChatConversation *chatMessageRConversationChatConversationR
}

type chatMessageRMessageChatMessageExecutionR struct {
	o *ChatMessageExecutionTemplate
}
type chatMessageRMessageChatMessageLLMCallsR struct {
	number int
	o      *ChatMessageLLMCallTemplate
}
type chatMessageRMessageChatMessageRetrievalR struct {
	o *ChatMessageRetrievalTemplate
}
type chatMessageRConversationChatConversationR struct {
	o *ChatConversationTemplate
}

// Apply mods to the ChatMessageTemplate
func (o *ChatMessageTemplate) Apply(ctx context.Context, mods ...ChatMessageMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.ChatMessage
// according to the relationships in the template. Nothing is inserted into the db
func (t ChatMessageTemplate) setModelRels(o *models.ChatMessage) {
	if t.r.MessageChatMessageExecution != nil {
		rel := t.r.MessageChatMessageExecution.o.Build()
		rel.MessageID = o.ID // h2
		o.R.MessageChatMessageExecution = rel
		o.R.Loaded.MessageChatMessageExecution = true
	}

	if t.r.MessageChatMessageLLMCalls != nil {
		rel := models.ChatMessageLLMCallSlice{}
		for _, r := range t.r.MessageChatMessageLLMCalls {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.MessageID = o.ID // h2
			}
			rel = append(rel, related...)
		}
		o.R.MessageChatMessageLLMCalls = rel
		o.R.Loaded.MessageChatMessageLLMCalls = true
	}

	if t.r.MessageChatMessageRetrieval != nil {
		rel := t.r.MessageChatMessageRetrieval.o.Build()
		rel.MessageID = o.ID // h2
		o.R.MessageChatMessageRetrieval = rel
		o.R.Loaded.MessageChatMessageRetrieval = true
	}

	if t.r.ConversationChatConversation != nil {
		rel := t.r.ConversationChatConversation.o.Build()
		o.ConversationID = rel.ID // h2
		o.R.ConversationChatConversation = rel
		o.R.Loaded.ConversationChatConversation = true
	}
}

// BuildSetter returns an *models.ChatMessageSetter
// this does nothing with the relationship templates
func (o ChatMessageTemplate) BuildSetter() *models.ChatMessageSetter {
	m := &models.ChatMessageSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.ConversationID != nil {
		val := o.ConversationID()
		m.ConversationID = omit.From(val)
	}
	if o.Role != nil {
		val := o.Role()
		m.Role = omit.From(val)
	}
	if o.Content != nil {
		val := o.Content()
		m.Content = omit.From(val)
	}
	if o.Provider != nil {
		val := o.Provider()
		m.Provider = omitnull.FromNull(val)
	}
	if o.Model != nil {
		val := o.Model()
		m.Model = omitnull.FromNull(val)
	}
	if o.Status != nil {
		val := o.Status()
		m.Status = omit.From(val)
	}
	if o.ErrorMessage != nil {
		val := o.ErrorMessage()
		m.ErrorMessage = omitnull.FromNull(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.ChatMessageSetter
// this does nothing with the relationship templates
func (o ChatMessageTemplate) BuildManySetter(number int) []*models.ChatMessageSetter {
	m := make([]*models.ChatMessageSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.ChatMessage
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ChatMessageTemplate.Create
func (o ChatMessageTemplate) Build() *models.ChatMessage {
	m := &models.ChatMessage{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.ConversationID != nil {
		m.ConversationID = o.ConversationID()
	}
	if o.Role != nil {
		m.Role = o.Role()
	}
	if o.Content != nil {
		m.Content = o.Content()
	}
	if o.Provider != nil {
		m.Provider = o.Provider()
	}
	if o.Model != nil {
		m.Model = o.Model()
	}
	if o.Status != nil {
		m.Status = o.Status()
	}
	if o.ErrorMessage != nil {
		m.ErrorMessage = o.ErrorMessage()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.ChatMessageSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ChatMessageTemplate.CreateMany
func (o ChatMessageTemplate) BuildMany(number int) models.ChatMessageSlice {
	m := make(models.ChatMessageSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableChatMessage(m *models.ChatMessageSetter) {
	if !(m.ConversationID.IsValue()) {
		val := random_int64(nil)
		m.ConversationID = omit.From(val)
	}
	if !(m.Role.IsValue()) {
		val := random_string(nil)
		m.Role = omit.From(val)
	}
	if !(m.Content.IsValue()) {
		val := random_string(nil)
		m.Content = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.ChatMessage
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *ChatMessageTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.ChatMessage) error {
	var err error

	isMessageChatMessageExecutionDone, _ := chatMessageRelMessageChatMessageExecutionCtx.Value(ctx)
	if !isMessageChatMessageExecutionDone && o.r.MessageChatMessageExecution != nil {
		ctx = chatMessageRelMessageChatMessageExecutionCtx.WithValue(ctx, true)
		if o.r.MessageChatMessageExecution.o.alreadyPersisted {
			m.R.MessageChatMessageExecution = o.r.MessageChatMessageExecution.o.Build()
			m.R.Loaded.MessageChatMessageExecution = true
		} else {
			var rel0 *models.ChatMessageExecution
			rel0, err = o.r.MessageChatMessageExecution.o.Create(ctx, exec)
			if err != nil {
				return err
			}
			err = m.AttachMessageChatMessageExecution(ctx, exec, rel0)
			if err != nil {
				return err
			}
		}

	}

	isMessageChatMessageLLMCallsDone, _ := chatMessageRelMessageChatMessageLLMCallsCtx.Value(ctx)
	if !isMessageChatMessageLLMCallsDone && o.r.MessageChatMessageLLMCalls != nil {
		ctx = chatMessageRelMessageChatMessageLLMCallsCtx.WithValue(ctx, true)
		for _, r := range o.r.MessageChatMessageLLMCalls {
			if r.o.alreadyPersisted {
				m.R.MessageChatMessageLLMCalls = append(m.R.MessageChatMessageLLMCalls, r.o.Build())
			} else {
				rel1, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachMessageChatMessageLLMCalls(ctx, exec, rel1...)
				if err != nil {
					return err
				}
			}
		}
	}

	isMessageChatMessageRetrievalDone, _ := chatMessageRelMessageChatMessageRetrievalCtx.Value(ctx)
	if !isMessageChatMessageRetrievalDone && o.r.MessageChatMessageRetrieval != nil {
		ctx = chatMessageRelMessageChatMessageRetrievalCtx.WithValue(ctx, true)
		if o.r.MessageChatMessageRetrieval.o.alreadyPersisted {
			m.R.MessageChatMessageRetrieval = o.r.MessageChatMessageRetrieval.o.Build()
			m.R.Loaded.MessageChatMessageRetrieval = true
		} else {
			var rel2 *models.ChatMessageRetrieval
			rel2, err = o.r.MessageChatMessageRetrieval.o.Create(ctx, exec)
			if err != nil {
				return err
			}
			err = m.AttachMessageChatMessageRetrieval(ctx, exec, rel2)
			if err != nil {
				return err
			}
		}

	}

	return err
}

// Create builds a chatMessage and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *ChatMessageTemplate) Create(ctx context.Context, exec bob.Executor) (*models.ChatMessage, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableChatMessage(opt)

	// Retrieve ancestor models from context to avoid duplicate parent creation.
	// Parents are keyed by "parent_table:child_table:child_rel_name".
	// This works regardless of NoBackReferencing since it only uses child-side metadata.
	mInCreation, _ := modelsInCreationCtx.Value(ctx)

	var rel3 *models.ChatConversation

	if o.r.ConversationChatConversation == nil {
		if parentModel, found := mInCreation["chat_conversations:chat_messages:chat_messages.chat_messages_conversation_id_fkey"]; found {
			if pModel, ok := parentModel.(*models.ChatConversation); ok {
				rel3 = pModel
			}
		}
	}

	if rel3 == nil {
		if o.r.ConversationChatConversation == nil {
			ChatMessageMods.WithNewConversationChatConversation().Apply(ctx, o)
		}

		if o.r.ConversationChatConversation.o.alreadyPersisted {
			rel3 = o.r.ConversationChatConversation.o.Build()
		} else {
			rel3, err = o.r.ConversationChatConversation.o.Create(ctx, exec)
			if err != nil {
				return nil, err
			}
		}
	}

	opt.ConversationID = omit.From(rel3.ID)

	m, err := models.ChatMessages.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	// Store this model in context for child creates.
	// Key format: "parent_table:child_table:child_rel_name" where child_rel_name is the FK name.
	// We store an entry for every relationship pointing TO this table (where this table is the parent).
	// This works regardless of NoBackReferencing since keys use child-side metadata.
	newMInCreation := make(map[string]any, len(mInCreation)+1)
	for k, v := range mInCreation {
		newMInCreation[k] = v
	}
	newMInCreation["chat_messages:chat_message_executions:chat_message_executions.chat_message_executions_message_id_fkey"] = m
	newMInCreation["chat_messages:chat_message_llm_calls:chat_message_llm_calls.chat_message_llm_calls_message_id_fkey"] = m
	newMInCreation["chat_messages:chat_message_retrievals:chat_message_retrievals.chat_message_retrievals_message_id_fkey"] = m

	ctx = modelsInCreationCtx.WithValue(ctx, newMInCreation)

	m.R.ConversationChatConversation = rel3
	m.R.Loaded.ConversationChatConversation = true

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a chatMessage and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *ChatMessageTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.ChatMessage {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a chatMessage and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *ChatMessageTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.ChatMessage {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple chatMessages and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o ChatMessageTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.ChatMessageSlice, error) {
	var err error
	m := make(models.ChatMessageSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple chatMessages and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o ChatMessageTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.ChatMessageSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple chatMessages and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o ChatMessageTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.ChatMessageSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// ChatMessage has methods that act as mods for the ChatMessageTemplate
var ChatMessageMods chatMessageMods

type chatMessageMods struct{}

func (m chatMessageMods) RandomizeAllColumns(f *faker.Faker) ChatMessageMod {
	return ChatMessageModSlice{
		ChatMessageMods.RandomID(f),
		ChatMessageMods.RandomConversationID(f),
		ChatMessageMods.RandomRole(f),
		ChatMessageMods.RandomContent(f),
		ChatMessageMods.RandomProvider(f),
		ChatMessageMods.RandomModel(f),
		ChatMessageMods.RandomStatus(f),
		ChatMessageMods.RandomErrorMessage(f),
		ChatMessageMods.RandomCreatedAt(f),
	}
}

// Set the model columns to this value
func (m chatMessageMods) ID(val int64) ChatMessageMod {
	return ChatMessageModFunc(func(_ context.Context, o *ChatMessageTemplate) {
		o.ID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m chatMessageMods) IDFunc(f func() int64) ChatMessageMod {
	return ChatMessageModFunc(func(_ context.Context, o *ChatMessageTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m chatMessageMods) UnsetID() ChatMessageMod {
	return ChatMessageModFunc(func(_ context.Context, o *ChatMessageTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m chatMessageMods) RandomID(f *faker.Faker) ChatMessageMod {
	return ChatMessageModFunc(func(_ context.Context, o *ChatMessageTemplate) {
		o.ID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m chatMessageMods) ConversationID(val int64) ChatMessageMod {
	return ChatMessageModFunc(func(_ context.Context, o *ChatMessageTemplate) {
		o.ConversationID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m chatMessageMods) ConversationIDFunc(f func() int64) ChatMessageMod {
	return ChatMessageModFunc(func(_ context.Context, o *ChatMessageTemplate) {
		o.ConversationID = f
	})
}

// Clear any values for the column
func (m chatMessageMods) UnsetConversationID() ChatMessageMod {
	return ChatMessageModFunc(func(_ context.Context, o *ChatMessageTemplate) {
		o.ConversationID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m chatMessageMods) RandomConversationID(f *faker.Faker) ChatMessageMod {
	return ChatMessageModFunc(func(_ context.Context, o *ChatMessageTemplate) {
		o.ConversationID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m chatMessageMods) Role(val string) ChatMessageMod {
	return ChatMessageModFunc(func(_ context.Context, o *ChatMessageTemplate) {
		o.Role = func() string { return val }
	})
}

// Set the Column from the function
func (m chatMessageMods) RoleFunc(f func() string) ChatMessageMod {
	return ChatMessageModFunc(func(_ context.Context, o *ChatMessageTemplate) {
		o.Role = f
	})
}

// Clear any values for the column
func (m chatMessageMods) UnsetRole() ChatMessageMod {
	return ChatMessageModFunc(func(_ context.Context, o *ChatMessageTemplate) {
		o.Role = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m chatMessageMods) RandomRole(f *faker.Faker) ChatMessageMod {
	return ChatMessageModFunc(func(_ context.Context, o *ChatMessageTemplate) {
		o.Role = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m chatMessageMods) Content(val string) ChatMessageMod {
	return ChatMessageModFunc(func(_ context.Context, o *ChatMessageTemplate) {
		o.Content = func() string { return val }
	})
}

// Set the Column from the function
func (m chatMessageMods) ContentFunc(f func() string) ChatMessageMod {
	return ChatMessageModFunc(func(_ context.Context, o *ChatMessageTemplate) {
		o.Content = f
	})
}

// Clear any values for the column
func (m chatMessageMods) UnsetContent() ChatMessageMod {
	return ChatMessageModFunc(func(_ context.Context, o *ChatMessageTemplate) {
		o.Content = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m chatMessageMods) RandomContent(f *faker.Faker) ChatMessageMod {
	return ChatMessageModFunc(func(_ context.Context, o *ChatMessageTemplate) {
		o.Content = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m chatMessageMods) Provider(val null.Val[string]) ChatMessageMod {
	return ChatMessageModFunc(func(_ context.Context, o *ChatMessageTemplate) {
		o.Provider = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m chatMessageMods) ProviderFunc(f func() null.Val[string]) ChatMessageMod {
	return ChatMessageModFunc(func(_ context.Context, o *ChatMessageTemplate) {
		o.Provider = f
	})
}

// Clear any values for the column
func (m chatMessageMods) UnsetProvider() ChatMessageMod {
	return ChatMessageModFunc(func(_ context.Context, o *ChatMessageTemplate) {
		o.Provider = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m chatMessageMods) RandomProvider(f *faker.Faker) ChatMessageMod {
	return ChatMessageModFunc(func(_ context.Context, o *ChatMessageTemplate) {
		o.Provider = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m chatMessageMods) RandomProviderNotNull(f *faker.Faker) ChatMessageMod {
	return ChatMessageModFunc(func(_ context.Context, o *ChatMessageTemplate) {
		o.Provider = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m chatMessageMods) Model(val null.Val[string]) ChatMessageMod {
	return ChatMessageModFunc(func(_ context.Context, o *ChatMessageTemplate) {
		o.Model = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m chatMessageMods) ModelFunc(f func() null.Val[string]) ChatMessageMod {
	return ChatMessageModFunc(func(_ context.Context, o *ChatMessageTemplate) {
		o.Model = f
	})
}

// Clear any values for the column
func (m chatMessageMods) UnsetModel() ChatMessageMod {
	return ChatMessageModFunc(func(_ context.Context, o *ChatMessageTemplate) {
		o.Model = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m chatMessageMods) RandomModel(f *faker.Faker) ChatMessageMod {
	return ChatMessageModFunc(func(_ context.Context, o *ChatMessageTemplate) {
		o.Model = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m chatMessageMods) RandomModelNotNull(f *faker.Faker) ChatMessageMod {
	return ChatMessageModFunc(func(_ context.Context, o *ChatMessageTemplate) {
		o.Model = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m chatMessageMods) Status(val string) ChatMessageMod {
	return ChatMessageModFunc(func(_ context.Context, o *ChatMessageTemplate) {
		o.Status = func() string { return val }
	})
}

// Set the Column from the function
func (m chatMessageMods) StatusFunc(f func() string) ChatMessageMod {
	return ChatMessageModFunc(func(_ context.Context, o *ChatMessageTemplate) {
		o.Status = f
	})
}

// Clear any values for the column
func (m chatMessageMods) UnsetStatus() ChatMessageMod {
	return ChatMessageModFunc(func(_ context.Context, o *ChatMessageTemplate) {
		o.Status = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m chatMessageMods) RandomStatus(f *faker.Faker) ChatMessageMod {
	return ChatMessageModFunc(func(_ context.Context, o *ChatMessageTemplate) {
		o.Status = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m chatMessageMods) ErrorMessage(val null.Val[string]) ChatMessageMod {
	return ChatMessageModFunc(func(_ context.Context, o *ChatMessageTemplate) {
		o.ErrorMessage = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m chatMessageMods) ErrorMessageFunc(f func() null.Val[string]) ChatMessageMod {
	return ChatMessageModFunc(func(_ context.Context, o *ChatMessageTemplate) {
		o.ErrorMessage = f
	})
}

// Clear any values for the column
func (m chatMessageMods) UnsetErrorMessage() ChatMessageMod {
	return ChatMessageModFunc(func(_ context.Context, o *ChatMessageTemplate) {
		o.ErrorMessage = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m chatMessageMods) RandomErrorMessage(f *faker.Faker) ChatMessageMod {
	return ChatMessageModFunc(func(_ context.Context, o *ChatMessageTemplate) {
		o.ErrorMessage = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m chatMessageMods) RandomErrorMessageNotNull(f *faker.Faker) ChatMessageMod {
	return ChatMessageModFunc(func(_ context.Context, o *ChatMessageTemplate) {
		o.ErrorMessage = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m chatMessageMods) CreatedAt(val time.Time) ChatMessageMod {
	return ChatMessageModFunc(func(_ context.Context, o *ChatMessageTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m chatMessageMods) CreatedAtFunc(f func() time.Time) ChatMessageMod {
	return ChatMessageModFunc(func(_ context.Context, o *ChatMessageTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m chatMessageMods) UnsetCreatedAt() ChatMessageMod {
	return ChatMessageModFunc(func(_ context.Context, o *ChatMessageTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m chatMessageMods) RandomCreatedAt(f *faker.Faker) ChatMessageMod {
	return ChatMessageModFunc(func(_ context.Context, o *ChatMessageTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m chatMessageMods) WithParentsCascading() ChatMessageMod {
	return ChatMessageModFunc(func(ctx context.Context, o *ChatMessageTemplate) {
		if isDone, _ := chatMessageWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = chatMessageWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewChatMessageExecutionWithContext(ctx, ChatMessageExecutionMods.WithParentsCascading())
			m.WithMessageChatMessageExecution(related).Apply(ctx, o)
		}
		{

			related := o.f.NewChatMessageRetrievalWithContext(ctx, ChatMessageRetrievalMods.WithParentsCascading())
			m.WithMessageChatMessageRetrieval(related).Apply(ctx, o)
		}
		{

			related := o.f.NewChatConversationWithContext(ctx, ChatConversationMods.WithParentsCascading())
			m.WithConversationChatConversation(related).Apply(ctx, o)
		}
	})
}

func (m chatMessageMods) WithMessageChatMessageExecution(rel *ChatMessageExecutionTemplate) ChatMessageMod {
	return ChatMessageModFunc(func(ctx context.Context, o *ChatMessageTemplate) {
		o.r.MessageChatMessageExecution = &chatMessageRMessageChatMessageExecutionR{
			o: rel,
		}
	})
}

func (m chatMessageMods) WithNewMessageChatMessageExecution(mods ...ChatMessageExecutionMod) ChatMessageMod {
	return ChatMessageModFunc(func(ctx context.Context, o *ChatMessageTemplate) {
		related := o.f.NewChatMessageExecutionWithContext(ctx, mods...)

		m.WithMessageChatMessageExecution(related).Apply(ctx, o)
	})
}

func (m chatMessageMods) WithExistingMessageChatMessageExecution(em *models.ChatMessageExecution) ChatMessageMod {
	return ChatMessageModFunc(func(ctx context.Context, o *ChatMessageTemplate) {
		o.r.MessageChatMessageExecution = &chatMessageRMessageChatMessageExecutionR{
			o: o.f.fromExistingChatMessageExecution(ctx, em),
		}
	})
}

func (m chatMessageMods) WithoutMessageChatMessageExecution() ChatMessageMod {
	return ChatMessageModFunc(func(ctx context.Context, o *ChatMessageTemplate) {
		o.r.MessageChatMessageExecution = nil
	})
}

func (m chatMessageMods) WithMessageChatMessageRetrieval(rel *ChatMessageRetrievalTemplate) ChatMessageMod {
	return ChatMessageModFunc(func(ctx context.Context, o *ChatMessageTemplate) {
		o.r.MessageChatMessageRetrieval = &chatMessageRMessageChatMessageRetrievalR{
			o: rel,
		}
	})
}

func (m chatMessageMods) WithNewMessageChatMessageRetrieval(mods ...ChatMessageRetrievalMod) ChatMessageMod {
	return ChatMessageModFunc(func(ctx context.Context, o *ChatMessageTemplate) {
		related := o.f.NewChatMessageRetrievalWithContext(ctx, mods...)

		m.WithMessageChatMessageRetrieval(related).Apply(ctx, o)
	})
}

func (m chatMessageMods) WithExistingMessageChatMessageRetrieval(em *models.ChatMessageRetrieval) ChatMessageMod {
	return ChatMessageModFunc(func(ctx context.Context, o *ChatMessageTemplate) {
		o.r.MessageChatMessageRetrieval = &chatMessageRMessageChatMessageRetrievalR{
			o: o.f.fromExistingChatMessageRetrieval(ctx, em),
		}
	})
}

func (m chatMessageMods) WithoutMessageChatMessageRetrieval() ChatMessageMod {
	return ChatMessageModFunc(func(ctx context.Context, o *ChatMessageTemplate) {
		o.r.MessageChatMessageRetrieval = nil
	})
}

func (m chatMessageMods) WithConversationChatConversation(rel *ChatConversationTemplate) ChatMessageMod {
	return ChatMessageModFunc(func(ctx context.Context, o *ChatMessageTemplate) {
		o.r.ConversationChatConversation = &chatMessageRConversationChatConversationR{
			o: rel,
		}
	})
}

func (m chatMessageMods) WithNewConversationChatConversation(mods ...ChatConversationMod) ChatMessageMod {
	return ChatMessageModFunc(func(ctx context.Context, o *ChatMessageTemplate) {
		related := o.f.NewChatConversationWithContext(ctx, mods...)

		m.WithConversationChatConversation(related).Apply(ctx, o)
	})
}

func (m chatMessageMods) WithExistingConversationChatConversation(em *models.ChatConversation) ChatMessageMod {
	return ChatMessageModFunc(func(ctx context.Context, o *ChatMessageTemplate) {
		o.r.ConversationChatConversation = &chatMessageRConversationChatConversationR{
			o: o.f.fromExistingChatConversation(ctx, em),
		}
	})
}

func (m chatMessageMods) WithoutConversationChatConversation() ChatMessageMod {
	return ChatMessageModFunc(func(ctx context.Context, o *ChatMessageTemplate) {
		o.r.ConversationChatConversation = nil
	})
}

func (m chatMessageMods) WithMessageChatMessageLLMCalls(number int, related *ChatMessageLLMCallTemplate) ChatMessageMod {
	return ChatMessageModFunc(func(ctx context.Context, o *ChatMessageTemplate) {
		o.r.MessageChatMessageLLMCalls = []*chatMessageRMessageChatMessageLLMCallsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m chatMessageMods) WithNewMessageChatMessageLLMCalls(number int, mods ...ChatMessageLLMCallMod) ChatMessageMod {
	return ChatMessageModFunc(func(ctx context.Context, o *ChatMessageTemplate) {
		related := o.f.NewChatMessageLLMCallWithContext(ctx, mods...)
		m.WithMessageChatMessageLLMCalls(number, related).Apply(ctx, o)
	})
}

func (m chatMessageMods) AddMessageChatMessageLLMCalls(number int, related *ChatMessageLLMCallTemplate) ChatMessageMod {
	return ChatMessageModFunc(func(ctx context.Context, o *ChatMessageTemplate) {
		o.r.MessageChatMessageLLMCalls = append(o.r.MessageChatMessageLLMCalls, &chatMessageRMessageChatMessageLLMCallsR{
			number: number,
			o:      related,
		})
	})
}

func (m chatMessageMods) AddNewMessageChatMessageLLMCalls(number int, mods ...ChatMessageLLMCallMod) ChatMessageMod {
	return ChatMessageModFunc(func(ctx context.Context, o *ChatMessageTemplate) {
		related := o.f.NewChatMessageLLMCallWithContext(ctx, mods...)
		m.AddMessageChatMessageLLMCalls(number, related).Apply(ctx, o)
	})
}

func (m chatMessageMods) AddExistingMessageChatMessageLLMCalls(existingModels ...*models.ChatMessageLLMCall) ChatMessageMod {
	return ChatMessageModFunc(func(ctx context.Context, o *ChatMessageTemplate) {
		for _, em := range existingModels {
			o.r.MessageChatMessageLLMCalls = append(o.r.MessageChatMessageLLMCalls, &chatMessageRMessageChatMessageLLMCallsR{
				o: o.f.fromExistingChatMessageLLMCall(ctx, em),
			})
		}
	})
}

func (m chatMessageMods) WithoutMessageChatMessageLLMCalls() ChatMessageMod {
	return ChatMessageModFunc(func(ctx context.Context, o *ChatMessageTemplate) {
		o.r.MessageChatMessageLLMCalls = nil
	})
}
