// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"encoding/json"
	"testing"
	"time"

	models "github.com/Uncensored-Developer/datalk/apps/backend/db/models"
	"github.com/aarondl/opt/omit"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/types"
)

type ChatMessageRetrievalMod interface {
	Apply(context.Context, *ChatMessageRetrievalTemplate)
}

type ChatMessageRetrievalModFunc func(context.Context, *ChatMessageRetrievalTemplate)

func (f ChatMessageRetrievalModFunc) Apply(ctx context.Context, n *ChatMessageRetrievalTemplate) {
	f(ctx, n)
}

type ChatMessageRetrievalModSlice []ChatMessageRetrievalMod

func (mods ChatMessageRetrievalModSlice) Apply(ctx context.Context, n *ChatMessageRetrievalTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// ChatMessageRetrievalTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type ChatMessageRetrievalTemplate struct {
	MessageID   func() int64
	SnapshotID  func() int32
	QueryText   func() string
	Chunks      func() types.JSON[json.RawMessage]
	RetrievedAt func() time.Time

	r chatMessageRetrievalR
	f *Factory

	alreadyPersisted bool
}

type chatMessageRetrievalR struct {
	MessageChatMessage     *chatMessageRetrievalRMessageChatMessageR
	SnapshotSchemaSnapshot *chatMessageRetrievalRSnapshotSchemaSnapshotR
}

type chatMessageRetrievalRMessageChatMessageR struct {
	o *ChatMessageTemplate
}
type chatMessageRetrievalRSnapshotSchemaSnapshotR struct {
	o *SchemaSnapshotTemplate
}

// Apply mods to the ChatMessageRetrievalTemplate
func (o *ChatMessageRetrievalTemplate) Apply(ctx context.Context, mods ...ChatMessageRetrievalMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.ChatMessageRetrieval
// according to the relationships in the template. Nothing is inserted into the db
func (t ChatMessageRetrievalTemplate) setModelRels(o *models.ChatMessageRetrieval) {
	if t.r.MessageChatMessage != nil {
		rel := t.r.MessageChatMessage.o.Build()
		o.MessageID = rel.ID // h2
		o.R.MessageChatMessage = rel
		o.R.Loaded.MessageChatMessage = true
	}

	if t.r.SnapshotSchemaSnapshot != nil {
		rel := t.r.SnapshotSchemaSnapshot.o.Build()
		o.SnapshotID = rel.ID // h2
		o.R.SnapshotSchemaSnapshot = rel
		o.R.Loaded.SnapshotSchemaSnapshot = true
	}
}

// BuildSetter returns an *models.ChatMessageRetrievalSetter
// this does nothing with the relationship templates
func (o ChatMessageRetrievalTemplate) BuildSetter() *models.ChatMessageRetrievalSetter {
	m := &models.ChatMessageRetrievalSetter{}

	if o.MessageID != nil {
		val := o.MessageID()
		m.MessageID = omit.From(val)
	}
	if o.SnapshotID != nil {
		val := o.SnapshotID()
		m.SnapshotID = omit.From(val)
	}
	if o.QueryText != nil {
		val := o.QueryText()
		m.QueryText = omit.From(val)
	}
	if o.Chunks != nil {
		val := o.Chunks()
		m.Chunks = omit.From(val)
	}
	if o.RetrievedAt != nil {
		val := o.RetrievedAt()
		m.RetrievedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.ChatMessageRetrievalSetter
// this does nothing with the relationship templates
func (o ChatMessageRetrievalTemplate) BuildManySetter(number int) []*models.ChatMessageRetrievalSetter {
	m := make([]*models.ChatMessageRetrievalSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.ChatMessageRetrieval
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ChatMessageRetrievalTemplate.Create
func (o ChatMessageRetrievalTemplate) Build() *models.ChatMessageRetrieval {
	m := &models.ChatMessageRetrieval{}

	if o.MessageID != nil {
		m.MessageID = o.MessageID()
	}
	if o.SnapshotID != nil {
		m.SnapshotID = o.SnapshotID()
	}
	if o.QueryText != nil {
		m.QueryText = o.QueryText()
	}
	if o.Chunks != nil {
		m.Chunks = o.Chunks()
	}
	if o.RetrievedAt != nil {
		m.RetrievedAt = o.RetrievedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.ChatMessageRetrievalSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ChatMessageRetrievalTemplate.CreateMany
func (o ChatMessageRetrievalTemplate) BuildMany(number int) models.ChatMessageRetrievalSlice {
	m := make(models.ChatMessageRetrievalSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableChatMessageRetrieval(m *models.ChatMessageRetrievalSetter) {
	if !(m.MessageID.IsValue()) {
		val := random_int64(nil)
		m.MessageID = omit.From(val)
	}
	if !(m.SnapshotID.IsValue()) {
		val := random_int32(nil)
		m.SnapshotID = omit.From(val)
	}
	if !(m.QueryText.IsValue()) {
		val := random_string(nil)
		m.QueryText = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.ChatMessageRetrieval
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *ChatMessageRetrievalTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.ChatMessageRetrieval) error {
	var err error

	return err
}

// Create builds a chatMessageRetrieval and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *ChatMessageRetrievalTemplate) Create(ctx context.Context, exec bob.Executor) (*models.ChatMessageRetrieval, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableChatMessageRetrieval(opt)

	// Retrieve ancestor models from context to avoid duplicate parent creation.
	// Parents are keyed by "parent_table:child_table:child_rel_name".
	// This works regardless of NoBackReferencing since it only uses child-side metadata.
	mInCreation, _ := modelsInCreationCtx.Value(ctx)

	var rel0 *models.ChatMessage

	if o.r.MessageChatMessage == nil {
		if parentModel, found := mInCreation["chat_messages:chat_message_retrievals:chat_message_retrievals.chat_message_retrievals_message_id_fkey"]; found {
			if pModel, ok := parentModel.(*models.ChatMessage); ok {
				rel0 = pModel
			}
		}
	}

	if rel0 == nil {
		if o.r.MessageChatMessage == nil {
			ChatMessageRetrievalMods.WithNewMessageChatMessage().Apply(ctx, o)
		}

		if o.r.MessageChatMessage.o.alreadyPersisted {
			rel0 = o.r.MessageChatMessage.o.Build()
		} else {
			rel0, err = o.r.MessageChatMessage.o.Create(ctx, exec)
			if err != nil {
				return nil, err
			}
		}
	}

	opt.MessageID = omit.From(rel0.ID)

	var rel1 *models.SchemaSnapshot

	if o.r.SnapshotSchemaSnapshot == nil {
		if parentModel, found := mInCreation["schema_snapshots:chat_message_retrievals:chat_message_retrievals.chat_message_retrievals_snapshot_id_fkey"]; found {
			if pModel, ok := parentModel.(*models.SchemaSnapshot); ok {
				rel1 = pModel
			}
		}
	}

	if rel1 == nil {
		if o.r.SnapshotSchemaSnapshot == nil {
			ChatMessageRetrievalMods.WithNewSnapshotSchemaSnapshot().Apply(ctx, o)
		}

		if o.r.SnapshotSchemaSnapshot.o.alreadyPersisted {
			rel1 = o.r.SnapshotSchemaSnapshot.o.Build()
		} else {
			rel1, err = o.r.SnapshotSchemaSnapshot.o.Create(ctx, exec)
			if err != nil {
				return nil, err
			}
		}
	}

	opt.SnapshotID = omit.From(rel1.ID)

	m, err := models.ChatMessageRetrievals.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	// Store this model in context for child creates.
	// Key format: "parent_table:child_table:child_rel_name" where child_rel_name is the FK name.
	// We store an entry for every relationship pointing TO this table (where this table is the parent).
	// This works regardless of NoBackReferencing since keys use child-side metadata.
	newMInCreation := make(map[string]any, len(mInCreation)+1)
	for k, v := range mInCreation {
		newMInCreation[k] = v
	}
	newMInCreation["chat_message_retrievals:chat_messages:chat_message_retrievals.chat_message_retrievals_message_id_fkey"] = m

	ctx = modelsInCreationCtx.WithValue(ctx, newMInCreation)

	m.R.MessageChatMessage = rel0
	m.R.Loaded.MessageChatMessage = true
	m.R.SnapshotSchemaSnapshot = rel1
	m.R.Loaded.SnapshotSchemaSnapshot = true

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a chatMessageRetrieval and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *ChatMessageRetrievalTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.ChatMessageRetrieval {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a chatMessageRetrieval and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *ChatMessageRetrievalTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.ChatMessageRetrieval {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple chatMessageRetrievals and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o ChatMessageRetrievalTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.ChatMessageRetrievalSlice, error) {
	var err error
	m := make(models.ChatMessageRetrievalSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple chatMessageRetrievals and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o ChatMessageRetrievalTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.ChatMessageRetrievalSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple chatMessageRetrievals and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o ChatMessageRetrievalTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.ChatMessageRetrievalSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// ChatMessageRetrieval has methods that act as mods for the ChatMessageRetrievalTemplate
var ChatMessageRetrievalMods chatMessageRetrievalMods

type chatMessageRetrievalMods struct{}

func (m chatMessageRetrievalMods) RandomizeAllColumns(f *faker.Faker) ChatMessageRetrievalMod {
	return ChatMessageRetrievalModSlice{
		ChatMessageRetrievalMods.RandomMessageID(f),
		ChatMessageRetrievalMods.RandomSnapshotID(f),
		ChatMessageRetrievalMods.RandomQueryText(f),
		ChatMessageRetrievalMods.RandomChunks(f),
		ChatMessageRetrievalMods.RandomRetrievedAt(f),
	}
}

// Set the model columns to this value
func (m chatMessageRetrievalMods) MessageID(val int64) ChatMessageRetrievalMod {
	return ChatMessageRetrievalModFunc(func(_ context.Context, o *ChatMessageRetrievalTemplate) {
		o.MessageID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m chatMessageRetrievalMods) MessageIDFunc(f func() int64) ChatMessageRetrievalMod {
	return ChatMessageRetrievalModFunc(func(_ context.Context, o *ChatMessageRetrievalTemplate) {
		o.MessageID = f
	})
}

// Clear any values for the column
func (m chatMessageRetrievalMods) UnsetMessageID() ChatMessageRetrievalMod {
	return ChatMessageRetrievalModFunc(func(_ context.Context, o *ChatMessageRetrievalTemplate) {
		o.MessageID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m chatMessageRetrievalMods) RandomMessageID(f *faker.Faker) ChatMessageRetrievalMod {
	return ChatMessageRetrievalModFunc(func(_ context.Context, o *ChatMessageRetrievalTemplate) {
		o.MessageID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m chatMessageRetrievalMods) SnapshotID(val int32) ChatMessageRetrievalMod {
	return ChatMessageRetrievalModFunc(func(_ context.Context, o *ChatMessageRetrievalTemplate) {
		o.SnapshotID = func() int32 { return val }
	})
}

// Set the Column from the function
func (m chatMessageRetrievalMods) SnapshotIDFunc(f func() int32) ChatMessageRetrievalMod {
	return ChatMessageRetrievalModFunc(func(_ context.Context, o *ChatMessageRetrievalTemplate) {
		o.SnapshotID = f
	})
}

// Clear any values for the column
func (m chatMessageRetrievalMods) UnsetSnapshotID() ChatMessageRetrievalMod {
	return ChatMessageRetrievalModFunc(func(_ context.Context, o *ChatMessageRetrievalTemplate) {
		o.SnapshotID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m chatMessageRetrievalMods) RandomSnapshotID(f *faker.Faker) ChatMessageRetrievalMod {
	return ChatMessageRetrievalModFunc(func(_ context.Context, o *ChatMessageRetrievalTemplate) {
		o.SnapshotID = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m chatMessageRetrievalMods) QueryText(val string) ChatMessageRetrievalMod {
	return ChatMessageRetrievalModFunc(func(_ context.Context, o *ChatMessageRetrievalTemplate) {
		o.QueryText = func() string { return val }
	})
}

// Set the Column from the function
func (m chatMessageRetrievalMods) QueryTextFunc(f func() string) ChatMessageRetrievalMod {
	return ChatMessageRetrievalModFunc(func(_ context.Context, o *ChatMessageRetrievalTemplate) {
		o.QueryText = f
	})
}

// Clear any values for the column
func (m chatMessageRetrievalMods) UnsetQueryText() ChatMessageRetrievalMod {
	return ChatMessageRetrievalModFunc(func(_ context.Context, o *ChatMessageRetrievalTemplate) {
		o.QueryText = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m chatMessageRetrievalMods) RandomQueryText(f *faker.Faker) ChatMessageRetrievalMod {
	return ChatMessageRetrievalModFunc(func(_ context.Context, o *ChatMessageRetrievalTemplate) {
		o.QueryText = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m chatMessageRetrievalMods) Chunks(val types.JSON[json.RawMessage]) ChatMessageRetrievalMod {
	return ChatMessageRetrievalModFunc(func(_ context.Context, o *ChatMessageRetrievalTemplate) {
		o.Chunks = func() types.JSON[json.RawMessage] { return val }
	})
}

// Set the Column from the function
func (m chatMessageRetrievalMods) ChunksFunc(f func() types.JSON[json.RawMessage]) ChatMessageRetrievalMod {
	return ChatMessageRetrievalModFunc(func(_ context.Context, o *ChatMessageRetrievalTemplate) {
		o.Chunks = f
	})
}

// Clear any values for the column
func (m chatMessageRetrievalMods) UnsetChunks() ChatMessageRetrievalMod {
	return ChatMessageRetrievalModFunc(func(_ context.Context, o *ChatMessageRetrievalTemplate) {
		o.Chunks = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m chatMessageRetrievalMods) RandomChunks(f *faker.Faker) ChatMessageRetrievalMod {
	return ChatMessageRetrievalModFunc(func(_ context.Context, o *ChatMessageRetrievalTemplate) {
		o.Chunks = func() types.JSON[json.RawMessage] {
			return random_types_JSON_json_RawMessage_(f)
		}
	})
}

// Set the model columns to this value
func (m chatMessageRetrievalMods) RetrievedAt(val time.Time) ChatMessageRetrievalMod {
	return ChatMessageRetrievalModFunc(func(_ context.Context, o *ChatMessageRetrievalTemplate) {
		o.RetrievedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m chatMessageRetrievalMods) RetrievedAtFunc(f func() time.Time) ChatMessageRetrievalMod {
	return ChatMessageRetrievalModFunc(func(_ context.Context, o *ChatMessageRetrievalTemplate) {
		o.RetrievedAt = f
	})
}

// Clear any values for the column
func (m chatMessageRetrievalMods) UnsetRetrievedAt() ChatMessageRetrievalMod {
	return ChatMessageRetrievalModFunc(func(_ context.Context, o *ChatMessageRetrievalTemplate) {
		o.RetrievedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m chatMessageRetrievalMods) RandomRetrievedAt(f *faker.Faker) ChatMessageRetrievalMod {
	return ChatMessageRetrievalModFunc(func(_ context.Context, o *ChatMessageRetrievalTemplate) {
		o.RetrievedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m chatMessageRetrievalMods) WithParentsCascading() ChatMessageRetrievalMod {
	return ChatMessageRetrievalModFunc(func(ctx context.Context, o *ChatMessageRetrievalTemplate) {
		if isDone, _ := chatMessageRetrievalWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = chatMessageRetrievalWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewChatMessageWithContext(ctx, ChatMessageMods.WithParentsCascading())
			m.WithMessageChatMessage(related).Apply(ctx, o)
		}
		{

			related := o.f.NewSchemaSnapshotWithContext(ctx, SchemaSnapshotMods.WithParentsCascading())
			m.WithSnapshotSchemaSnapshot(related).Apply(ctx, o)
		}
	})
}

func (m chatMessageRetrievalMods) WithMessageChatMessage(rel *ChatMessageTemplate) ChatMessageRetrievalMod {
	return ChatMessageRetrievalModFunc(func(ctx context.Context, o *ChatMessageRetrievalTemplate) {
		o.r.MessageChatMessage = &chatMessageRetrievalRMessageChatMessageR{
			o: rel,
		}
	})
}

func (m chatMessageRetrievalMods) WithNewMessageChatMessage(mods ...ChatMessageMod) ChatMessageRetrievalMod {
	return ChatMessageRetrievalModFunc(func(ctx context.Context, o *ChatMessageRetrievalTemplate) {
		related := o.f.NewChatMessageWithContext(ctx, mods...)

		m.WithMessageChatMessage(related).Apply(ctx, o)
	})
}

func (m chatMessageRetrievalMods) WithExistingMessageChatMessage(em *models.ChatMessage) ChatMessageRetrievalMod {
	return ChatMessageRetrievalModFunc(func(ctx context.Context, o *ChatMessageRetrievalTemplate) {
		o.r.MessageChatMessage = &chatMessageRetrievalRMessageChatMessageR{
			o: o.f.fromExistingChatMessage(ctx, em),
		}
	})
}

func (m chatMessageRetrievalMods) WithoutMessageChatMessage() ChatMessageRetrievalMod {
	return ChatMessageRetrievalModFunc(func(ctx context.Context, o *ChatMessageRetrievalTemplate) {
		o.r.MessageChatMessage = nil
	})
}

func (m chatMessageRetrievalMods) WithSnapshotSchemaSnapshot(rel *SchemaSnapshotTemplate) ChatMessageRetrievalMod {
	return ChatMessageRetrievalModFunc(func(ctx context.Context, o *ChatMessageRetrievalTemplate) {
		o.r.SnapshotSchemaSnapshot = &chatMessageRetrievalRSnapshotSchemaSnapshotR{
			o: rel,
		}
	})
}

func (m chatMessageRetrievalMods) WithNewSnapshotSchemaSnapshot(mods ...SchemaSnapshotMod) ChatMessageRetrievalMod {
	return ChatMessageRetrievalModFunc(func(ctx context.Context, o *ChatMessageRetrievalTemplate) {
		related := o.f.NewSchemaSnapshotWithContext(ctx, mods...)

		m.WithSnapshotSchemaSnapshot(related).Apply(ctx, o)
	})
}

func (m chatMessageRetrievalMods) WithExistingSnapshotSchemaSnapshot(em *models.SchemaSnapshot) ChatMessageRetrievalMod {
	return ChatMessageRetrievalModFunc(func(ctx context.Context, o *ChatMessageRetrievalTemplate) {
		o.r.SnapshotSchemaSnapshot = &chatMessageRetrievalRSnapshotSchemaSnapshotR{
			o: o.f.fromExistingSchemaSnapshot(ctx, em),
		}
	})
}

func (m chatMessageRetrievalMods) WithoutSnapshotSchemaSnapshot() ChatMessageRetrievalMod {
	return ChatMessageRetrievalModFunc(func(ctx context.Context, o *ChatMessageRetrievalTemplate) {
		o.r.SnapshotSchemaSnapshot = nil
	})
}
