// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"encoding/json"
	"testing"
	"time"

	models "github.com/Uncensored-Developer/datalk/apps/backend/db/models"
	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/types"
)

type ConnectionMod interface {
	Apply(context.Context, *ConnectionTemplate)
}

type ConnectionModFunc func(context.Context, *ConnectionTemplate)

func (f ConnectionModFunc) Apply(ctx context.Context, n *ConnectionTemplate) {
	f(ctx, n)
}

type ConnectionModSlice []ConnectionMod

func (mods ConnectionModSlice) Apply(ctx context.Context, n *ConnectionTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// ConnectionTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type ConnectionTemplate struct {
	ID        func() int32
	Name      func() string
	Kind      func() string
	DSN       func() null.Val[string]
	IsEnabled func() bool
	UserID    func() int32
	CreatedAt func() time.Time
	Metadata  func() types.JSON[json.RawMessage]

	r connectionR
	f *Factory

	alreadyPersisted bool
}

type connectionR struct {
	ChatConversations     []*connectionRChatConversationsR
	ChatMessageExecutions []*connectionRChatMessageExecutionsR
	ConnectionAccesses    []*connectionRConnectionAccessesR
	User                  *connectionRUserR
	SchemaChunks          []*connectionRSchemaChunksR
	SchemaSnapshots       []*connectionRSchemaSnapshotsR
}

type connectionRChatConversationsR struct {
	number int
	o      *ChatConversationTemplate
}
type connectionRChatMessageExecutionsR struct {
	number int
	o      *ChatMessageExecutionTemplate
}
type connectionRConnectionAccessesR struct {
	number int
	o      *ConnectionAccessTemplate
}
type connectionRUserR struct {
	o *UserTemplate
}
type connectionRSchemaChunksR struct {
	number int
	o      *SchemaChunkTemplate
}
type connectionRSchemaSnapshotsR struct {
	number int
	o      *SchemaSnapshotTemplate
}

// Apply mods to the ConnectionTemplate
func (o *ConnectionTemplate) Apply(ctx context.Context, mods ...ConnectionMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Connection
// according to the relationships in the template. Nothing is inserted into the db
func (t ConnectionTemplate) setModelRels(o *models.Connection) {
	if t.r.ChatConversations != nil {
		rel := models.ChatConversationSlice{}
		for _, r := range t.r.ChatConversations {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.ConnectionID = o.ID // h2
			}
			rel = append(rel, related...)
		}
		o.R.ChatConversations = rel
	}

	if t.r.ChatMessageExecutions != nil {
		rel := models.ChatMessageExecutionSlice{}
		for _, r := range t.r.ChatMessageExecutions {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.ConnectionID = o.ID // h2
			}
			rel = append(rel, related...)
		}
		o.R.ChatMessageExecutions = rel
	}

	if t.r.ConnectionAccesses != nil {
		rel := models.ConnectionAccessSlice{}
		for _, r := range t.r.ConnectionAccesses {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.ConnectionID = o.ID // h2
			}
			rel = append(rel, related...)
		}
		o.R.ConnectionAccesses = rel
	}

	if t.r.User != nil {
		rel := t.r.User.o.Build()
		o.UserID = rel.ID // h2
		o.R.User = rel
	}

	if t.r.SchemaChunks != nil {
		rel := models.SchemaChunkSlice{}
		for _, r := range t.r.SchemaChunks {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.ConnectionID = o.ID // h2
			}
			rel = append(rel, related...)
		}
		o.R.SchemaChunks = rel
	}

	if t.r.SchemaSnapshots != nil {
		rel := models.SchemaSnapshotSlice{}
		for _, r := range t.r.SchemaSnapshots {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.ConnectionID = o.ID // h2
			}
			rel = append(rel, related...)
		}
		o.R.SchemaSnapshots = rel
	}
}

// BuildSetter returns an *models.ConnectionSetter
// this does nothing with the relationship templates
func (o ConnectionTemplate) BuildSetter() *models.ConnectionSetter {
	m := &models.ConnectionSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.Name != nil {
		val := o.Name()
		m.Name = omit.From(val)
	}
	if o.Kind != nil {
		val := o.Kind()
		m.Kind = omit.From(val)
	}
	if o.DSN != nil {
		val := o.DSN()
		m.DSN = omitnull.FromNull(val)
	}
	if o.IsEnabled != nil {
		val := o.IsEnabled()
		m.IsEnabled = omit.From(val)
	}
	if o.UserID != nil {
		val := o.UserID()
		m.UserID = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.Metadata != nil {
		val := o.Metadata()
		m.Metadata = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.ConnectionSetter
// this does nothing with the relationship templates
func (o ConnectionTemplate) BuildManySetter(number int) []*models.ConnectionSetter {
	m := make([]*models.ConnectionSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Connection
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ConnectionTemplate.Create
func (o ConnectionTemplate) Build() *models.Connection {
	m := &models.Connection{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Name != nil {
		m.Name = o.Name()
	}
	if o.Kind != nil {
		m.Kind = o.Kind()
	}
	if o.DSN != nil {
		m.DSN = o.DSN()
	}
	if o.IsEnabled != nil {
		m.IsEnabled = o.IsEnabled()
	}
	if o.UserID != nil {
		m.UserID = o.UserID()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.Metadata != nil {
		m.Metadata = o.Metadata()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.ConnectionSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ConnectionTemplate.CreateMany
func (o ConnectionTemplate) BuildMany(number int) models.ConnectionSlice {
	m := make(models.ConnectionSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableConnection(m *models.ConnectionSetter) {
	if !(m.Name.IsValue()) {
		val := random_string(nil)
		m.Name = omit.From(val)
	}
	if !(m.Kind.IsValue()) {
		val := random_string(nil)
		m.Kind = omit.From(val)
	}
	if !(m.UserID.IsValue()) {
		val := random_int32(nil)
		m.UserID = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Connection
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *ConnectionTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Connection) error {
	var err error

	isChatConversationsDone, _ := connectionRelChatConversationsCtx.Value(ctx)
	if !isChatConversationsDone && o.r.ChatConversations != nil {
		ctx = connectionRelChatConversationsCtx.WithValue(ctx, true)
		for _, r := range o.r.ChatConversations {
			if r.o.alreadyPersisted {
				m.R.ChatConversations = append(m.R.ChatConversations, r.o.Build())
			} else {
				rel0, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachChatConversations(ctx, exec, rel0...)
				if err != nil {
					return err
				}
			}
		}
	}

	isChatMessageExecutionsDone, _ := connectionRelChatMessageExecutionsCtx.Value(ctx)
	if !isChatMessageExecutionsDone && o.r.ChatMessageExecutions != nil {
		ctx = connectionRelChatMessageExecutionsCtx.WithValue(ctx, true)
		for _, r := range o.r.ChatMessageExecutions {
			if r.o.alreadyPersisted {
				m.R.ChatMessageExecutions = append(m.R.ChatMessageExecutions, r.o.Build())
			} else {
				rel1, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachChatMessageExecutions(ctx, exec, rel1...)
				if err != nil {
					return err
				}
			}
		}
	}

	isConnectionAccessesDone, _ := connectionRelConnectionAccessesCtx.Value(ctx)
	if !isConnectionAccessesDone && o.r.ConnectionAccesses != nil {
		ctx = connectionRelConnectionAccessesCtx.WithValue(ctx, true)
		for _, r := range o.r.ConnectionAccesses {
			if r.o.alreadyPersisted {
				m.R.ConnectionAccesses = append(m.R.ConnectionAccesses, r.o.Build())
			} else {
				rel2, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachConnectionAccesses(ctx, exec, rel2...)
				if err != nil {
					return err
				}
			}
		}
	}

	isSchemaChunksDone, _ := connectionRelSchemaChunksCtx.Value(ctx)
	if !isSchemaChunksDone && o.r.SchemaChunks != nil {
		ctx = connectionRelSchemaChunksCtx.WithValue(ctx, true)
		for _, r := range o.r.SchemaChunks {
			if r.o.alreadyPersisted {
				m.R.SchemaChunks = append(m.R.SchemaChunks, r.o.Build())
			} else {
				rel4, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachSchemaChunks(ctx, exec, rel4...)
				if err != nil {
					return err
				}
			}
		}
	}

	isSchemaSnapshotsDone, _ := connectionRelSchemaSnapshotsCtx.Value(ctx)
	if !isSchemaSnapshotsDone && o.r.SchemaSnapshots != nil {
		ctx = connectionRelSchemaSnapshotsCtx.WithValue(ctx, true)
		for _, r := range o.r.SchemaSnapshots {
			if r.o.alreadyPersisted {
				m.R.SchemaSnapshots = append(m.R.SchemaSnapshots, r.o.Build())
			} else {
				rel5, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachSchemaSnapshots(ctx, exec, rel5...)
				if err != nil {
					return err
				}
			}
		}
	}

	return err
}

// Create builds a connection and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *ConnectionTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Connection, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableConnection(opt)

	if o.r.User == nil {
		ConnectionMods.WithNewUser().Apply(ctx, o)
	}

	var rel3 *models.User

	if o.r.User.o.alreadyPersisted {
		rel3 = o.r.User.o.Build()
	} else {
		rel3, err = o.r.User.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.UserID = omit.From(rel3.ID)

	m, err := models.Connections.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.User = rel3

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a connection and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *ConnectionTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Connection {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a connection and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *ConnectionTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Connection {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple connections and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o ConnectionTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.ConnectionSlice, error) {
	var err error
	m := make(models.ConnectionSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple connections and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o ConnectionTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.ConnectionSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple connections and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o ConnectionTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.ConnectionSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Connection has methods that act as mods for the ConnectionTemplate
var ConnectionMods connectionMods

type connectionMods struct{}

func (m connectionMods) RandomizeAllColumns(f *faker.Faker) ConnectionMod {
	return ConnectionModSlice{
		ConnectionMods.RandomID(f),
		ConnectionMods.RandomName(f),
		ConnectionMods.RandomKind(f),
		ConnectionMods.RandomDSN(f),
		ConnectionMods.RandomIsEnabled(f),
		ConnectionMods.RandomUserID(f),
		ConnectionMods.RandomCreatedAt(f),
		ConnectionMods.RandomMetadata(f),
	}
}

// Set the model columns to this value
func (m connectionMods) ID(val int32) ConnectionMod {
	return ConnectionModFunc(func(_ context.Context, o *ConnectionTemplate) {
		o.ID = func() int32 { return val }
	})
}

// Set the Column from the function
func (m connectionMods) IDFunc(f func() int32) ConnectionMod {
	return ConnectionModFunc(func(_ context.Context, o *ConnectionTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m connectionMods) UnsetID() ConnectionMod {
	return ConnectionModFunc(func(_ context.Context, o *ConnectionTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m connectionMods) RandomID(f *faker.Faker) ConnectionMod {
	return ConnectionModFunc(func(_ context.Context, o *ConnectionTemplate) {
		o.ID = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m connectionMods) Name(val string) ConnectionMod {
	return ConnectionModFunc(func(_ context.Context, o *ConnectionTemplate) {
		o.Name = func() string { return val }
	})
}

// Set the Column from the function
func (m connectionMods) NameFunc(f func() string) ConnectionMod {
	return ConnectionModFunc(func(_ context.Context, o *ConnectionTemplate) {
		o.Name = f
	})
}

// Clear any values for the column
func (m connectionMods) UnsetName() ConnectionMod {
	return ConnectionModFunc(func(_ context.Context, o *ConnectionTemplate) {
		o.Name = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m connectionMods) RandomName(f *faker.Faker) ConnectionMod {
	return ConnectionModFunc(func(_ context.Context, o *ConnectionTemplate) {
		o.Name = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m connectionMods) Kind(val string) ConnectionMod {
	return ConnectionModFunc(func(_ context.Context, o *ConnectionTemplate) {
		o.Kind = func() string { return val }
	})
}

// Set the Column from the function
func (m connectionMods) KindFunc(f func() string) ConnectionMod {
	return ConnectionModFunc(func(_ context.Context, o *ConnectionTemplate) {
		o.Kind = f
	})
}

// Clear any values for the column
func (m connectionMods) UnsetKind() ConnectionMod {
	return ConnectionModFunc(func(_ context.Context, o *ConnectionTemplate) {
		o.Kind = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m connectionMods) RandomKind(f *faker.Faker) ConnectionMod {
	return ConnectionModFunc(func(_ context.Context, o *ConnectionTemplate) {
		o.Kind = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m connectionMods) DSN(val null.Val[string]) ConnectionMod {
	return ConnectionModFunc(func(_ context.Context, o *ConnectionTemplate) {
		o.DSN = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m connectionMods) DSNFunc(f func() null.Val[string]) ConnectionMod {
	return ConnectionModFunc(func(_ context.Context, o *ConnectionTemplate) {
		o.DSN = f
	})
}

// Clear any values for the column
func (m connectionMods) UnsetDSN() ConnectionMod {
	return ConnectionModFunc(func(_ context.Context, o *ConnectionTemplate) {
		o.DSN = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m connectionMods) RandomDSN(f *faker.Faker) ConnectionMod {
	return ConnectionModFunc(func(_ context.Context, o *ConnectionTemplate) {
		o.DSN = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m connectionMods) RandomDSNNotNull(f *faker.Faker) ConnectionMod {
	return ConnectionModFunc(func(_ context.Context, o *ConnectionTemplate) {
		o.DSN = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m connectionMods) IsEnabled(val bool) ConnectionMod {
	return ConnectionModFunc(func(_ context.Context, o *ConnectionTemplate) {
		o.IsEnabled = func() bool { return val }
	})
}

// Set the Column from the function
func (m connectionMods) IsEnabledFunc(f func() bool) ConnectionMod {
	return ConnectionModFunc(func(_ context.Context, o *ConnectionTemplate) {
		o.IsEnabled = f
	})
}

// Clear any values for the column
func (m connectionMods) UnsetIsEnabled() ConnectionMod {
	return ConnectionModFunc(func(_ context.Context, o *ConnectionTemplate) {
		o.IsEnabled = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m connectionMods) RandomIsEnabled(f *faker.Faker) ConnectionMod {
	return ConnectionModFunc(func(_ context.Context, o *ConnectionTemplate) {
		o.IsEnabled = func() bool {
			return random_bool(f)
		}
	})
}

// Set the model columns to this value
func (m connectionMods) UserID(val int32) ConnectionMod {
	return ConnectionModFunc(func(_ context.Context, o *ConnectionTemplate) {
		o.UserID = func() int32 { return val }
	})
}

// Set the Column from the function
func (m connectionMods) UserIDFunc(f func() int32) ConnectionMod {
	return ConnectionModFunc(func(_ context.Context, o *ConnectionTemplate) {
		o.UserID = f
	})
}

// Clear any values for the column
func (m connectionMods) UnsetUserID() ConnectionMod {
	return ConnectionModFunc(func(_ context.Context, o *ConnectionTemplate) {
		o.UserID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m connectionMods) RandomUserID(f *faker.Faker) ConnectionMod {
	return ConnectionModFunc(func(_ context.Context, o *ConnectionTemplate) {
		o.UserID = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m connectionMods) CreatedAt(val time.Time) ConnectionMod {
	return ConnectionModFunc(func(_ context.Context, o *ConnectionTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m connectionMods) CreatedAtFunc(f func() time.Time) ConnectionMod {
	return ConnectionModFunc(func(_ context.Context, o *ConnectionTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m connectionMods) UnsetCreatedAt() ConnectionMod {
	return ConnectionModFunc(func(_ context.Context, o *ConnectionTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m connectionMods) RandomCreatedAt(f *faker.Faker) ConnectionMod {
	return ConnectionModFunc(func(_ context.Context, o *ConnectionTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m connectionMods) Metadata(val types.JSON[json.RawMessage]) ConnectionMod {
	return ConnectionModFunc(func(_ context.Context, o *ConnectionTemplate) {
		o.Metadata = func() types.JSON[json.RawMessage] { return val }
	})
}

// Set the Column from the function
func (m connectionMods) MetadataFunc(f func() types.JSON[json.RawMessage]) ConnectionMod {
	return ConnectionModFunc(func(_ context.Context, o *ConnectionTemplate) {
		o.Metadata = f
	})
}

// Clear any values for the column
func (m connectionMods) UnsetMetadata() ConnectionMod {
	return ConnectionModFunc(func(_ context.Context, o *ConnectionTemplate) {
		o.Metadata = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m connectionMods) RandomMetadata(f *faker.Faker) ConnectionMod {
	return ConnectionModFunc(func(_ context.Context, o *ConnectionTemplate) {
		o.Metadata = func() types.JSON[json.RawMessage] {
			return random_types_JSON_json_RawMessage_(f)
		}
	})
}

func (m connectionMods) WithParentsCascading() ConnectionMod {
	return ConnectionModFunc(func(ctx context.Context, o *ConnectionTemplate) {
		if isDone, _ := connectionWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = connectionWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewUserWithContext(ctx, UserMods.WithParentsCascading())
			m.WithUser(related).Apply(ctx, o)
		}
	})
}

func (m connectionMods) WithUser(rel *UserTemplate) ConnectionMod {
	return ConnectionModFunc(func(ctx context.Context, o *ConnectionTemplate) {
		o.r.User = &connectionRUserR{
			o: rel,
		}
	})
}

func (m connectionMods) WithNewUser(mods ...UserMod) ConnectionMod {
	return ConnectionModFunc(func(ctx context.Context, o *ConnectionTemplate) {
		related := o.f.NewUserWithContext(ctx, mods...)

		m.WithUser(related).Apply(ctx, o)
	})
}

func (m connectionMods) WithExistingUser(em *models.User) ConnectionMod {
	return ConnectionModFunc(func(ctx context.Context, o *ConnectionTemplate) {
		o.r.User = &connectionRUserR{
			o: o.f.FromExistingUser(em),
		}
	})
}

func (m connectionMods) WithoutUser() ConnectionMod {
	return ConnectionModFunc(func(ctx context.Context, o *ConnectionTemplate) {
		o.r.User = nil
	})
}

func (m connectionMods) WithChatConversations(number int, related *ChatConversationTemplate) ConnectionMod {
	return ConnectionModFunc(func(ctx context.Context, o *ConnectionTemplate) {
		o.r.ChatConversations = []*connectionRChatConversationsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m connectionMods) WithNewChatConversations(number int, mods ...ChatConversationMod) ConnectionMod {
	return ConnectionModFunc(func(ctx context.Context, o *ConnectionTemplate) {
		related := o.f.NewChatConversationWithContext(ctx, mods...)
		m.WithChatConversations(number, related).Apply(ctx, o)
	})
}

func (m connectionMods) AddChatConversations(number int, related *ChatConversationTemplate) ConnectionMod {
	return ConnectionModFunc(func(ctx context.Context, o *ConnectionTemplate) {
		o.r.ChatConversations = append(o.r.ChatConversations, &connectionRChatConversationsR{
			number: number,
			o:      related,
		})
	})
}

func (m connectionMods) AddNewChatConversations(number int, mods ...ChatConversationMod) ConnectionMod {
	return ConnectionModFunc(func(ctx context.Context, o *ConnectionTemplate) {
		related := o.f.NewChatConversationWithContext(ctx, mods...)
		m.AddChatConversations(number, related).Apply(ctx, o)
	})
}

func (m connectionMods) AddExistingChatConversations(existingModels ...*models.ChatConversation) ConnectionMod {
	return ConnectionModFunc(func(ctx context.Context, o *ConnectionTemplate) {
		for _, em := range existingModels {
			o.r.ChatConversations = append(o.r.ChatConversations, &connectionRChatConversationsR{
				o: o.f.FromExistingChatConversation(em),
			})
		}
	})
}

func (m connectionMods) WithoutChatConversations() ConnectionMod {
	return ConnectionModFunc(func(ctx context.Context, o *ConnectionTemplate) {
		o.r.ChatConversations = nil
	})
}

func (m connectionMods) WithChatMessageExecutions(number int, related *ChatMessageExecutionTemplate) ConnectionMod {
	return ConnectionModFunc(func(ctx context.Context, o *ConnectionTemplate) {
		o.r.ChatMessageExecutions = []*connectionRChatMessageExecutionsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m connectionMods) WithNewChatMessageExecutions(number int, mods ...ChatMessageExecutionMod) ConnectionMod {
	return ConnectionModFunc(func(ctx context.Context, o *ConnectionTemplate) {
		related := o.f.NewChatMessageExecutionWithContext(ctx, mods...)
		m.WithChatMessageExecutions(number, related).Apply(ctx, o)
	})
}

func (m connectionMods) AddChatMessageExecutions(number int, related *ChatMessageExecutionTemplate) ConnectionMod {
	return ConnectionModFunc(func(ctx context.Context, o *ConnectionTemplate) {
		o.r.ChatMessageExecutions = append(o.r.ChatMessageExecutions, &connectionRChatMessageExecutionsR{
			number: number,
			o:      related,
		})
	})
}

func (m connectionMods) AddNewChatMessageExecutions(number int, mods ...ChatMessageExecutionMod) ConnectionMod {
	return ConnectionModFunc(func(ctx context.Context, o *ConnectionTemplate) {
		related := o.f.NewChatMessageExecutionWithContext(ctx, mods...)
		m.AddChatMessageExecutions(number, related).Apply(ctx, o)
	})
}

func (m connectionMods) AddExistingChatMessageExecutions(existingModels ...*models.ChatMessageExecution) ConnectionMod {
	return ConnectionModFunc(func(ctx context.Context, o *ConnectionTemplate) {
		for _, em := range existingModels {
			o.r.ChatMessageExecutions = append(o.r.ChatMessageExecutions, &connectionRChatMessageExecutionsR{
				o: o.f.FromExistingChatMessageExecution(em),
			})
		}
	})
}

func (m connectionMods) WithoutChatMessageExecutions() ConnectionMod {
	return ConnectionModFunc(func(ctx context.Context, o *ConnectionTemplate) {
		o.r.ChatMessageExecutions = nil
	})
}

func (m connectionMods) WithConnectionAccesses(number int, related *ConnectionAccessTemplate) ConnectionMod {
	return ConnectionModFunc(func(ctx context.Context, o *ConnectionTemplate) {
		o.r.ConnectionAccesses = []*connectionRConnectionAccessesR{{
			number: number,
			o:      related,
		}}
	})
}

func (m connectionMods) WithNewConnectionAccesses(number int, mods ...ConnectionAccessMod) ConnectionMod {
	return ConnectionModFunc(func(ctx context.Context, o *ConnectionTemplate) {
		related := o.f.NewConnectionAccessWithContext(ctx, mods...)
		m.WithConnectionAccesses(number, related).Apply(ctx, o)
	})
}

func (m connectionMods) AddConnectionAccesses(number int, related *ConnectionAccessTemplate) ConnectionMod {
	return ConnectionModFunc(func(ctx context.Context, o *ConnectionTemplate) {
		o.r.ConnectionAccesses = append(o.r.ConnectionAccesses, &connectionRConnectionAccessesR{
			number: number,
			o:      related,
		})
	})
}

func (m connectionMods) AddNewConnectionAccesses(number int, mods ...ConnectionAccessMod) ConnectionMod {
	return ConnectionModFunc(func(ctx context.Context, o *ConnectionTemplate) {
		related := o.f.NewConnectionAccessWithContext(ctx, mods...)
		m.AddConnectionAccesses(number, related).Apply(ctx, o)
	})
}

func (m connectionMods) AddExistingConnectionAccesses(existingModels ...*models.ConnectionAccess) ConnectionMod {
	return ConnectionModFunc(func(ctx context.Context, o *ConnectionTemplate) {
		for _, em := range existingModels {
			o.r.ConnectionAccesses = append(o.r.ConnectionAccesses, &connectionRConnectionAccessesR{
				o: o.f.FromExistingConnectionAccess(em),
			})
		}
	})
}

func (m connectionMods) WithoutConnectionAccesses() ConnectionMod {
	return ConnectionModFunc(func(ctx context.Context, o *ConnectionTemplate) {
		o.r.ConnectionAccesses = nil
	})
}

func (m connectionMods) WithSchemaChunks(number int, related *SchemaChunkTemplate) ConnectionMod {
	return ConnectionModFunc(func(ctx context.Context, o *ConnectionTemplate) {
		o.r.SchemaChunks = []*connectionRSchemaChunksR{{
			number: number,
			o:      related,
		}}
	})
}

func (m connectionMods) WithNewSchemaChunks(number int, mods ...SchemaChunkMod) ConnectionMod {
	return ConnectionModFunc(func(ctx context.Context, o *ConnectionTemplate) {
		related := o.f.NewSchemaChunkWithContext(ctx, mods...)
		m.WithSchemaChunks(number, related).Apply(ctx, o)
	})
}

func (m connectionMods) AddSchemaChunks(number int, related *SchemaChunkTemplate) ConnectionMod {
	return ConnectionModFunc(func(ctx context.Context, o *ConnectionTemplate) {
		o.r.SchemaChunks = append(o.r.SchemaChunks, &connectionRSchemaChunksR{
			number: number,
			o:      related,
		})
	})
}

func (m connectionMods) AddNewSchemaChunks(number int, mods ...SchemaChunkMod) ConnectionMod {
	return ConnectionModFunc(func(ctx context.Context, o *ConnectionTemplate) {
		related := o.f.NewSchemaChunkWithContext(ctx, mods...)
		m.AddSchemaChunks(number, related).Apply(ctx, o)
	})
}

func (m connectionMods) AddExistingSchemaChunks(existingModels ...*models.SchemaChunk) ConnectionMod {
	return ConnectionModFunc(func(ctx context.Context, o *ConnectionTemplate) {
		for _, em := range existingModels {
			o.r.SchemaChunks = append(o.r.SchemaChunks, &connectionRSchemaChunksR{
				o: o.f.FromExistingSchemaChunk(em),
			})
		}
	})
}

func (m connectionMods) WithoutSchemaChunks() ConnectionMod {
	return ConnectionModFunc(func(ctx context.Context, o *ConnectionTemplate) {
		o.r.SchemaChunks = nil
	})
}

func (m connectionMods) WithSchemaSnapshots(number int, related *SchemaSnapshotTemplate) ConnectionMod {
	return ConnectionModFunc(func(ctx context.Context, o *ConnectionTemplate) {
		o.r.SchemaSnapshots = []*connectionRSchemaSnapshotsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m connectionMods) WithNewSchemaSnapshots(number int, mods ...SchemaSnapshotMod) ConnectionMod {
	return ConnectionModFunc(func(ctx context.Context, o *ConnectionTemplate) {
		related := o.f.NewSchemaSnapshotWithContext(ctx, mods...)
		m.WithSchemaSnapshots(number, related).Apply(ctx, o)
	})
}

func (m connectionMods) AddSchemaSnapshots(number int, related *SchemaSnapshotTemplate) ConnectionMod {
	return ConnectionModFunc(func(ctx context.Context, o *ConnectionTemplate) {
		o.r.SchemaSnapshots = append(o.r.SchemaSnapshots, &connectionRSchemaSnapshotsR{
			number: number,
			o:      related,
		})
	})
}

func (m connectionMods) AddNewSchemaSnapshots(number int, mods ...SchemaSnapshotMod) ConnectionMod {
	return ConnectionModFunc(func(ctx context.Context, o *ConnectionTemplate) {
		related := o.f.NewSchemaSnapshotWithContext(ctx, mods...)
		m.AddSchemaSnapshots(number, related).Apply(ctx, o)
	})
}

func (m connectionMods) AddExistingSchemaSnapshots(existingModels ...*models.SchemaSnapshot) ConnectionMod {
	return ConnectionModFunc(func(ctx context.Context, o *ConnectionTemplate) {
		for _, em := range existingModels {
			o.r.SchemaSnapshots = append(o.r.SchemaSnapshots, &connectionRSchemaSnapshotsR{
				o: o.f.FromExistingSchemaSnapshot(em),
			})
		}
	})
}

func (m connectionMods) WithoutSchemaSnapshots() ConnectionMod {
	return ConnectionModFunc(func(ctx context.Context, o *ConnectionTemplate) {
		o.r.SchemaSnapshots = nil
	})
}
