// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	models "github.com/Uncensored-Developer/datalk/apps/backend/db/models"
	"github.com/aarondl/opt/omit"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
)

type ConnectionAccessMod interface {
	Apply(context.Context, *ConnectionAccessTemplate)
}

type ConnectionAccessModFunc func(context.Context, *ConnectionAccessTemplate)

func (f ConnectionAccessModFunc) Apply(ctx context.Context, n *ConnectionAccessTemplate) {
	f(ctx, n)
}

type ConnectionAccessModSlice []ConnectionAccessMod

func (mods ConnectionAccessModSlice) Apply(ctx context.Context, n *ConnectionAccessTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// ConnectionAccessTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type ConnectionAccessTemplate struct {
	UserID       func() int32
	ConnectionID func() int32
	CanQuery     func() bool
	AllowWrites  func() bool
	CanManage    func() bool
	GrantedAt    func() time.Time

	r connectionAccessR
	f *Factory

	alreadyPersisted bool
}

type connectionAccessR struct {
	Connection *connectionAccessRConnectionR
	User       *connectionAccessRUserR
}

type connectionAccessRConnectionR struct {
	o *ConnectionTemplate
}
type connectionAccessRUserR struct {
	o *UserTemplate
}

// Apply mods to the ConnectionAccessTemplate
func (o *ConnectionAccessTemplate) Apply(ctx context.Context, mods ...ConnectionAccessMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.ConnectionAccess
// according to the relationships in the template. Nothing is inserted into the db
func (t ConnectionAccessTemplate) setModelRels(o *models.ConnectionAccess) {
	if t.r.Connection != nil {
		rel := t.r.Connection.o.Build()
		o.ConnectionID = rel.ID // h2
		o.R.Connection = rel
		o.R.Loaded.Connection = true
	}

	if t.r.User != nil {
		rel := t.r.User.o.Build()
		o.UserID = rel.ID // h2
		o.R.User = rel
		o.R.Loaded.User = true
	}
}

// BuildSetter returns an *models.ConnectionAccessSetter
// this does nothing with the relationship templates
func (o ConnectionAccessTemplate) BuildSetter() *models.ConnectionAccessSetter {
	m := &models.ConnectionAccessSetter{}

	if o.UserID != nil {
		val := o.UserID()
		m.UserID = omit.From(val)
	}
	if o.ConnectionID != nil {
		val := o.ConnectionID()
		m.ConnectionID = omit.From(val)
	}
	if o.CanQuery != nil {
		val := o.CanQuery()
		m.CanQuery = omit.From(val)
	}
	if o.AllowWrites != nil {
		val := o.AllowWrites()
		m.AllowWrites = omit.From(val)
	}
	if o.CanManage != nil {
		val := o.CanManage()
		m.CanManage = omit.From(val)
	}
	if o.GrantedAt != nil {
		val := o.GrantedAt()
		m.GrantedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.ConnectionAccessSetter
// this does nothing with the relationship templates
func (o ConnectionAccessTemplate) BuildManySetter(number int) []*models.ConnectionAccessSetter {
	m := make([]*models.ConnectionAccessSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.ConnectionAccess
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ConnectionAccessTemplate.Create
func (o ConnectionAccessTemplate) Build() *models.ConnectionAccess {
	m := &models.ConnectionAccess{}

	if o.UserID != nil {
		m.UserID = o.UserID()
	}
	if o.ConnectionID != nil {
		m.ConnectionID = o.ConnectionID()
	}
	if o.CanQuery != nil {
		m.CanQuery = o.CanQuery()
	}
	if o.AllowWrites != nil {
		m.AllowWrites = o.AllowWrites()
	}
	if o.CanManage != nil {
		m.CanManage = o.CanManage()
	}
	if o.GrantedAt != nil {
		m.GrantedAt = o.GrantedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.ConnectionAccessSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ConnectionAccessTemplate.CreateMany
func (o ConnectionAccessTemplate) BuildMany(number int) models.ConnectionAccessSlice {
	m := make(models.ConnectionAccessSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableConnectionAccess(m *models.ConnectionAccessSetter) {
	if !(m.UserID.IsValue()) {
		val := random_int32(nil)
		m.UserID = omit.From(val)
	}
	if !(m.ConnectionID.IsValue()) {
		val := random_int32(nil)
		m.ConnectionID = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.ConnectionAccess
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *ConnectionAccessTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.ConnectionAccess) error {
	var err error

	return err
}

// Create builds a connectionAccess and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *ConnectionAccessTemplate) Create(ctx context.Context, exec bob.Executor) (*models.ConnectionAccess, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableConnectionAccess(opt)

	// Retrieve ancestor models from context to avoid duplicate parent creation.
	// Parents are keyed by "parent_table:child_table:child_rel_name".
	// This works regardless of NoBackReferencing since it only uses child-side metadata.
	mInCreation, _ := modelsInCreationCtx.Value(ctx)

	var rel0 *models.Connection

	if o.r.Connection == nil {
		if parentModel, found := mInCreation["connections:connection_access:connection_access.connection_access_connection_id_fkey"]; found {
			if pModel, ok := parentModel.(*models.Connection); ok {
				rel0 = pModel
			}
		}
	}

	if rel0 == nil {
		if o.r.Connection == nil {
			ConnectionAccessMods.WithNewConnection().Apply(ctx, o)
		}

		if o.r.Connection.o.alreadyPersisted {
			rel0 = o.r.Connection.o.Build()
		} else {
			rel0, err = o.r.Connection.o.Create(ctx, exec)
			if err != nil {
				return nil, err
			}
		}
	}

	opt.ConnectionID = omit.From(rel0.ID)

	var rel1 *models.User

	if o.r.User == nil {
		if parentModel, found := mInCreation["users:connection_access:connection_access.connection_access_user_id_fkey"]; found {
			if pModel, ok := parentModel.(*models.User); ok {
				rel1 = pModel
			}
		}
	}

	if rel1 == nil {
		if o.r.User == nil {
			ConnectionAccessMods.WithNewUser().Apply(ctx, o)
		}

		if o.r.User.o.alreadyPersisted {
			rel1 = o.r.User.o.Build()
		} else {
			rel1, err = o.r.User.o.Create(ctx, exec)
			if err != nil {
				return nil, err
			}
		}
	}

	opt.UserID = omit.From(rel1.ID)

	m, err := models.ConnectionAccesses.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	// Store this model in context for child creates.
	// Key format: "parent_table:child_table:child_rel_name" where child_rel_name is the FK name.
	// We store an entry for every relationship pointing TO this table (where this table is the parent).
	// This works regardless of NoBackReferencing since keys use child-side metadata.
	newMInCreation := make(map[string]any, len(mInCreation)+1)
	for k, v := range mInCreation {
		newMInCreation[k] = v
	}

	ctx = modelsInCreationCtx.WithValue(ctx, newMInCreation)

	m.R.Connection = rel0
	m.R.Loaded.Connection = true
	m.R.User = rel1
	m.R.Loaded.User = true

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a connectionAccess and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *ConnectionAccessTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.ConnectionAccess {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a connectionAccess and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *ConnectionAccessTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.ConnectionAccess {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple connectionAccesses and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o ConnectionAccessTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.ConnectionAccessSlice, error) {
	var err error
	m := make(models.ConnectionAccessSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple connectionAccesses and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o ConnectionAccessTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.ConnectionAccessSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple connectionAccesses and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o ConnectionAccessTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.ConnectionAccessSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// ConnectionAccess has methods that act as mods for the ConnectionAccessTemplate
var ConnectionAccessMods connectionAccessMods

type connectionAccessMods struct{}

func (m connectionAccessMods) RandomizeAllColumns(f *faker.Faker) ConnectionAccessMod {
	return ConnectionAccessModSlice{
		ConnectionAccessMods.RandomUserID(f),
		ConnectionAccessMods.RandomConnectionID(f),
		ConnectionAccessMods.RandomCanQuery(f),
		ConnectionAccessMods.RandomAllowWrites(f),
		ConnectionAccessMods.RandomCanManage(f),
		ConnectionAccessMods.RandomGrantedAt(f),
	}
}

// Set the model columns to this value
func (m connectionAccessMods) UserID(val int32) ConnectionAccessMod {
	return ConnectionAccessModFunc(func(_ context.Context, o *ConnectionAccessTemplate) {
		o.UserID = func() int32 { return val }
	})
}

// Set the Column from the function
func (m connectionAccessMods) UserIDFunc(f func() int32) ConnectionAccessMod {
	return ConnectionAccessModFunc(func(_ context.Context, o *ConnectionAccessTemplate) {
		o.UserID = f
	})
}

// Clear any values for the column
func (m connectionAccessMods) UnsetUserID() ConnectionAccessMod {
	return ConnectionAccessModFunc(func(_ context.Context, o *ConnectionAccessTemplate) {
		o.UserID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m connectionAccessMods) RandomUserID(f *faker.Faker) ConnectionAccessMod {
	return ConnectionAccessModFunc(func(_ context.Context, o *ConnectionAccessTemplate) {
		o.UserID = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m connectionAccessMods) ConnectionID(val int32) ConnectionAccessMod {
	return ConnectionAccessModFunc(func(_ context.Context, o *ConnectionAccessTemplate) {
		o.ConnectionID = func() int32 { return val }
	})
}

// Set the Column from the function
func (m connectionAccessMods) ConnectionIDFunc(f func() int32) ConnectionAccessMod {
	return ConnectionAccessModFunc(func(_ context.Context, o *ConnectionAccessTemplate) {
		o.ConnectionID = f
	})
}

// Clear any values for the column
func (m connectionAccessMods) UnsetConnectionID() ConnectionAccessMod {
	return ConnectionAccessModFunc(func(_ context.Context, o *ConnectionAccessTemplate) {
		o.ConnectionID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m connectionAccessMods) RandomConnectionID(f *faker.Faker) ConnectionAccessMod {
	return ConnectionAccessModFunc(func(_ context.Context, o *ConnectionAccessTemplate) {
		o.ConnectionID = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m connectionAccessMods) CanQuery(val bool) ConnectionAccessMod {
	return ConnectionAccessModFunc(func(_ context.Context, o *ConnectionAccessTemplate) {
		o.CanQuery = func() bool { return val }
	})
}

// Set the Column from the function
func (m connectionAccessMods) CanQueryFunc(f func() bool) ConnectionAccessMod {
	return ConnectionAccessModFunc(func(_ context.Context, o *ConnectionAccessTemplate) {
		o.CanQuery = f
	})
}

// Clear any values for the column
func (m connectionAccessMods) UnsetCanQuery() ConnectionAccessMod {
	return ConnectionAccessModFunc(func(_ context.Context, o *ConnectionAccessTemplate) {
		o.CanQuery = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m connectionAccessMods) RandomCanQuery(f *faker.Faker) ConnectionAccessMod {
	return ConnectionAccessModFunc(func(_ context.Context, o *ConnectionAccessTemplate) {
		o.CanQuery = func() bool {
			return random_bool(f)
		}
	})
}

// Set the model columns to this value
func (m connectionAccessMods) AllowWrites(val bool) ConnectionAccessMod {
	return ConnectionAccessModFunc(func(_ context.Context, o *ConnectionAccessTemplate) {
		o.AllowWrites = func() bool { return val }
	})
}

// Set the Column from the function
func (m connectionAccessMods) AllowWritesFunc(f func() bool) ConnectionAccessMod {
	return ConnectionAccessModFunc(func(_ context.Context, o *ConnectionAccessTemplate) {
		o.AllowWrites = f
	})
}

// Clear any values for the column
func (m connectionAccessMods) UnsetAllowWrites() ConnectionAccessMod {
	return ConnectionAccessModFunc(func(_ context.Context, o *ConnectionAccessTemplate) {
		o.AllowWrites = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m connectionAccessMods) RandomAllowWrites(f *faker.Faker) ConnectionAccessMod {
	return ConnectionAccessModFunc(func(_ context.Context, o *ConnectionAccessTemplate) {
		o.AllowWrites = func() bool {
			return random_bool(f)
		}
	})
}

// Set the model columns to this value
func (m connectionAccessMods) CanManage(val bool) ConnectionAccessMod {
	return ConnectionAccessModFunc(func(_ context.Context, o *ConnectionAccessTemplate) {
		o.CanManage = func() bool { return val }
	})
}

// Set the Column from the function
func (m connectionAccessMods) CanManageFunc(f func() bool) ConnectionAccessMod {
	return ConnectionAccessModFunc(func(_ context.Context, o *ConnectionAccessTemplate) {
		o.CanManage = f
	})
}

// Clear any values for the column
func (m connectionAccessMods) UnsetCanManage() ConnectionAccessMod {
	return ConnectionAccessModFunc(func(_ context.Context, o *ConnectionAccessTemplate) {
		o.CanManage = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m connectionAccessMods) RandomCanManage(f *faker.Faker) ConnectionAccessMod {
	return ConnectionAccessModFunc(func(_ context.Context, o *ConnectionAccessTemplate) {
		o.CanManage = func() bool {
			return random_bool(f)
		}
	})
}

// Set the model columns to this value
func (m connectionAccessMods) GrantedAt(val time.Time) ConnectionAccessMod {
	return ConnectionAccessModFunc(func(_ context.Context, o *ConnectionAccessTemplate) {
		o.GrantedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m connectionAccessMods) GrantedAtFunc(f func() time.Time) ConnectionAccessMod {
	return ConnectionAccessModFunc(func(_ context.Context, o *ConnectionAccessTemplate) {
		o.GrantedAt = f
	})
}

// Clear any values for the column
func (m connectionAccessMods) UnsetGrantedAt() ConnectionAccessMod {
	return ConnectionAccessModFunc(func(_ context.Context, o *ConnectionAccessTemplate) {
		o.GrantedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m connectionAccessMods) RandomGrantedAt(f *faker.Faker) ConnectionAccessMod {
	return ConnectionAccessModFunc(func(_ context.Context, o *ConnectionAccessTemplate) {
		o.GrantedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m connectionAccessMods) WithParentsCascading() ConnectionAccessMod {
	return ConnectionAccessModFunc(func(ctx context.Context, o *ConnectionAccessTemplate) {
		if isDone, _ := connectionAccessWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = connectionAccessWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewConnectionWithContext(ctx, ConnectionMods.WithParentsCascading())
			m.WithConnection(related).Apply(ctx, o)
		}
		{

			related := o.f.NewUserWithContext(ctx, UserMods.WithParentsCascading())
			m.WithUser(related).Apply(ctx, o)
		}
	})
}

func (m connectionAccessMods) WithConnection(rel *ConnectionTemplate) ConnectionAccessMod {
	return ConnectionAccessModFunc(func(ctx context.Context, o *ConnectionAccessTemplate) {
		o.r.Connection = &connectionAccessRConnectionR{
			o: rel,
		}
	})
}

func (m connectionAccessMods) WithNewConnection(mods ...ConnectionMod) ConnectionAccessMod {
	return ConnectionAccessModFunc(func(ctx context.Context, o *ConnectionAccessTemplate) {
		related := o.f.NewConnectionWithContext(ctx, mods...)

		m.WithConnection(related).Apply(ctx, o)
	})
}

func (m connectionAccessMods) WithExistingConnection(em *models.Connection) ConnectionAccessMod {
	return ConnectionAccessModFunc(func(ctx context.Context, o *ConnectionAccessTemplate) {
		o.r.Connection = &connectionAccessRConnectionR{
			o: o.f.fromExistingConnection(ctx, em),
		}
	})
}

func (m connectionAccessMods) WithoutConnection() ConnectionAccessMod {
	return ConnectionAccessModFunc(func(ctx context.Context, o *ConnectionAccessTemplate) {
		o.r.Connection = nil
	})
}

func (m connectionAccessMods) WithUser(rel *UserTemplate) ConnectionAccessMod {
	return ConnectionAccessModFunc(func(ctx context.Context, o *ConnectionAccessTemplate) {
		o.r.User = &connectionAccessRUserR{
			o: rel,
		}
	})
}

func (m connectionAccessMods) WithNewUser(mods ...UserMod) ConnectionAccessMod {
	return ConnectionAccessModFunc(func(ctx context.Context, o *ConnectionAccessTemplate) {
		related := o.f.NewUserWithContext(ctx, mods...)

		m.WithUser(related).Apply(ctx, o)
	})
}

func (m connectionAccessMods) WithExistingUser(em *models.User) ConnectionAccessMod {
	return ConnectionAccessModFunc(func(ctx context.Context, o *ConnectionAccessTemplate) {
		o.r.User = &connectionAccessRUserR{
			o: o.f.fromExistingUser(ctx, em),
		}
	})
}

func (m connectionAccessMods) WithoutUser() ConnectionAccessMod {
	return ConnectionAccessModFunc(func(ctx context.Context, o *ConnectionAccessTemplate) {
		o.r.User = nil
	})
}
