// Code generated by BobGen psql v0.44.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"encoding/json"
	"testing"
	"time"

	models "github.com/Uncensored-Developer/datalk/apps/backend/db/models"
	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/types"
)

type LLMProviderConfigMod interface {
	Apply(context.Context, *LLMProviderConfigTemplate)
}

type LLMProviderConfigModFunc func(context.Context, *LLMProviderConfigTemplate)

func (f LLMProviderConfigModFunc) Apply(ctx context.Context, n *LLMProviderConfigTemplate) {
	f(ctx, n)
}

type LLMProviderConfigModSlice []LLMProviderConfigMod

func (mods LLMProviderConfigModSlice) Apply(ctx context.Context, n *LLMProviderConfigTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// LLMProviderConfigTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type LLMProviderConfigTemplate struct {
	ID          func() int64
	Provider    func() string
	DisplayName func() string
	APIKeyEnc   func() string
	BaseURL     func() null.Val[string]
	IsEnabled   func() bool
	Metadata    func() types.JSON[json.RawMessage]
	CreatedAt   func() time.Time
	UpdatedAt   func() time.Time

	r llmProviderConfigR
	f *Factory

	alreadyPersisted bool
}

type llmProviderConfigR struct {
	ProviderConfigChatMessageLLMCalls []*llmProviderConfigRProviderConfigChatMessageLLMCallsR
	ProviderConfigLLMProviderModels   []*llmProviderConfigRProviderConfigLLMProviderModelsR
}

type llmProviderConfigRProviderConfigChatMessageLLMCallsR struct {
	number int
	o      *ChatMessageLLMCallTemplate
}
type llmProviderConfigRProviderConfigLLMProviderModelsR struct {
	number int
	o      *LLMProviderModelTemplate
}

// Apply mods to the LLMProviderConfigTemplate
func (o *LLMProviderConfigTemplate) Apply(ctx context.Context, mods ...LLMProviderConfigMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.LLMProviderConfig
// according to the relationships in the template. Nothing is inserted into the db
func (t LLMProviderConfigTemplate) setModelRels(o *models.LLMProviderConfig) {
	if t.r.ProviderConfigChatMessageLLMCalls != nil {
		rel := models.ChatMessageLLMCallSlice{}
		for _, r := range t.r.ProviderConfigChatMessageLLMCalls {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.ProviderConfigID = o.ID // h2
			}
			rel = append(rel, related...)
		}
		o.R.ProviderConfigChatMessageLLMCalls = rel
		o.R.Loaded.ProviderConfigChatMessageLLMCalls = true
	}

	if t.r.ProviderConfigLLMProviderModels != nil {
		rel := models.LLMProviderModelSlice{}
		for _, r := range t.r.ProviderConfigLLMProviderModels {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.ProviderConfigID = o.ID // h2
			}
			rel = append(rel, related...)
		}
		o.R.ProviderConfigLLMProviderModels = rel
		o.R.Loaded.ProviderConfigLLMProviderModels = true
	}
}

// BuildSetter returns an *models.LLMProviderConfigSetter
// this does nothing with the relationship templates
func (o LLMProviderConfigTemplate) BuildSetter() *models.LLMProviderConfigSetter {
	m := &models.LLMProviderConfigSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.Provider != nil {
		val := o.Provider()
		m.Provider = omit.From(val)
	}
	if o.DisplayName != nil {
		val := o.DisplayName()
		m.DisplayName = omit.From(val)
	}
	if o.APIKeyEnc != nil {
		val := o.APIKeyEnc()
		m.APIKeyEnc = omit.From(val)
	}
	if o.BaseURL != nil {
		val := o.BaseURL()
		m.BaseURL = omitnull.FromNull(val)
	}
	if o.IsEnabled != nil {
		val := o.IsEnabled()
		m.IsEnabled = omit.From(val)
	}
	if o.Metadata != nil {
		val := o.Metadata()
		m.Metadata = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.LLMProviderConfigSetter
// this does nothing with the relationship templates
func (o LLMProviderConfigTemplate) BuildManySetter(number int) []*models.LLMProviderConfigSetter {
	m := make([]*models.LLMProviderConfigSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.LLMProviderConfig
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use LLMProviderConfigTemplate.Create
func (o LLMProviderConfigTemplate) Build() *models.LLMProviderConfig {
	m := &models.LLMProviderConfig{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Provider != nil {
		m.Provider = o.Provider()
	}
	if o.DisplayName != nil {
		m.DisplayName = o.DisplayName()
	}
	if o.APIKeyEnc != nil {
		m.APIKeyEnc = o.APIKeyEnc()
	}
	if o.BaseURL != nil {
		m.BaseURL = o.BaseURL()
	}
	if o.IsEnabled != nil {
		m.IsEnabled = o.IsEnabled()
	}
	if o.Metadata != nil {
		m.Metadata = o.Metadata()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.LLMProviderConfigSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use LLMProviderConfigTemplate.CreateMany
func (o LLMProviderConfigTemplate) BuildMany(number int) models.LLMProviderConfigSlice {
	m := make(models.LLMProviderConfigSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableLLMProviderConfig(m *models.LLMProviderConfigSetter) {
	if !(m.Provider.IsValue()) {
		val := random_string(nil)
		m.Provider = omit.From(val)
	}
	if !(m.DisplayName.IsValue()) {
		val := random_string(nil)
		m.DisplayName = omit.From(val)
	}
	if !(m.APIKeyEnc.IsValue()) {
		val := random_string(nil)
		m.APIKeyEnc = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.LLMProviderConfig
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *LLMProviderConfigTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.LLMProviderConfig) error {
	var err error

	isProviderConfigChatMessageLLMCallsDone, _ := llmProviderConfigRelProviderConfigChatMessageLLMCallsCtx.Value(ctx)
	if !isProviderConfigChatMessageLLMCallsDone && o.r.ProviderConfigChatMessageLLMCalls != nil {
		ctx = llmProviderConfigRelProviderConfigChatMessageLLMCallsCtx.WithValue(ctx, true)
		for _, r := range o.r.ProviderConfigChatMessageLLMCalls {
			if r.o.alreadyPersisted {
				m.R.ProviderConfigChatMessageLLMCalls = append(m.R.ProviderConfigChatMessageLLMCalls, r.o.Build())
			} else {
				rel0, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachProviderConfigChatMessageLLMCalls(ctx, exec, rel0...)
				if err != nil {
					return err
				}
			}
		}
	}

	isProviderConfigLLMProviderModelsDone, _ := llmProviderConfigRelProviderConfigLLMProviderModelsCtx.Value(ctx)
	if !isProviderConfigLLMProviderModelsDone && o.r.ProviderConfigLLMProviderModels != nil {
		ctx = llmProviderConfigRelProviderConfigLLMProviderModelsCtx.WithValue(ctx, true)
		for _, r := range o.r.ProviderConfigLLMProviderModels {
			if r.o.alreadyPersisted {
				m.R.ProviderConfigLLMProviderModels = append(m.R.ProviderConfigLLMProviderModels, r.o.Build())
			} else {
				rel1, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachProviderConfigLLMProviderModels(ctx, exec, rel1...)
				if err != nil {
					return err
				}
			}
		}
	}

	return err
}

// Create builds a llmProviderConfig and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *LLMProviderConfigTemplate) Create(ctx context.Context, exec bob.Executor) (*models.LLMProviderConfig, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableLLMProviderConfig(opt)

	// Retrieve ancestor models from context to avoid duplicate parent creation.
	// Parents are keyed by "parent_table:child_table:child_rel_name".
	// This works regardless of NoBackReferencing since it only uses child-side metadata.
	mInCreation, _ := modelsInCreationCtx.Value(ctx)

	m, err := models.LLMProviderConfigs.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	// Store this model in context for child creates.
	// Key format: "parent_table:child_table:child_rel_name" where child_rel_name is the FK name.
	// We store an entry for every relationship pointing TO this table (where this table is the parent).
	// This works regardless of NoBackReferencing since keys use child-side metadata.
	newMInCreation := make(map[string]any, len(mInCreation)+1)
	for k, v := range mInCreation {
		newMInCreation[k] = v
	}
	newMInCreation["llm_provider_configs:chat_message_llm_calls:chat_message_llm_calls.chat_message_llm_calls_provider_config_id_fkey"] = m
	newMInCreation["llm_provider_configs:llm_provider_models:llm_provider_models.llm_provider_models_provider_config_id_fkey"] = m

	ctx = modelsInCreationCtx.WithValue(ctx, newMInCreation)

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a llmProviderConfig and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *LLMProviderConfigTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.LLMProviderConfig {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a llmProviderConfig and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *LLMProviderConfigTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.LLMProviderConfig {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple llmProviderConfigs and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o LLMProviderConfigTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.LLMProviderConfigSlice, error) {
	var err error
	m := make(models.LLMProviderConfigSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple llmProviderConfigs and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o LLMProviderConfigTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.LLMProviderConfigSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple llmProviderConfigs and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o LLMProviderConfigTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.LLMProviderConfigSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// LLMProviderConfig has methods that act as mods for the LLMProviderConfigTemplate
var LLMProviderConfigMods llmProviderConfigMods

type llmProviderConfigMods struct{}

func (m llmProviderConfigMods) RandomizeAllColumns(f *faker.Faker) LLMProviderConfigMod {
	return LLMProviderConfigModSlice{
		LLMProviderConfigMods.RandomID(f),
		LLMProviderConfigMods.RandomProvider(f),
		LLMProviderConfigMods.RandomDisplayName(f),
		LLMProviderConfigMods.RandomAPIKeyEnc(f),
		LLMProviderConfigMods.RandomBaseURL(f),
		LLMProviderConfigMods.RandomIsEnabled(f),
		LLMProviderConfigMods.RandomMetadata(f),
		LLMProviderConfigMods.RandomCreatedAt(f),
		LLMProviderConfigMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m llmProviderConfigMods) ID(val int64) LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(_ context.Context, o *LLMProviderConfigTemplate) {
		o.ID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m llmProviderConfigMods) IDFunc(f func() int64) LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(_ context.Context, o *LLMProviderConfigTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m llmProviderConfigMods) UnsetID() LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(_ context.Context, o *LLMProviderConfigTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m llmProviderConfigMods) RandomID(f *faker.Faker) LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(_ context.Context, o *LLMProviderConfigTemplate) {
		o.ID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m llmProviderConfigMods) Provider(val string) LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(_ context.Context, o *LLMProviderConfigTemplate) {
		o.Provider = func() string { return val }
	})
}

// Set the Column from the function
func (m llmProviderConfigMods) ProviderFunc(f func() string) LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(_ context.Context, o *LLMProviderConfigTemplate) {
		o.Provider = f
	})
}

// Clear any values for the column
func (m llmProviderConfigMods) UnsetProvider() LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(_ context.Context, o *LLMProviderConfigTemplate) {
		o.Provider = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m llmProviderConfigMods) RandomProvider(f *faker.Faker) LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(_ context.Context, o *LLMProviderConfigTemplate) {
		o.Provider = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m llmProviderConfigMods) DisplayName(val string) LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(_ context.Context, o *LLMProviderConfigTemplate) {
		o.DisplayName = func() string { return val }
	})
}

// Set the Column from the function
func (m llmProviderConfigMods) DisplayNameFunc(f func() string) LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(_ context.Context, o *LLMProviderConfigTemplate) {
		o.DisplayName = f
	})
}

// Clear any values for the column
func (m llmProviderConfigMods) UnsetDisplayName() LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(_ context.Context, o *LLMProviderConfigTemplate) {
		o.DisplayName = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m llmProviderConfigMods) RandomDisplayName(f *faker.Faker) LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(_ context.Context, o *LLMProviderConfigTemplate) {
		o.DisplayName = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m llmProviderConfigMods) APIKeyEnc(val string) LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(_ context.Context, o *LLMProviderConfigTemplate) {
		o.APIKeyEnc = func() string { return val }
	})
}

// Set the Column from the function
func (m llmProviderConfigMods) APIKeyEncFunc(f func() string) LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(_ context.Context, o *LLMProviderConfigTemplate) {
		o.APIKeyEnc = f
	})
}

// Clear any values for the column
func (m llmProviderConfigMods) UnsetAPIKeyEnc() LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(_ context.Context, o *LLMProviderConfigTemplate) {
		o.APIKeyEnc = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m llmProviderConfigMods) RandomAPIKeyEnc(f *faker.Faker) LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(_ context.Context, o *LLMProviderConfigTemplate) {
		o.APIKeyEnc = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m llmProviderConfigMods) BaseURL(val null.Val[string]) LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(_ context.Context, o *LLMProviderConfigTemplate) {
		o.BaseURL = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m llmProviderConfigMods) BaseURLFunc(f func() null.Val[string]) LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(_ context.Context, o *LLMProviderConfigTemplate) {
		o.BaseURL = f
	})
}

// Clear any values for the column
func (m llmProviderConfigMods) UnsetBaseURL() LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(_ context.Context, o *LLMProviderConfigTemplate) {
		o.BaseURL = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m llmProviderConfigMods) RandomBaseURL(f *faker.Faker) LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(_ context.Context, o *LLMProviderConfigTemplate) {
		o.BaseURL = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m llmProviderConfigMods) RandomBaseURLNotNull(f *faker.Faker) LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(_ context.Context, o *LLMProviderConfigTemplate) {
		o.BaseURL = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m llmProviderConfigMods) IsEnabled(val bool) LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(_ context.Context, o *LLMProviderConfigTemplate) {
		o.IsEnabled = func() bool { return val }
	})
}

// Set the Column from the function
func (m llmProviderConfigMods) IsEnabledFunc(f func() bool) LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(_ context.Context, o *LLMProviderConfigTemplate) {
		o.IsEnabled = f
	})
}

// Clear any values for the column
func (m llmProviderConfigMods) UnsetIsEnabled() LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(_ context.Context, o *LLMProviderConfigTemplate) {
		o.IsEnabled = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m llmProviderConfigMods) RandomIsEnabled(f *faker.Faker) LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(_ context.Context, o *LLMProviderConfigTemplate) {
		o.IsEnabled = func() bool {
			return random_bool(f)
		}
	})
}

// Set the model columns to this value
func (m llmProviderConfigMods) Metadata(val types.JSON[json.RawMessage]) LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(_ context.Context, o *LLMProviderConfigTemplate) {
		o.Metadata = func() types.JSON[json.RawMessage] { return val }
	})
}

// Set the Column from the function
func (m llmProviderConfigMods) MetadataFunc(f func() types.JSON[json.RawMessage]) LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(_ context.Context, o *LLMProviderConfigTemplate) {
		o.Metadata = f
	})
}

// Clear any values for the column
func (m llmProviderConfigMods) UnsetMetadata() LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(_ context.Context, o *LLMProviderConfigTemplate) {
		o.Metadata = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m llmProviderConfigMods) RandomMetadata(f *faker.Faker) LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(_ context.Context, o *LLMProviderConfigTemplate) {
		o.Metadata = func() types.JSON[json.RawMessage] {
			return random_types_JSON_json_RawMessage_(f)
		}
	})
}

// Set the model columns to this value
func (m llmProviderConfigMods) CreatedAt(val time.Time) LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(_ context.Context, o *LLMProviderConfigTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m llmProviderConfigMods) CreatedAtFunc(f func() time.Time) LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(_ context.Context, o *LLMProviderConfigTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m llmProviderConfigMods) UnsetCreatedAt() LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(_ context.Context, o *LLMProviderConfigTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m llmProviderConfigMods) RandomCreatedAt(f *faker.Faker) LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(_ context.Context, o *LLMProviderConfigTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m llmProviderConfigMods) UpdatedAt(val time.Time) LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(_ context.Context, o *LLMProviderConfigTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m llmProviderConfigMods) UpdatedAtFunc(f func() time.Time) LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(_ context.Context, o *LLMProviderConfigTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m llmProviderConfigMods) UnsetUpdatedAt() LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(_ context.Context, o *LLMProviderConfigTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m llmProviderConfigMods) RandomUpdatedAt(f *faker.Faker) LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(_ context.Context, o *LLMProviderConfigTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m llmProviderConfigMods) WithParentsCascading() LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(ctx context.Context, o *LLMProviderConfigTemplate) {
		if isDone, _ := llmProviderConfigWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = llmProviderConfigWithParentsCascadingCtx.WithValue(ctx, true)
	})
}

func (m llmProviderConfigMods) WithProviderConfigChatMessageLLMCalls(number int, related *ChatMessageLLMCallTemplate) LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(ctx context.Context, o *LLMProviderConfigTemplate) {
		o.r.ProviderConfigChatMessageLLMCalls = []*llmProviderConfigRProviderConfigChatMessageLLMCallsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m llmProviderConfigMods) WithNewProviderConfigChatMessageLLMCalls(number int, mods ...ChatMessageLLMCallMod) LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(ctx context.Context, o *LLMProviderConfigTemplate) {
		related := o.f.NewChatMessageLLMCallWithContext(ctx, mods...)
		m.WithProviderConfigChatMessageLLMCalls(number, related).Apply(ctx, o)
	})
}

func (m llmProviderConfigMods) AddProviderConfigChatMessageLLMCalls(number int, related *ChatMessageLLMCallTemplate) LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(ctx context.Context, o *LLMProviderConfigTemplate) {
		o.r.ProviderConfigChatMessageLLMCalls = append(o.r.ProviderConfigChatMessageLLMCalls, &llmProviderConfigRProviderConfigChatMessageLLMCallsR{
			number: number,
			o:      related,
		})
	})
}

func (m llmProviderConfigMods) AddNewProviderConfigChatMessageLLMCalls(number int, mods ...ChatMessageLLMCallMod) LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(ctx context.Context, o *LLMProviderConfigTemplate) {
		related := o.f.NewChatMessageLLMCallWithContext(ctx, mods...)
		m.AddProviderConfigChatMessageLLMCalls(number, related).Apply(ctx, o)
	})
}

func (m llmProviderConfigMods) AddExistingProviderConfigChatMessageLLMCalls(existingModels ...*models.ChatMessageLLMCall) LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(ctx context.Context, o *LLMProviderConfigTemplate) {
		for _, em := range existingModels {
			o.r.ProviderConfigChatMessageLLMCalls = append(o.r.ProviderConfigChatMessageLLMCalls, &llmProviderConfigRProviderConfigChatMessageLLMCallsR{
				o: o.f.fromExistingChatMessageLLMCall(ctx, em),
			})
		}
	})
}

func (m llmProviderConfigMods) WithoutProviderConfigChatMessageLLMCalls() LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(ctx context.Context, o *LLMProviderConfigTemplate) {
		o.r.ProviderConfigChatMessageLLMCalls = nil
	})
}

func (m llmProviderConfigMods) WithProviderConfigLLMProviderModels(number int, related *LLMProviderModelTemplate) LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(ctx context.Context, o *LLMProviderConfigTemplate) {
		o.r.ProviderConfigLLMProviderModels = []*llmProviderConfigRProviderConfigLLMProviderModelsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m llmProviderConfigMods) WithNewProviderConfigLLMProviderModels(number int, mods ...LLMProviderModelMod) LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(ctx context.Context, o *LLMProviderConfigTemplate) {
		related := o.f.NewLLMProviderModelWithContext(ctx, mods...)
		m.WithProviderConfigLLMProviderModels(number, related).Apply(ctx, o)
	})
}

func (m llmProviderConfigMods) AddProviderConfigLLMProviderModels(number int, related *LLMProviderModelTemplate) LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(ctx context.Context, o *LLMProviderConfigTemplate) {
		o.r.ProviderConfigLLMProviderModels = append(o.r.ProviderConfigLLMProviderModels, &llmProviderConfigRProviderConfigLLMProviderModelsR{
			number: number,
			o:      related,
		})
	})
}

func (m llmProviderConfigMods) AddNewProviderConfigLLMProviderModels(number int, mods ...LLMProviderModelMod) LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(ctx context.Context, o *LLMProviderConfigTemplate) {
		related := o.f.NewLLMProviderModelWithContext(ctx, mods...)
		m.AddProviderConfigLLMProviderModels(number, related).Apply(ctx, o)
	})
}

func (m llmProviderConfigMods) AddExistingProviderConfigLLMProviderModels(existingModels ...*models.LLMProviderModel) LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(ctx context.Context, o *LLMProviderConfigTemplate) {
		for _, em := range existingModels {
			o.r.ProviderConfigLLMProviderModels = append(o.r.ProviderConfigLLMProviderModels, &llmProviderConfigRProviderConfigLLMProviderModelsR{
				o: o.f.fromExistingLLMProviderModel(ctx, em),
			})
		}
	})
}

func (m llmProviderConfigMods) WithoutProviderConfigLLMProviderModels() LLMProviderConfigMod {
	return LLMProviderConfigModFunc(func(ctx context.Context, o *LLMProviderConfigTemplate) {
		o.r.ProviderConfigLLMProviderModels = nil
	})
}
