// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"encoding/json"
	"testing"
	"time"

	models "github.com/Uncensored-Developer/datalk/apps/backend/db/models"
	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/jaswdr/faker/v2"
	pgvector "github.com/pgvector/pgvector-go"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/types"
)

type SchemaChunkMod interface {
	Apply(context.Context, *SchemaChunkTemplate)
}

type SchemaChunkModFunc func(context.Context, *SchemaChunkTemplate)

func (f SchemaChunkModFunc) Apply(ctx context.Context, n *SchemaChunkTemplate) {
	f(ctx, n)
}

type SchemaChunkModSlice []SchemaChunkMod

func (mods SchemaChunkModSlice) Apply(ctx context.Context, n *SchemaChunkTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// SchemaChunkTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type SchemaChunkTemplate struct {
	ID           func() int64
	SnapshotID   func() int32
	ConnectionID func() int32
	NamespaceID  func() int32
	ObjectType   func() string
	ObjectName   func() string
	SchemaJSON   func() types.JSON[json.RawMessage]
	Content      func() string
	Embedding    func() null.Val[pgvector.Vector]
	Metadata     func() types.JSON[json.RawMessage]
	CreatedAt    func() time.Time

	r schemaChunkR
	f *Factory

	alreadyPersisted bool
}

type schemaChunkR struct {
	Connection                   *schemaChunkRConnectionR
	NamespaceConnectionNamespace *schemaChunkRNamespaceConnectionNamespaceR
	SnapshotSchemaSnapshot       *schemaChunkRSnapshotSchemaSnapshotR
}

type schemaChunkRConnectionR struct {
	o *ConnectionTemplate
}
type schemaChunkRNamespaceConnectionNamespaceR struct {
	o *ConnectionNamespaceTemplate
}
type schemaChunkRSnapshotSchemaSnapshotR struct {
	o *SchemaSnapshotTemplate
}

// Apply mods to the SchemaChunkTemplate
func (o *SchemaChunkTemplate) Apply(ctx context.Context, mods ...SchemaChunkMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.SchemaChunk
// according to the relationships in the template. Nothing is inserted into the db
func (t SchemaChunkTemplate) setModelRels(o *models.SchemaChunk) {
	if t.r.Connection != nil {
		rel := t.r.Connection.o.Build()
		o.ConnectionID = rel.ID // h2
		o.R.Connection = rel
	}

	if t.r.NamespaceConnectionNamespace != nil {
		rel := t.r.NamespaceConnectionNamespace.o.Build()
		o.NamespaceID = rel.ID // h2
		o.R.NamespaceConnectionNamespace = rel
	}

	if t.r.SnapshotSchemaSnapshot != nil {
		rel := t.r.SnapshotSchemaSnapshot.o.Build()
		o.SnapshotID = rel.ID // h2
		o.R.SnapshotSchemaSnapshot = rel
	}
}

// BuildSetter returns an *models.SchemaChunkSetter
// this does nothing with the relationship templates
func (o SchemaChunkTemplate) BuildSetter() *models.SchemaChunkSetter {
	m := &models.SchemaChunkSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.SnapshotID != nil {
		val := o.SnapshotID()
		m.SnapshotID = omit.From(val)
	}
	if o.ConnectionID != nil {
		val := o.ConnectionID()
		m.ConnectionID = omit.From(val)
	}
	if o.NamespaceID != nil {
		val := o.NamespaceID()
		m.NamespaceID = omit.From(val)
	}
	if o.ObjectType != nil {
		val := o.ObjectType()
		m.ObjectType = omit.From(val)
	}
	if o.ObjectName != nil {
		val := o.ObjectName()
		m.ObjectName = omit.From(val)
	}
	if o.SchemaJSON != nil {
		val := o.SchemaJSON()
		m.SchemaJSON = omit.From(val)
	}
	if o.Content != nil {
		val := o.Content()
		m.Content = omit.From(val)
	}
	if o.Embedding != nil {
		val := o.Embedding()
		m.Embedding = omitnull.FromNull(val)
	}
	if o.Metadata != nil {
		val := o.Metadata()
		m.Metadata = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.SchemaChunkSetter
// this does nothing with the relationship templates
func (o SchemaChunkTemplate) BuildManySetter(number int) []*models.SchemaChunkSetter {
	m := make([]*models.SchemaChunkSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.SchemaChunk
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use SchemaChunkTemplate.Create
func (o SchemaChunkTemplate) Build() *models.SchemaChunk {
	m := &models.SchemaChunk{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.SnapshotID != nil {
		m.SnapshotID = o.SnapshotID()
	}
	if o.ConnectionID != nil {
		m.ConnectionID = o.ConnectionID()
	}
	if o.NamespaceID != nil {
		m.NamespaceID = o.NamespaceID()
	}
	if o.ObjectType != nil {
		m.ObjectType = o.ObjectType()
	}
	if o.ObjectName != nil {
		m.ObjectName = o.ObjectName()
	}
	if o.SchemaJSON != nil {
		m.SchemaJSON = o.SchemaJSON()
	}
	if o.Content != nil {
		m.Content = o.Content()
	}
	if o.Embedding != nil {
		m.Embedding = o.Embedding()
	}
	if o.Metadata != nil {
		m.Metadata = o.Metadata()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.SchemaChunkSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use SchemaChunkTemplate.CreateMany
func (o SchemaChunkTemplate) BuildMany(number int) models.SchemaChunkSlice {
	m := make(models.SchemaChunkSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableSchemaChunk(m *models.SchemaChunkSetter) {
	if !(m.SnapshotID.IsValue()) {
		val := random_int32(nil)
		m.SnapshotID = omit.From(val)
	}
	if !(m.ConnectionID.IsValue()) {
		val := random_int32(nil)
		m.ConnectionID = omit.From(val)
	}
	if !(m.NamespaceID.IsValue()) {
		val := random_int32(nil)
		m.NamespaceID = omit.From(val)
	}
	if !(m.ObjectType.IsValue()) {
		val := random_string(nil)
		m.ObjectType = omit.From(val)
	}
	if !(m.ObjectName.IsValue()) {
		val := random_string(nil)
		m.ObjectName = omit.From(val)
	}
	if !(m.SchemaJSON.IsValue()) {
		val := random_types_JSON_json_RawMessage_(nil)
		m.SchemaJSON = omit.From(val)
	}
	if !(m.Content.IsValue()) {
		val := random_string(nil)
		m.Content = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.SchemaChunk
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *SchemaChunkTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.SchemaChunk) error {
	var err error

	return err
}

// Create builds a schemaChunk and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *SchemaChunkTemplate) Create(ctx context.Context, exec bob.Executor) (*models.SchemaChunk, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableSchemaChunk(opt)

	if o.r.Connection == nil {
		SchemaChunkMods.WithNewConnection().Apply(ctx, o)
	}

	var rel0 *models.Connection

	if o.r.Connection.o.alreadyPersisted {
		rel0 = o.r.Connection.o.Build()
	} else {
		rel0, err = o.r.Connection.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.ConnectionID = omit.From(rel0.ID)

	if o.r.NamespaceConnectionNamespace == nil {
		SchemaChunkMods.WithNewNamespaceConnectionNamespace().Apply(ctx, o)
	}

	var rel1 *models.ConnectionNamespace

	if o.r.NamespaceConnectionNamespace.o.alreadyPersisted {
		rel1 = o.r.NamespaceConnectionNamespace.o.Build()
	} else {
		rel1, err = o.r.NamespaceConnectionNamespace.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.NamespaceID = omit.From(rel1.ID)

	if o.r.SnapshotSchemaSnapshot == nil {
		SchemaChunkMods.WithNewSnapshotSchemaSnapshot().Apply(ctx, o)
	}

	var rel2 *models.SchemaSnapshot

	if o.r.SnapshotSchemaSnapshot.o.alreadyPersisted {
		rel2 = o.r.SnapshotSchemaSnapshot.o.Build()
	} else {
		rel2, err = o.r.SnapshotSchemaSnapshot.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.SnapshotID = omit.From(rel2.ID)

	m, err := models.SchemaChunks.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.Connection = rel0
	m.R.NamespaceConnectionNamespace = rel1
	m.R.SnapshotSchemaSnapshot = rel2

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a schemaChunk and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *SchemaChunkTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.SchemaChunk {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a schemaChunk and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *SchemaChunkTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.SchemaChunk {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple schemaChunks and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o SchemaChunkTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.SchemaChunkSlice, error) {
	var err error
	m := make(models.SchemaChunkSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple schemaChunks and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o SchemaChunkTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.SchemaChunkSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple schemaChunks and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o SchemaChunkTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.SchemaChunkSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// SchemaChunk has methods that act as mods for the SchemaChunkTemplate
var SchemaChunkMods schemaChunkMods

type schemaChunkMods struct{}

func (m schemaChunkMods) RandomizeAllColumns(f *faker.Faker) SchemaChunkMod {
	return SchemaChunkModSlice{
		SchemaChunkMods.RandomID(f),
		SchemaChunkMods.RandomSnapshotID(f),
		SchemaChunkMods.RandomConnectionID(f),
		SchemaChunkMods.RandomNamespaceID(f),
		SchemaChunkMods.RandomObjectType(f),
		SchemaChunkMods.RandomObjectName(f),
		SchemaChunkMods.RandomSchemaJSON(f),
		SchemaChunkMods.RandomContent(f),
		SchemaChunkMods.RandomEmbedding(f),
		SchemaChunkMods.RandomMetadata(f),
		SchemaChunkMods.RandomCreatedAt(f),
	}
}

// Set the model columns to this value
func (m schemaChunkMods) ID(val int64) SchemaChunkMod {
	return SchemaChunkModFunc(func(_ context.Context, o *SchemaChunkTemplate) {
		o.ID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m schemaChunkMods) IDFunc(f func() int64) SchemaChunkMod {
	return SchemaChunkModFunc(func(_ context.Context, o *SchemaChunkTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m schemaChunkMods) UnsetID() SchemaChunkMod {
	return SchemaChunkModFunc(func(_ context.Context, o *SchemaChunkTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m schemaChunkMods) RandomID(f *faker.Faker) SchemaChunkMod {
	return SchemaChunkModFunc(func(_ context.Context, o *SchemaChunkTemplate) {
		o.ID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m schemaChunkMods) SnapshotID(val int32) SchemaChunkMod {
	return SchemaChunkModFunc(func(_ context.Context, o *SchemaChunkTemplate) {
		o.SnapshotID = func() int32 { return val }
	})
}

// Set the Column from the function
func (m schemaChunkMods) SnapshotIDFunc(f func() int32) SchemaChunkMod {
	return SchemaChunkModFunc(func(_ context.Context, o *SchemaChunkTemplate) {
		o.SnapshotID = f
	})
}

// Clear any values for the column
func (m schemaChunkMods) UnsetSnapshotID() SchemaChunkMod {
	return SchemaChunkModFunc(func(_ context.Context, o *SchemaChunkTemplate) {
		o.SnapshotID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m schemaChunkMods) RandomSnapshotID(f *faker.Faker) SchemaChunkMod {
	return SchemaChunkModFunc(func(_ context.Context, o *SchemaChunkTemplate) {
		o.SnapshotID = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m schemaChunkMods) ConnectionID(val int32) SchemaChunkMod {
	return SchemaChunkModFunc(func(_ context.Context, o *SchemaChunkTemplate) {
		o.ConnectionID = func() int32 { return val }
	})
}

// Set the Column from the function
func (m schemaChunkMods) ConnectionIDFunc(f func() int32) SchemaChunkMod {
	return SchemaChunkModFunc(func(_ context.Context, o *SchemaChunkTemplate) {
		o.ConnectionID = f
	})
}

// Clear any values for the column
func (m schemaChunkMods) UnsetConnectionID() SchemaChunkMod {
	return SchemaChunkModFunc(func(_ context.Context, o *SchemaChunkTemplate) {
		o.ConnectionID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m schemaChunkMods) RandomConnectionID(f *faker.Faker) SchemaChunkMod {
	return SchemaChunkModFunc(func(_ context.Context, o *SchemaChunkTemplate) {
		o.ConnectionID = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m schemaChunkMods) NamespaceID(val int32) SchemaChunkMod {
	return SchemaChunkModFunc(func(_ context.Context, o *SchemaChunkTemplate) {
		o.NamespaceID = func() int32 { return val }
	})
}

// Set the Column from the function
func (m schemaChunkMods) NamespaceIDFunc(f func() int32) SchemaChunkMod {
	return SchemaChunkModFunc(func(_ context.Context, o *SchemaChunkTemplate) {
		o.NamespaceID = f
	})
}

// Clear any values for the column
func (m schemaChunkMods) UnsetNamespaceID() SchemaChunkMod {
	return SchemaChunkModFunc(func(_ context.Context, o *SchemaChunkTemplate) {
		o.NamespaceID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m schemaChunkMods) RandomNamespaceID(f *faker.Faker) SchemaChunkMod {
	return SchemaChunkModFunc(func(_ context.Context, o *SchemaChunkTemplate) {
		o.NamespaceID = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m schemaChunkMods) ObjectType(val string) SchemaChunkMod {
	return SchemaChunkModFunc(func(_ context.Context, o *SchemaChunkTemplate) {
		o.ObjectType = func() string { return val }
	})
}

// Set the Column from the function
func (m schemaChunkMods) ObjectTypeFunc(f func() string) SchemaChunkMod {
	return SchemaChunkModFunc(func(_ context.Context, o *SchemaChunkTemplate) {
		o.ObjectType = f
	})
}

// Clear any values for the column
func (m schemaChunkMods) UnsetObjectType() SchemaChunkMod {
	return SchemaChunkModFunc(func(_ context.Context, o *SchemaChunkTemplate) {
		o.ObjectType = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m schemaChunkMods) RandomObjectType(f *faker.Faker) SchemaChunkMod {
	return SchemaChunkModFunc(func(_ context.Context, o *SchemaChunkTemplate) {
		o.ObjectType = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m schemaChunkMods) ObjectName(val string) SchemaChunkMod {
	return SchemaChunkModFunc(func(_ context.Context, o *SchemaChunkTemplate) {
		o.ObjectName = func() string { return val }
	})
}

// Set the Column from the function
func (m schemaChunkMods) ObjectNameFunc(f func() string) SchemaChunkMod {
	return SchemaChunkModFunc(func(_ context.Context, o *SchemaChunkTemplate) {
		o.ObjectName = f
	})
}

// Clear any values for the column
func (m schemaChunkMods) UnsetObjectName() SchemaChunkMod {
	return SchemaChunkModFunc(func(_ context.Context, o *SchemaChunkTemplate) {
		o.ObjectName = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m schemaChunkMods) RandomObjectName(f *faker.Faker) SchemaChunkMod {
	return SchemaChunkModFunc(func(_ context.Context, o *SchemaChunkTemplate) {
		o.ObjectName = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m schemaChunkMods) SchemaJSON(val types.JSON[json.RawMessage]) SchemaChunkMod {
	return SchemaChunkModFunc(func(_ context.Context, o *SchemaChunkTemplate) {
		o.SchemaJSON = func() types.JSON[json.RawMessage] { return val }
	})
}

// Set the Column from the function
func (m schemaChunkMods) SchemaJSONFunc(f func() types.JSON[json.RawMessage]) SchemaChunkMod {
	return SchemaChunkModFunc(func(_ context.Context, o *SchemaChunkTemplate) {
		o.SchemaJSON = f
	})
}

// Clear any values for the column
func (m schemaChunkMods) UnsetSchemaJSON() SchemaChunkMod {
	return SchemaChunkModFunc(func(_ context.Context, o *SchemaChunkTemplate) {
		o.SchemaJSON = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m schemaChunkMods) RandomSchemaJSON(f *faker.Faker) SchemaChunkMod {
	return SchemaChunkModFunc(func(_ context.Context, o *SchemaChunkTemplate) {
		o.SchemaJSON = func() types.JSON[json.RawMessage] {
			return random_types_JSON_json_RawMessage_(f)
		}
	})
}

// Set the model columns to this value
func (m schemaChunkMods) Content(val string) SchemaChunkMod {
	return SchemaChunkModFunc(func(_ context.Context, o *SchemaChunkTemplate) {
		o.Content = func() string { return val }
	})
}

// Set the Column from the function
func (m schemaChunkMods) ContentFunc(f func() string) SchemaChunkMod {
	return SchemaChunkModFunc(func(_ context.Context, o *SchemaChunkTemplate) {
		o.Content = f
	})
}

// Clear any values for the column
func (m schemaChunkMods) UnsetContent() SchemaChunkMod {
	return SchemaChunkModFunc(func(_ context.Context, o *SchemaChunkTemplate) {
		o.Content = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m schemaChunkMods) RandomContent(f *faker.Faker) SchemaChunkMod {
	return SchemaChunkModFunc(func(_ context.Context, o *SchemaChunkTemplate) {
		o.Content = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m schemaChunkMods) Embedding(val null.Val[pgvector.Vector]) SchemaChunkMod {
	return SchemaChunkModFunc(func(_ context.Context, o *SchemaChunkTemplate) {
		o.Embedding = func() null.Val[pgvector.Vector] { return val }
	})
}

// Set the Column from the function
func (m schemaChunkMods) EmbeddingFunc(f func() null.Val[pgvector.Vector]) SchemaChunkMod {
	return SchemaChunkModFunc(func(_ context.Context, o *SchemaChunkTemplate) {
		o.Embedding = f
	})
}

// Clear any values for the column
func (m schemaChunkMods) UnsetEmbedding() SchemaChunkMod {
	return SchemaChunkModFunc(func(_ context.Context, o *SchemaChunkTemplate) {
		o.Embedding = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m schemaChunkMods) RandomEmbedding(f *faker.Faker) SchemaChunkMod {
	return SchemaChunkModFunc(func(_ context.Context, o *SchemaChunkTemplate) {
		o.Embedding = func() null.Val[pgvector.Vector] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_pgvector_Vector(f, "1536")
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m schemaChunkMods) RandomEmbeddingNotNull(f *faker.Faker) SchemaChunkMod {
	return SchemaChunkModFunc(func(_ context.Context, o *SchemaChunkTemplate) {
		o.Embedding = func() null.Val[pgvector.Vector] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_pgvector_Vector(f, "1536")
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m schemaChunkMods) Metadata(val types.JSON[json.RawMessage]) SchemaChunkMod {
	return SchemaChunkModFunc(func(_ context.Context, o *SchemaChunkTemplate) {
		o.Metadata = func() types.JSON[json.RawMessage] { return val }
	})
}

// Set the Column from the function
func (m schemaChunkMods) MetadataFunc(f func() types.JSON[json.RawMessage]) SchemaChunkMod {
	return SchemaChunkModFunc(func(_ context.Context, o *SchemaChunkTemplate) {
		o.Metadata = f
	})
}

// Clear any values for the column
func (m schemaChunkMods) UnsetMetadata() SchemaChunkMod {
	return SchemaChunkModFunc(func(_ context.Context, o *SchemaChunkTemplate) {
		o.Metadata = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m schemaChunkMods) RandomMetadata(f *faker.Faker) SchemaChunkMod {
	return SchemaChunkModFunc(func(_ context.Context, o *SchemaChunkTemplate) {
		o.Metadata = func() types.JSON[json.RawMessage] {
			return random_types_JSON_json_RawMessage_(f)
		}
	})
}

// Set the model columns to this value
func (m schemaChunkMods) CreatedAt(val time.Time) SchemaChunkMod {
	return SchemaChunkModFunc(func(_ context.Context, o *SchemaChunkTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m schemaChunkMods) CreatedAtFunc(f func() time.Time) SchemaChunkMod {
	return SchemaChunkModFunc(func(_ context.Context, o *SchemaChunkTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m schemaChunkMods) UnsetCreatedAt() SchemaChunkMod {
	return SchemaChunkModFunc(func(_ context.Context, o *SchemaChunkTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m schemaChunkMods) RandomCreatedAt(f *faker.Faker) SchemaChunkMod {
	return SchemaChunkModFunc(func(_ context.Context, o *SchemaChunkTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m schemaChunkMods) WithParentsCascading() SchemaChunkMod {
	return SchemaChunkModFunc(func(ctx context.Context, o *SchemaChunkTemplate) {
		if isDone, _ := schemaChunkWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = schemaChunkWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewConnectionWithContext(ctx, ConnectionMods.WithParentsCascading())
			m.WithConnection(related).Apply(ctx, o)
		}
		{

			related := o.f.NewConnectionNamespaceWithContext(ctx, ConnectionNamespaceMods.WithParentsCascading())
			m.WithNamespaceConnectionNamespace(related).Apply(ctx, o)
		}
		{

			related := o.f.NewSchemaSnapshotWithContext(ctx, SchemaSnapshotMods.WithParentsCascading())
			m.WithSnapshotSchemaSnapshot(related).Apply(ctx, o)
		}
	})
}

func (m schemaChunkMods) WithConnection(rel *ConnectionTemplate) SchemaChunkMod {
	return SchemaChunkModFunc(func(ctx context.Context, o *SchemaChunkTemplate) {
		o.r.Connection = &schemaChunkRConnectionR{
			o: rel,
		}
	})
}

func (m schemaChunkMods) WithNewConnection(mods ...ConnectionMod) SchemaChunkMod {
	return SchemaChunkModFunc(func(ctx context.Context, o *SchemaChunkTemplate) {
		related := o.f.NewConnectionWithContext(ctx, mods...)

		m.WithConnection(related).Apply(ctx, o)
	})
}

func (m schemaChunkMods) WithExistingConnection(em *models.Connection) SchemaChunkMod {
	return SchemaChunkModFunc(func(ctx context.Context, o *SchemaChunkTemplate) {
		o.r.Connection = &schemaChunkRConnectionR{
			o: o.f.FromExistingConnection(em),
		}
	})
}

func (m schemaChunkMods) WithoutConnection() SchemaChunkMod {
	return SchemaChunkModFunc(func(ctx context.Context, o *SchemaChunkTemplate) {
		o.r.Connection = nil
	})
}

func (m schemaChunkMods) WithNamespaceConnectionNamespace(rel *ConnectionNamespaceTemplate) SchemaChunkMod {
	return SchemaChunkModFunc(func(ctx context.Context, o *SchemaChunkTemplate) {
		o.r.NamespaceConnectionNamespace = &schemaChunkRNamespaceConnectionNamespaceR{
			o: rel,
		}
	})
}

func (m schemaChunkMods) WithNewNamespaceConnectionNamespace(mods ...ConnectionNamespaceMod) SchemaChunkMod {
	return SchemaChunkModFunc(func(ctx context.Context, o *SchemaChunkTemplate) {
		related := o.f.NewConnectionNamespaceWithContext(ctx, mods...)

		m.WithNamespaceConnectionNamespace(related).Apply(ctx, o)
	})
}

func (m schemaChunkMods) WithExistingNamespaceConnectionNamespace(em *models.ConnectionNamespace) SchemaChunkMod {
	return SchemaChunkModFunc(func(ctx context.Context, o *SchemaChunkTemplate) {
		o.r.NamespaceConnectionNamespace = &schemaChunkRNamespaceConnectionNamespaceR{
			o: o.f.FromExistingConnectionNamespace(em),
		}
	})
}

func (m schemaChunkMods) WithoutNamespaceConnectionNamespace() SchemaChunkMod {
	return SchemaChunkModFunc(func(ctx context.Context, o *SchemaChunkTemplate) {
		o.r.NamespaceConnectionNamespace = nil
	})
}

func (m schemaChunkMods) WithSnapshotSchemaSnapshot(rel *SchemaSnapshotTemplate) SchemaChunkMod {
	return SchemaChunkModFunc(func(ctx context.Context, o *SchemaChunkTemplate) {
		o.r.SnapshotSchemaSnapshot = &schemaChunkRSnapshotSchemaSnapshotR{
			o: rel,
		}
	})
}

func (m schemaChunkMods) WithNewSnapshotSchemaSnapshot(mods ...SchemaSnapshotMod) SchemaChunkMod {
	return SchemaChunkModFunc(func(ctx context.Context, o *SchemaChunkTemplate) {
		related := o.f.NewSchemaSnapshotWithContext(ctx, mods...)

		m.WithSnapshotSchemaSnapshot(related).Apply(ctx, o)
	})
}

func (m schemaChunkMods) WithExistingSnapshotSchemaSnapshot(em *models.SchemaSnapshot) SchemaChunkMod {
	return SchemaChunkModFunc(func(ctx context.Context, o *SchemaChunkTemplate) {
		o.r.SnapshotSchemaSnapshot = &schemaChunkRSnapshotSchemaSnapshotR{
			o: o.f.FromExistingSchemaSnapshot(em),
		}
	})
}

func (m schemaChunkMods) WithoutSnapshotSchemaSnapshot() SchemaChunkMod {
	return SchemaChunkModFunc(func(ctx context.Context, o *SchemaChunkTemplate) {
		o.r.SnapshotSchemaSnapshot = nil
	})
}
