// Code generated by mockery v2.53.5. DO NOT EDIT.

package testing

import (
	context "context"

	schemas "github.com/Uncensored-Developer/datalk/apps/backend/services/schemas/pkg/schemas"
	mock "github.com/stretchr/testify/mock"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

// GetSnapshot provides a mock function with given fields: ctx, snapshotID
func (_m *Storage) GetSnapshot(ctx context.Context, snapshotID int32) (schemas.Snapshot, error) {
	ret := _m.Called(ctx, snapshotID)

	if len(ret) == 0 {
		panic("no return value specified for GetSnapshot")
	}

	var r0 schemas.Snapshot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (schemas.Snapshot, error)); ok {
		return rf(ctx, snapshotID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) schemas.Snapshot); ok {
		r0 = rf(ctx, snapshotID)
	} else {
		r0 = ret.Get(0).(schemas.Snapshot)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, snapshotID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertChunk provides a mock function with given fields: ctx, snapshot
func (_m *Storage) InsertChunk(ctx context.Context, snapshot *schemas.Chunk) error {
	ret := _m.Called(ctx, snapshot)

	if len(ret) == 0 {
		panic("no return value specified for InsertChunk")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *schemas.Chunk) error); ok {
		r0 = rf(ctx, snapshot)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertSnapshot provides a mock function with given fields: ctx, snapshot
func (_m *Storage) InsertSnapshot(ctx context.Context, snapshot *schemas.Snapshot) error {
	ret := _m.Called(ctx, snapshot)

	if len(ret) == 0 {
		panic("no return value specified for InsertSnapshot")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *schemas.Snapshot) error); ok {
		r0 = rf(ctx, snapshot)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
},
) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
