// Code generated by mockery v2.53.5. DO NOT EDIT.

package testing

import (
	context "context"

	connections "github.com/Uncensored-Developer/datalk/apps/backend/services/connections/pkg/connections"

	mock "github.com/stretchr/testify/mock"

	storage "github.com/Uncensored-Developer/datalk/apps/backend/services/connections/internal/storage"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

// DeleteConnection provides a mock function with given fields: ctx, id
func (_m *Storage) DeleteConnection(ctx context.Context, id int32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteConnection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListAccess provides a mock function with given fields: ctx, params
func (_m *Storage) ListAccess(ctx context.Context, params storage.ListAccessParam) ([]*connections.Access, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListAccess")
	}

	var r0 []*connections.Access
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, storage.ListAccessParam) ([]*connections.Access, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, storage.ListAccessParam) []*connections.Access); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*connections.Access)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, storage.ListAccessParam) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListConnections provides a mock function with given fields: ctx, params
func (_m *Storage) ListConnections(ctx context.Context, params storage.ListConnectionsParam) ([]*connections.Connection, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListConnections")
	}

	var r0 []*connections.Connection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, storage.ListConnectionsParam) ([]*connections.Connection, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, storage.ListConnectionsParam) []*connections.Connection); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*connections.Connection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, storage.ListConnectionsParam) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateConnection provides a mock function with given fields: ctx, connection
func (_m *Storage) UpdateConnection(ctx context.Context, connection *connections.Connection) error {
	ret := _m.Called(ctx, connection)

	if len(ret) == 0 {
		panic("no return value specified for UpdateConnection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *connections.Connection) error); ok {
		r0 = rf(ctx, connection)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpsertAccess provides a mock function with given fields: ctx, access
func (_m *Storage) UpsertAccess(ctx context.Context, access *connections.Access) error {
	ret := _m.Called(ctx, access)

	if len(ret) == 0 {
		panic("no return value specified for UpsertAccess")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *connections.Access) error); ok {
		r0 = rf(ctx, access)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpsertConnection provides a mock function with given fields: ctx, connection
func (_m *Storage) UpsertConnection(ctx context.Context, connection *connections.Connection) error {
	ret := _m.Called(ctx, connection)

	if len(ret) == 0 {
		panic("no return value specified for UpsertConnection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *connections.Connection) error); ok {
		r0 = rf(ctx, connection)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
},
) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
