// Code generated by mockery v2.53.5. DO NOT EDIT.

package testing

import (
	context "context"

	internalchat "github.com/Uncensored-Developer/datalk/apps/backend/services/chat/internal/chat"
	chat "github.com/Uncensored-Developer/datalk/apps/backend/services/chat/pkg/chat"
	llm "github.com/Uncensored-Developer/datalk/apps/backend/services/chat/pkg/llm"
	mock "github.com/stretchr/testify/mock"
)

// API is an autogenerated mock type for the Client type
type API struct {
	mock.Mock
}

// CreateConversation provides a mock function with given fields: ctx, userID, params
func (_m *API) CreateConversation(ctx context.Context, userID int32, params chat.CreateConversationParams) (*chat.Conversation, error) {
	ret := _m.Called(ctx, userID, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateConversation")
	}

	var r0 *chat.Conversation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, chat.CreateConversationParams) (*chat.Conversation, error)); ok {
		return rf(ctx, userID, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, chat.CreateConversationParams) *chat.Conversation); ok {
		r0 = rf(ctx, userID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chat.Conversation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, chat.CreateConversationParams) error); ok {
		r1 = rf(ctx, userID, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteConversation provides a mock function with given fields: ctx, userID, conversationID
func (_m *API) DeleteConversation(ctx context.Context, userID int32, conversationID int64) error {
	ret := _m.Called(ctx, userID, conversationID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteConversation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int64) error); ok {
		r0 = rf(ctx, userID, conversationID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetConversation provides a mock function with given fields: ctx, userID, conversationID
func (_m *API) GetConversation(ctx context.Context, userID int32, conversationID int64) (*chat.Conversation, error) {
	ret := _m.Called(ctx, userID, conversationID)

	if len(ret) == 0 {
		panic("no return value specified for GetConversation")
	}

	var r0 *chat.Conversation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int64) (*chat.Conversation, error)); ok {
		return rf(ctx, userID, conversationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, int64) *chat.Conversation); ok {
		r0 = rf(ctx, userID, conversationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chat.Conversation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, int64) error); ok {
		r1 = rf(ctx, userID, conversationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAvailableModels provides a mock function with given fields: ctx
func (_m *API) ListAvailableModels(ctx context.Context) ([]llm.Model, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAvailableModels")
	}

	var r0 []llm.Model
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]llm.Model, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []llm.Model); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]llm.Model)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListConversations provides a mock function with given fields: ctx, userID, filter
func (_m *API) ListConversations(ctx context.Context, userID int32, filter chat.ListConversationsFilter) ([]*chat.Conversation, error) {
	ret := _m.Called(ctx, userID, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListConversations")
	}

	var r0 []*chat.Conversation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, chat.ListConversationsFilter) ([]*chat.Conversation, error)); ok {
		return rf(ctx, userID, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, chat.ListConversationsFilter) []*chat.Conversation); ok {
		r0 = rf(ctx, userID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*chat.Conversation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, chat.ListConversationsFilter) error); ok {
		r1 = rf(ctx, userID, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListMessages provides a mock function with given fields: ctx, userID, filter
func (_m *API) ListMessages(ctx context.Context, userID int32, filter chat.ListMessagesFilter) ([]*chat.MessageDetails, error) {
	ret := _m.Called(ctx, userID, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListMessages")
	}

	var r0 []*chat.MessageDetails
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, chat.ListMessagesFilter) ([]*chat.MessageDetails, error)); ok {
		return rf(ctx, userID, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, chat.ListMessagesFilter) []*chat.MessageDetails); ok {
		r0 = rf(ctx, userID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*chat.MessageDetails)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, chat.ListMessagesFilter) error); ok {
		r1 = rf(ctx, userID, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListProviderConfigs provides a mock function with given fields: ctx
func (_m *API) ListProviderConfigs(ctx context.Context) ([]*llm.ProviderConfig, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListProviderConfigs")
	}

	var r0 []*llm.ProviderConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*llm.ProviderConfig, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*llm.ProviderConfig); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*llm.ProviderConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveProviderConfig provides a mock function with given fields: ctx, params
func (_m *API) SaveProviderConfig(ctx context.Context, params internalchat.SaveProviderConfigParams) (*llm.ProviderConfig, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for SaveProviderConfig")
	}

	var r0 *llm.ProviderConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, internalchat.SaveProviderConfigParams) (*llm.ProviderConfig, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, internalchat.SaveProviderConfigParams) *llm.ProviderConfig); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*llm.ProviderConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, internalchat.SaveProviderConfigParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SendMessage provides a mock function with given fields: ctx, params
func (_m *API) SendMessage(ctx context.Context, params chat.SendMessageParams) (*chat.AssistantTurn, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 *chat.AssistantTurn
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, chat.SendMessageParams) (*chat.AssistantTurn, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, chat.SendMessageParams) *chat.AssistantTurn); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chat.AssistantTurn)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, chat.SendMessageParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SendMessageWithProgress provides a mock function with given fields: ctx, params, progress
func (_m *API) SendMessageWithProgress(ctx context.Context, params chat.SendMessageParams, progress chat.SendMessageProgressHandler) (*chat.AssistantTurn, error) {
	ret := _m.Called(ctx, params, progress)

	if len(ret) == 0 {
		panic("no return value specified for SendMessageWithProgress")
	}

	var r0 *chat.AssistantTurn
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, chat.SendMessageParams, chat.SendMessageProgressHandler) (*chat.AssistantTurn, error)); ok {
		return rf(ctx, params, progress)
	}
	if rf, ok := ret.Get(0).(func(context.Context, chat.SendMessageParams, chat.SendMessageProgressHandler) *chat.AssistantTurn); ok {
		r0 = rf(ctx, params, progress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chat.AssistantTurn)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, chat.SendMessageParams, chat.SendMessageProgressHandler) error); ok {
		r1 = rf(ctx, params, progress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TestProviderConfig provides a mock function with given fields: ctx, params
func (_m *API) TestProviderConfig(ctx context.Context, params internalchat.TestProviderConfigParams) (*internalchat.TestProviderConfigResult, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for TestProviderConfig")
	}

	var r0 *internalchat.TestProviderConfigResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, internalchat.TestProviderConfigParams) (*internalchat.TestProviderConfigResult, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, internalchat.TestProviderConfigParams) *internalchat.TestProviderConfigResult); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internalchat.TestProviderConfigResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, internalchat.TestProviderConfigParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAPI creates a new instance of API. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAPI(t interface {
	mock.TestingT
	Cleanup(func())
},
) *API {
	mock := &API{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
