// Code generated by mockery v2.53.5. DO NOT EDIT.

package testing

import (
	context "context"

	chat "github.com/Uncensored-Developer/datalk/apps/backend/services/chat/pkg/chat"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// CreateConversation provides a mock function with given fields: ctx, userID, params
func (_m *Service) CreateConversation(ctx context.Context, userID int32, params chat.CreateConversationParams) (*chat.Conversation, error) {
	ret := _m.Called(ctx, userID, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateConversation")
	}

	var r0 *chat.Conversation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, chat.CreateConversationParams) (*chat.Conversation, error)); ok {
		return rf(ctx, userID, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, chat.CreateConversationParams) *chat.Conversation); ok {
		r0 = rf(ctx, userID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chat.Conversation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, chat.CreateConversationParams) error); ok {
		r1 = rf(ctx, userID, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetConversation provides a mock function with given fields: ctx, userID, conversationID
func (_m *Service) GetConversation(ctx context.Context, userID int32, conversationID int64) (*chat.Conversation, error) {
	ret := _m.Called(ctx, userID, conversationID)

	if len(ret) == 0 {
		panic("no return value specified for GetConversation")
	}

	var r0 *chat.Conversation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int64) (*chat.Conversation, error)); ok {
		return rf(ctx, userID, conversationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, int64) *chat.Conversation); ok {
		r0 = rf(ctx, userID, conversationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chat.Conversation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, int64) error); ok {
		r1 = rf(ctx, userID, conversationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListConversations provides a mock function with given fields: ctx, userID, filter
func (_m *Service) ListConversations(ctx context.Context, userID int32, filter chat.ListConversationsFilter) ([]*chat.Conversation, error) {
	ret := _m.Called(ctx, userID, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListConversations")
	}

	var r0 []*chat.Conversation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, chat.ListConversationsFilter) ([]*chat.Conversation, error)); ok {
		return rf(ctx, userID, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, chat.ListConversationsFilter) []*chat.Conversation); ok {
		r0 = rf(ctx, userID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*chat.Conversation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, chat.ListConversationsFilter) error); ok {
		r1 = rf(ctx, userID, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListMessages provides a mock function with given fields: ctx, userID, filter
func (_m *Service) ListMessages(ctx context.Context, userID int32, filter chat.ListMessagesFilter) ([]*chat.MessageDetails, error) {
	ret := _m.Called(ctx, userID, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListMessages")
	}

	var r0 []*chat.MessageDetails
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, chat.ListMessagesFilter) ([]*chat.MessageDetails, error)); ok {
		return rf(ctx, userID, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, chat.ListMessagesFilter) []*chat.MessageDetails); ok {
		r0 = rf(ctx, userID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*chat.MessageDetails)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, chat.ListMessagesFilter) error); ok {
		r1 = rf(ctx, userID, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SendMessage provides a mock function with given fields: ctx, params
func (_m *Service) SendMessage(ctx context.Context, params chat.SendMessageParams) (*chat.AssistantTurn, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 *chat.AssistantTurn
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, chat.SendMessageParams) (*chat.AssistantTurn, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, chat.SendMessageParams) *chat.AssistantTurn); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chat.AssistantTurn)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, chat.SendMessageParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
},
) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
